### ISSUE TITLE
Implement Reward Video

### ISSUE THREAD

**Issue by Screeze** [admob-plus/admob-plus#1]
As requested for your priorization:
Rewarded Videos are pretty important for me before I can use this.

And I directly have some request about how you do it:
So what troubled me in cordova-admob-pro when I tried to add reward videos witht hat plugin:
I had to listen to global events to know when the video showed completely.
I would prefer an interface like
```
ads.showRewardVideo(config).then((shownCompletely) => { 
    if(shownCompletely) {
        // give reward
    } else {
       // show some hint 
   }
 })
.catch(() => {
   // failed to show
});
```

I don't know if it is possible or if this is a restriction from admob: But it would be nice to be able to request if ads are available without loading them. At the moment I always have to preload some ad to know if I can show a button which offers this. This uses bandwith which I would like to only use when user actually decides to watch a video. But I fear this is an admob limitation maybe I don't know the admob interface.

**Comment by hckr** [comment]
Hi, I see you've marked this issue as Done, but there is no information about this new API in [the docs](https://admob-plus.github.io/docs/show-reward-video.html). I'd like to use your plugin, but without the good-enough docs, I don't know how to use it.

**Comment by ratson** [comment]
It is my bad to not explain that the proposed API is not used, but an implementation of Reward Video Ad is available. I think the `load` -> `show` promise API should address common use cases, for more complicated one, the event API should fill the gap.

@hckr Let me know if you think anything confusing in the docs.

**Comment by hckr** [comment]
Ah, ok. Can this promise also be rejected, for example on loading error? Do any of callback functions presented in the docs receive any arguments or, as implicitly presented in docs, they receive none?

BTW. Could maybe show() also return a promise (which would be resolved when the reward should be given to the user and rejected otherwise)?

**Comment by mateusjose** [comment]
The reward video can set a User ID for futher server sode verification?

**Comment by willmeet** [comment]
[That issue is clearly shown here how to solve admob failed to load ads](http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html)

**Comment by ratson** [comment]
Feature is implemented in latest release.
