### ISSUE TITLE
[Funding Suggestion]

### ISSUE THREAD

**Issue by Blanketsniffer** [admob-plus/admob-plus#10]
Patreon Page, paypal.me page would be much easier for non-fixed amounts and you would get funding for your name @ratson so that would also cover legacy project admob-free

**Comment by ratson** [comment]
@Blanketsniffer Thank you for the suggestion. I have setup https://www.paypal.me/ratsonal (sadly can not register as ratson).

I have updated [FAQ](https://admob-plus.github.io/docs/faq.html#how-to-fund-this-project) to include the new funding option.
