### ISSUE TITLE
Banner Ad Aligned Left

### ISSUE THREAD

**Issue by FlippingWork** [admob-plus/admob-plus#100]
Hello,

This is a very good banner ad plugin and I would like to thank you for your hard work on it! We just have a quick issue on it that maybe you can shed some light on, and that is that the banner ad is aligned to the left when it displays at the bottom of the screen. How do we center the banner ad? We also tried setting the position in the setting but when we set the position it seems to not show the banner ad at all? How can we get the banner ad to display in the center bottom of the screen instead of bottom left?

Thank you!

**Comment by aabdolla** [comment]
I am also experiencing this and no idea on a solution as of yet.

**Comment by ratson** [comment]
A screenshot would be helpful

**Comment by FlippingWork** [comment]
Just to clarify the issue only occurs on larger screens, it doesn't occur on old iPhones like iPhone 5!

**Comment by FlippingWork** [comment]
Attached is the screenshot of your admob-plus banner mis-aligned left on a iPhone 8 Plus Simulator on Mac OS X per your request:

![banner_left_align_issue_iphone_8_plus](https://user-images.githubusercontent.com/50723373/58863843-74742400-8668-11e9-8eef-7282ac70e03e.png)

**Comment by FlippingWork** [comment]
The issue seems to occur intermittently, it occurs on some banners with some devices and doesn't occur on other banners on the same device, so I am not sure if there is a way to ensure that all banners are always centered on every device in the safe area or if the issue is coming from your plugin or the banner provider, but perhaps these details will help you draw a conclusion in your investigation!!!

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk
