### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by gartorware** [admob-plus/admob-plus#102]
### Is this a bug report?

No

### Expected Behavior

Plugin should allow to forward user consent to admob sdk as explained here:
https://developers.google.com/admob/android/eu-consent#forward_consent_without_the_consent_sdk
This is mandatory to use the plugin within Europe.

The only thing needed seems to be to pass a string in the extras Bundle:
```
Bundle extras = new Bundle();
extras.putString("npa", "1");

AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();
```

There is an [automatic-closed issue about this](https://github.com/admob-plus/admob-plus/issues/71)
This has been requested as well for admob-free [here](https://github.com/ratson/cordova-plugin-admob-free/issues/210), where it is already doable as explained in the issue.

Maybe it is enough with allowing to pass a generic `extras` parameter, so users can customize it.

Thank you.

**Comment by svzi** [comment]
I would also like to see this feature added.

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by ReallySmallSoftware** [comment]
I could take a look at this if you like? Would you have a preferred way of supporting it? Another method on the AdMob class maybe? setConsentRequired(value:boolean) perhaps?

**Comment by svzi** [comment]
Not sure about that, in first place it's really imported to be added. How does it work in the native SDK? Maybe that should be the way it should work here as well, or at least similar.

**Comment by ReallySmallSoftware** [comment]
I agree in hindsight - having had a closer look there are really 2 aspects - one is asking for consent, the other is telling the SDK about the choice the user made (the npa setting) - which looks as simple as passing another option as a poster above sort of suggested. I believe this is just the latter.

**Comment by svzi** [comment]
Not sure about that. As there is a Consent SDK available, it would make a ton of sense to have this included here, because it's needed for every app that serves ads in Europe.

**Comment by alexp25** [comment]
I've found this on their website https://admob-plus.github.io/docs/installation which seems to add the ```npa``` flag: https://github.com/admob-plus/admob-plus/blob/master/examples/consent/www/js/index.js#L15

**Comment by brunoalex** [comment]
can any one use  .load({ id: 'ca-app-pub-xxx', npa: '1'  }) with sucess ?

**Comment by alexp25** [comment]
I had a look at the code and it has references to the ```npa``` flag and using ```addNetworkExtrasBundle```. However, is there a way to know for sure that the ad is called with this option?

**Comment by alexp25** [comment]
It is theoretically a very critical issue so it needs to be properly tested and documented ASAP as you can get fined at least 20 million for infringements.

**Comment by ratson** [comment]
Close as documented in https://admob-plus.github.io/docs/cordova/consent
