### ISSUE TITLE
Failed to load file: www/plugins/cordova-admob-plus/www/admob.js.map resource

### ISSUE THREAD

**Issue by FlippingWork** [admob-plus/admob-plus#103]
The following error is occurring when launching on iOS simulator on Mac OS and inspecting the javascript web error console with Safari developer toolbar:

Failed to load file:///var/containers/Bundle/Application/4E8/Test.app/www/plugins/cordova-admob-plus/www/admob.js.map resource: The requested URL was not found on this server.

It is not a fatal error, but it seems like you are missing the admob.js.map file that should be bundled with admob.js file.

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk
