### ISSUE TITLE
Don't use ES6 javascript in your plugin

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#104]
Don't use ES6 javascript, because Android 4.4, Android 5.0,5.1 and Android 6.0 do not support the arrow functions, classes and all other ES6 is not supported methods. I need to reproduce your javascript to ES5 version through https://babeljs.io/repl here.

**Comment by ChadoriRebornXD** [comment]
You sure about that? I think it already does. :thinking:

**Comment by merbin2012** [comment]
Admin changed the code. Thank you
