### ISSUE TITLE
Admob banner view load before load the banner

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#105]
When I request the banner ads, the "adView" is load before successfully load the AdMob banner ads.
Please do the following changes

**BannerAd.java**
Move **addBannerView(adView);** from **show(AdRequest adRequest)** to 
**getLoadedEvent()**

The final code should be added like below

```java
 String getLoadedEvent() {
        addBannerView(adView);
        return Events.BANNER_LOAD;
}

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk
