### ISSUE TITLE
ios cordova 9 never loads ad

### ISSUE THREAD

**Issue by erikkurtu** [admob-plus/admob-plus#108]
I cannot get the interstitial or reward load promise to return anything. I don't see any errors in build or javascript console. 

Running:
Cordova 9.01, cordova-ios 5, xcode 10.2.1

I have this in config.xml
 <preference name="UseSwiftLanguageVersion" value="5" />

And this is my package.xml:
{
  "name": "com.eventfulapps.lohi",
  "displayName": "lohi",
  "version": "0.7.0",
  "description": "lohi - the game of lower or higher",
  "main": "js/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Erik Wilder",
  "dependencies": {
    "cc.fovea.cordova.purchase": "^8.1.1",
    "com.darktalker.cordova.screenshot": "git+https://github.com/gitawego/cordova-screenshot.git",
    "cordova-admob-plus": "^0.30.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-apprate": "^1.4.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-game": "^1.0.120",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-google-analytics": "^1.8.6",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-x-socialsharing": "^5.4.7",
    "es6-promise-plugin": "^4.2.2"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-apprate": {},
      "cordova-plugin-device": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-x-socialsharing": {
        "PHOTO_LIBRARY_ADD_USAGE_DESCRIPTION": "This app requires photo library access to function properly.",
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "This app requires photo library access to function properly."
      },
      "cordova-plugin-game": {},
      "com.darktalker.cordova.screenshot": {},
      "cc.fovea.cordova.purchase": {},
      "cordova-plugin-google-analytics": {},
      "cordova-admob-plus": {
        "APP_ID_ANDROID": "ca-app-pub-1148177229257417~9970435587",
        "APP_ID_IOS": "ca-app-pub-1148177229257417~9970435587"
      }
    },
    "platforms": [
      "ios"
    ]
  }
}

Been working on it for a few days with no luck.

**Comment by erikkurtu** [comment]
I do actually get this warning when adding the ios platform:

Installing "cordova-plugin-add-swift-support" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by Kaz-** [comment]
I'm having exact same issue on Android & iOS with Cordova 9.01 ... No error on console, .then() is correctly being executed, no error catched, but no ads are showing.

**Comment by rashnk** [comment]
it does not return resolve or reject
