### ISSUE TITLE
invalid action

### ISSUE THREAD

**Issue by isularifin** [admob-plus/admob-plus#109]
hi, Everything is working well. The ads can load. But i have got alert notification "invalid action" after reloaded my APP. Is it bug?

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by simontribus** [comment]
I'm facing the same issue, but only if I have my App in debug. The first time it runs perfectly, after recompile the alert box shows: "Invalid action"

**Comment by alexstanbury** [comment]
Same here.

This is the offending code in admob.ts

`private ready() {
    exec(
      event => {
        this.state.applicationId = event.data.applicationId
        fireDocumentEvent(event.type, event.data)
      },
      err => {
        alert(err)
      },
      NativeActions.Service,
      NativeActions.ready,
    )
  }`

**Comment by berokapp** [comment]
I'm facing the same issue, how to fix it please?

**Comment by esavichev** [comment]
The same issue. Is there any plan to fix it or at least a workaround?

**Comment by berokapp** [comment]
i fixed by initialize cordova deviceready
