### ISSUE TITLE
IOS Banner sets overlayWebView to true

### ISSUE THREAD

**Issue by jasonandress** [admob-plus/admob-plus#112]
IONIC V1 Project. When I show a banner ad it overrides the StatusBar Plugin overlayWebView setting and allows it to overlay. Showing a RewardVideo reverts it until the banner refreshes and it goes back to incorrect. I've removed the statusbar plugin with no difference.

### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 8.25 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      cordova-admob-plus: ^0.30.0 => 0.30.0 
      cordova-android: ^8.0.0 => 8.0.0 
      cordova-ios: ^5.0.1 => 5.0.1 
      cordova-plugin-device: ^2.0.3 => 2.0.3 
      cordova-plugin-inappbrowser: ^3.1.0 => 3.1.0 
      cordova-plugin-ionic-keyboard: ^2.1.3 => 2.1.3 
      cordova-plugin-ionic-webview: ^4.1.1 => 4.1.1 
      cordova-plugin-local-notification: ^0.9.0-beta.2 => 0.9.0-beta.2 
      cordova-plugin-network-information: ^2.0.2 => 2.0.2 
      cordova-plugin-purchases: ^0.2.1 => 0.2.1 
      cordova-plugin-settings-hook: ^0.3.1 => 0.3.1 
      cordova-plugin-splashscreen: ^5.0.3 => 5.0.3 
      cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
    npmGlobalPackages:
      cordova: 9.0.0
      ionic: 5.2.3

### Steps to Reproduce

1. admob.banner.show({
		    id: {
		      // replace with your ad unit IDs
		    	android: admobid.android_banner,
		    	ios: admobid.ios_banner
		    }
		});

### Expected Behavior

Showing Banner should not affect the StatusBar.overlaysWebView(false);

### Actual Behavior

Showing Banner unsets the StatusBar.overlaysWebView(false); settings which allows the status bar to overlap the WebView.

When a Reward Video shows the StatusBar is correct until the Banner is refreshed.

**Comment by Steco17** [comment]
Hi. Am having the same issue here. Any fix to this?

**Comment by jasonandress** [comment]
I haven't found a fix. I've simply not used banners.
