### ISSUE TITLE
Ionic 4 + cordova-admob-plus build issue when using with cordova-google-plus. App get build successfully if i remove admob

### ISSUE THREAD

**Issue by bhavin9695** [admob-plus/admob-plus#115]
### Is this a bug report?

yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 7.45 GB / 15.37 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    SDKs:
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.0
        System Images: android-25 | Google APIs Intel x86 Atom
    Languages:
      Java: 1.8.0_191 - /usr/bin/javac
    npmPackages:
      cordova-admob-plus: 0.30.0 => 0.30.0 
      cordova-android: 7.1.4 => 7.1.4 
      cordova-plugin-appminimize: 1.0.1 => 1.0.1 
      cordova-plugin-camera: 4.1.0 => 4.1.0 
      cordova-plugin-crop: 0.4.0 => 0.4.0 
      cordova-plugin-datepicker: 0.9.3 => 0.9.3 
      cordova-plugin-device: ^2.0.2 => 2.0.2 
      cordova-plugin-file: 6.0.2 => 6.0.2 
      cordova-plugin-googleplus: 8.0.0 => 8.0.0 
      cordova-plugin-ionic-keyboard: ^2.1.3 => 2.1.3 
      cordova-plugin-ionic-webview: ^4.1.0 => 4.1.0 
      cordova-plugin-splashscreen: ^5.0.2 => 5.0.2 
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2 
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3 
      cordova-sqlite-storage: 3.2.1 => 3.2.1 
      info.protonet.imageresizer: 0.1.1 => 0.1.1 
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 5.0.0

AndroidManifest.xml: looks ok

### Steps to Reproduce

(Write your steps here:)

1) ionic cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx --variable APP_ID_IOS=ca-app-pub-xxx~xxx
2) npm install --save @ionic-native/admob-plus

 

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)
Build issue in ionic 4.

`Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_40ah3zdub44u38bs07zf6gszx.run(/home/abc/project/adMobDemo/adMobDemo/platforms/android/app/build.gradle:148)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:checkDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processDebugManifest
:CordovaLib:javaPreCompileDebug
:CordovaLib:processDebugJavaRes NO-SOURCE
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:compileDebugAidl
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
/home/abc/project/adMobDemo/adMobDemo/platforms/android/app/src/main/java/nl/xservices/plugins/GooglePlus.java:182: error: cannot access zzbfm
            .addApi(Auth.GOOGLE_SIGN_IN_API, gso.build());
                   ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/abc/project/adMobDemo/adMobDemo/platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:app:compileDebugJavaWithJavac FAILED
27 actionable tasks: 27 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
/home/abc/project/adMobDemo/adMobDemo/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/abc/project/adMobDemo/adMobDemo/platforms/android/app/src/main/java/nl/xservices/plugins/GooglePlus.java:182: error: cannot access zzbfm
            .addApi(Auth.GOOGLE_SIGN_IN_API, gso.build());
                   ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/abc/project/adMobDemo/adMobDemo/platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
[ERROR] An error occurred while running subprocess cordova.
        cordova build android --device exited with exit code 1.
        Re-running this command with the --verbose flag may provide more information.`

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by bhavin9695** [comment]
Ok. I found the solution though it is not good way but it can help.
I think when you use multiple google service using cordova plugins it creates conflicts for `com.google.android.gms:play-services-(ads/base/auth/identity)` for android platform. i am not sure about ios platform. 
i am using cordova-google-plus and cordova-admob-plus both in my app. i also saw issue created for plugin cordova-google-plus and fcm (ref : https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/349)

so for my case,  above issue was occurring because when install admob plugin it added following line /platforms/android/project.properties 
`cordova.system.library.1=com.google.android.gms:play-services-ads:17.2.0`

and same was also there as below with version 11.0.4, so that was creating conflicts.
```
cordova.system.library.2=com.google.android.gms:play-services-base:11.0.4
**cordova.system.library.3=com.google.android.gms:play-services-ads:11.0.4**
cordova.system.library.4=com.android.support:support-v4:27.+
cordova.system.library.5=com.soundcloud.android:android-crop:1.0.0@aar
cordova.system.library.6=com.google.android.gms:play-services-auth:11.8.0
cordova.system.library.7=com.google.android.gms:play-services-identity:11.8.0
cordova.system.library.8=com.android.support:support-annotations:27.+
```

so i changed all version (17.2.0/11.0.4/11.8.0) to 15.0.1 and it resolved the issue.

though this is not good approach as every time you delete the platform directory, you will require to do above changes.

if there is any other good approach to fix this permanently then i would be happy to know.

**Comment by tarunmishra592** [comment]
Can you hep me i don't understand my compatbailty i am trying last 2 days 

**project.properties**  
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-auth:11.8.0
cordova.system.library.2=com.google.android.gms:play-services-identity:11.8.0
cordova.gradle.include.1=phonegap-plugin-barcodescanner/retailordering-barcodescanner.gradle
cordova.system.library.3=com.android.support:support-v4:27.+
cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.5=com.android.support:support-v4:27.+
cordova.gradle.include.2=cordova-support-google-services/retailordering-build.gradle
cordova.system.library.8=com.google.firebase:firebase-core:10.+
cordova.system.library.9=com.google.firebase:firebase-messaging:10.+
cordova.gradle.include.3=cordova-plugin-fcm-with-dependency-updated-apns/retailordering-FCMPlugin.gradle

**getting error Execution failed for task ':app:processDebugGoogleServices'.**
