### ISSUE TITLE
No Ads Showing on Dev/Production Build But Works With Google's Test Ad Units

### ISSUE THREAD

**Issue by snow-drop** [admob-plus/admob-plus#116]
### Environment
  AdMob Plus Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
      Memory: 4.20 GB / 9.49 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    Languages:
      Java: 1.8.0_201 - /usr/bin/javac
    npmPackages:
      cordova-admob-plus: ^0.30.0 => 0.30.0 
      cordova-android: ^7.1.4 => 7.1.4 
      cordova-plugin-file: ^6.0.2 => 6.0.2 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
      cordova-sqlite-storage: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      cordova: 8.1.1

AndroidManifest.xml: looks ok

### Additional info for Environment
Android 6.0.1 (Marshmallow)
Quasar v1.0.0-beta.4

### Steps to Reproduce
1. Use the Google's Banner and Interstitial test ads on dev, ads displayed properly.
2. Changed to the my own ad units on dev, no ads are showing.
3. Built the app for production with my own ad units, no ads are showing.
4. Check Google Admob account, 75 requests, but no impressions and other stuff, only requests.

### Expected Behavior

App should show the ads.

### Actual Behavior

App not showing ads.

### Reproducible Demo

My hands are full at the moment, will update here if not resolved yet.

### Additional notes

I used the same library months ago and works perfectly. I don't know why this time it fails to display the ads.

Thank you very much.

P.S. I'm only testing the ads so I don't have any stuff running on it. Only blank page to check if there are ads displayed.

**Comment by drrodio** [comment]
Same here. Only tests ads are working, when I link with real ads the screen shows blank page

Thanks in advance!
