### ISSUE TITLE
Google Rejeited Apps - Developer Program Policies violation - WARNING

### ISSUE THREAD

**Issue by 123dma** [admob-plus/admob-plus#119]
### Is this a bug report? 

(YES)

  If you answered "Yes":
  
Rejeiction cause: Disruptive Ads
Description: The user attempts to exit the app and navigate to the home screen, but instead, the expected flow is interrupted by an ad.
Hello Hatson, you need to check if the app LIFECYCLE is paused or closed before to show the  Ad. Google is rejecting Apps. I took a look at the code and I bealive this check need to put here.

Files: Intersticialad.java, bannersad.java
    
```
private void show() {
        if (interstitialAd != null && interstitialAd.isLoaded()) { // NEED TO CHECK APP LIFECYCLE BEFORE SHOW AD (SUBSCRIVE LIFECYCLES ANDROID ONPAUSE ONCLOSE
            interstitialAd.show();
        }
    }
```

### Environment

(paste the output of the command here)

### Steps to Reproduce

(Write your steps here:)

1. 
2. 
3. 

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior
(https://play.google.com/about/monetization-ads/ads/#!?zippy_activeEl=interfering#interfering)

(Write what happened. Please add screenshots!)

### Reproducible Demo
(https://stackoverflow.com/questions/57251947/uncaught-exception-thrown-by-finalizer-all-webview-methods-must-be-called-on-th/57308639#57308639)
(https://stackoverflow.com/questions/57234180/issue-violation-of-interfering-with-apps-third-party-ads-or-device-functional)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by cesarak** [comment]
Sorry, but this is not an error report ...
Under the new Google/AdMob terms, you cannot add interstitial ads when launching your app. You need to add it to your app, showing it properly when a user does something. Hope it helps.

**Comment by 123dma** [comment]
Hello @cesarak 

Could you tell me where you saw this update?. For all I know you can. As long as you don't introduce it initially. You only need to submit after splashScreen.

https://support.google.com/admob/answer/6201362

https://www.blog.google/products/admob/using-splash-pages-to-avoid-unexpected-launch-interstitials/

**Comment by cesarak** [comment]
Hi @123dma 
You are right. The link that you sent describes how to implement interstitial ad. So we did, we followed these rules in our apps.
We've implemented following those steps
`Launch app -> Loading screen -> Interstitial Ad -> Home screen`
but the apps are ALWAYS rejected.
I don't know why but in all cases we receive an email from Google with a policy violation content.
To avoid it, we removed the interstitial ad from app launch.

**Comment by 123dma** [comment]
If the violation presented to you is (https://play.google.com/about/monetization-ads/ads/#!?zippy_activeEl=interfering#interfering) it is because you need to make sure that your AD is not displayed outside the app . This is the fix I am requesting.
