### ISSUE TITLE
PLAY SERVICES VERSION conflict with fcm plugin

### ISSUE THREAD

**Issue by gasci** [admob-plus/admob-plus#131]
### Is this a bug report?

Yes, this is a bug report.

### Environment

cordova-android@8.0.0
cordova-cli@9.0.0

### Steps to Reproduce

1. add https://github.com/fechanique/cordova-plugin-fcm
2. add admob-plus
3. cordova build android

### Expected Behavior

Dependencies conflict.
I couldn't find a common google services version that works for both plugins.

### Actual Behavior

It should have built the android app smoothly.

**Comment by eftas-gka** [comment]
Same with phonegap-plugin-push unfortunately.

**Comment by piernik** [comment]
I think I have the same problem. `cordova-plugin-googlemaps` uses `PLAY_SERVICES_VERSION@15.0.1`. I'm using `ionic`. Hot to solve this problem?

**Comment by gasci** [comment]
We have to force the same version for all plugins; this seems like the only solution.
