### ISSUE TITLE
Outdated Swift version

### ISSUE THREAD

**Issue by jake-c** [admob-plus/admob-plus#132]
### Is this a bug report?

Maybe? I can't get anything to run in Xcode once I add this project. It seems as if it's using a version of Swift that's too old? Maybe this is just me not understanding at all how these plugins are built.

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS Mojave 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 221.20 MB / 16.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.13.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      cordova-admob-plus: ^0.32.0 => 0.32.0 
      cordova-ios: 5.0.1 => 5.0.1 
      cordova-plugin-device: ^2.0.3 => 2.0.3 
      cordova-plugin-ionic-keyboard: ^2.2.0 => 2.2.0 
      cordova-plugin-ionic-webview: ^4.1.3 => 4.1.3 
      cordova-plugin-splashscreen: ^5.0.3 => 5.0.3 
      cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
    npmGlobalPackages:
      cordova: 9.0.0
      ionic: 5.4.6

### Steps to Reproduce

(Write your steps here:)

1. Create new Ionic project
2. Install plugin
3. Open in Xcode with inability to build because no SWIFT version is specified
4. Specify SWIFT version 4+
5. Receive lots of errors

### Expected Behavior

Successfully built

### Actual Behavior

Unsuccessful build

Again all of this could just be my lack of understanding on how all this stuff works together. I'd love to be able to throw ads into my Ionic apps but as of yet I've been unable to do so.

**Comment by eftas-gka** [comment]
Worked for me after changing line 62 in [AMSBanner.swift](https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/ios/AMSBanner.swift) from

`            view.sendSubviewToBack(background)
`

to

`            view.sendSubview(toBack: background)
`

**Comment by JoseGeorges8** [comment]
This is still an issue, is been an issue for the longest time (priorly used to say it was version swift 2.x and the minimum version on Xcode was 3) and @eftas-gka line did not fix it, there's still 43 issues being displayed

**Comment by cumpstey** [comment]
Just leaving my experience here, in the hope that it helps someone else...

There's a note on the installation instructions which says to add this to the Cordova `config.xml`:

```
<preference name="UseSwiftLanguageVersion" value="5" />
```

This gets rid of the above error about `sendSubview` but adds a whole lot of other errors about referencing unknown types such as `GADRequest`. Then make this change to `plugins/cordova-admob-plus/plugin.xml`, and remove and readd the ios platform.

```
        <!-- <framework src="Google-Mobile-Ads-SDK" type="podspec" spec="~> 7.53.1" /> -->
        <podspec>
            <config>
                <src url="https://github.com/CocoaPods/Specs.git" />
            </config>
            <pods>
                <pod name="Google-Mobile-Ads-SDK" />
            </pods>
        </podspec>
```

This allows the project to build, and it'll then (at least) display test ads once it's run on an iPhone.

Fingers crossed for it working in prod mode!

**Comment by Carlosps** [comment]
@cumpstey
Still not working, but thank you for your help
