### ISSUE TITLE
admob-plus won't build for iOS on Adobe Phonegap Build

### ISSUE THREAD

**Issue by jglesner** [admob-plus/admob-plus#137]
### Is this a bug report?
Yes

### Environment
Adobe Phonegap Build CLI 9.0.0 for iOS

### Steps to Reproduce
The installation in phonegap gets to this line and croaks:
`<framework src="Google-Mobile-Ads-SDK" type="podspec" spec="~> 7.51" />`

The error is: 
```
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1
```
### Expected Behavior
The expected behavior is that the build succeeds.  

I believe this is an Adobe Phonegap Build issue, but it's remained unresolved for a long time, and it doesn't look like they're going to fix it.  Has anyone managed to get passed this, or Is it possible to use a separate option similar to the admob-sdk package that was available under admob-free?

**Comment by lopezasin** [comment]
for android either

**Comment by Be4t5** [comment]
Same problem on iOS, works fine in Android... Any solution?

**Comment by juxfr** [comment]
Exactly the same problem for me.
Is it possible to re-open the case?
