### ISSUE TITLE
Unable to build app with admob-plus

### ISSUE THREAD

**Issue by MajesticThrust** [admob-plus/admob-plus#139]
### Is this a bug report?

Yes.

### Environment

I've tried fixing the problem by adding androidx plugins (`cordova-plugin-androidx` and `cordova-plugin-androidx-adapter`), so I'm attaching 2 environments, with and without those plugins respectably:

[environment_with_androidx_plugins.txt](https://github.com/admob-plus/admob-plus/files/3945100/environment_with_androidx_plugins.txt)
[environment_without_androidx_plugins.txt](https://github.com/admob-plus/admob-plus/files/3945102/environment_without_androidx_plugins.txt)

### Steps to Reproduce

1. Add `cordova-admob-plus` to existing app with these plugins installed:
```
cordova-plugin-whitelist
cordova-plugin-statusbar
cordova-plugin-device
cordova-plugin-splashscreen
cordova-plugin-ionic-keyboard
cordova-plugin-appavailability
cordova-plugin-youtube-video-player
cordova-plugin-market
cordova-plugin-x-socialsharing
cordova-plugin-ionic-webview
cordova-plugin-flurryanalytics
cordova-sqlite-storage
cordova-plugin-apprate
cordova-plugin-email-composer
cordova-plugin-android-permissions
cordova-plugin-inappbrowser
cordova-admob-plus

```
2. Try to build the app with `ionic cordova build android`

### Expected Behavior

A successful build.

### Actual Behavior

Errors during the build.
Here are the logs for both cases - with and without androidx plugins.
[build_with_androidx_plugins.txt](https://github.com/admob-plus/admob-plus/files/3945693/build_with_androidx_plugins.txt)
[build_without_androidx_plugins.txt](https://github.com/admob-plus/admob-plus/files/3945694/build_without_androidx_plugins.txt)

### Reproducible Demo

A repo which seems to reproduce the issue. It's Ionic 3, just FYI.
https://github.com/MajesticThrust/issue-example-admob-plus

I've also managed to pinpoint some problematic plugins that can't be build together with `cordova-admob-plus`. Here are the logs:
[cordova-plugin-email-composer.txt](https://github.com/admob-plus/admob-plus/files/3945718/cordova-plugin-email-composer.txt)
[cordova-plugin-flurryanalytics.txt](https://github.com/admob-plus/admob-plus/files/3945719/cordova-plugin-flurryanalytics.txt)
[cordova-plugin-x-socialsharing.txt](https://github.com/admob-plus/admob-plus/files/3945720/cordova-plugin-x-socialsharing.txt)

I've only tried to build those without androidx plugins.
The repo has a script for automatic building and saving error build logs.

**Comment by lopezasin** [comment]
With Phonegp build dont compile :(

**Comment by crushingCodes** [comment]
Hi Majestic

Thank you for this talking about this error, I managed to fix it with  the following:

Adding these two lines to gradle.properties
android.useAndroidX=true
android.enableJetifier=true

Plus 

cordova plugins add cordova-plugin-androidx
cordova plugins add cordova-plugin-androidx-adapter
