### ISSUE TITLE
[question] which App-ID to use during setup?

### ISSUE THREAD

**Issue by znegva** [admob-plus/admob-plus#14]
Hi.

When creating an App in Google AdMob the very first thing to select is the Platform  - is your App for Android or iOS.

Since my App is distributed on both platforms I created two Apps within AdMob with the same name, but for the two different platforms. So i got two different __App-IDs__.

Which one should be used during setup of the plugin?  
Regarding to [the setup instruction of the admob-free-plugin](https://github.com/ratson/cordova-plugin-admob-free#installation) the App-ID is only needed for the `AndroidManifest.xml`, so I will use/try the Android-App-ID...

Is this the correct approach?

**Comment by ratson** [comment]
The latest version accept 2 ids: `APP_ID_ANDROID` and `APP_ID_IOS`
