### ISSUE TITLE
Android source not copied on install

### ISSUE THREAD

**Issue by ReallySmallSoftware** [admob-plus/admob-plus#144]
### Is this a bug report?

Yes

### Environment

Android

### Steps to Reproduce

Installing the cordova-consent plugin as per instructions

### Expected Behavior

The plugin installs

### Actual Behavior

The Java source file is not being copied. I think the source-file directive in plugin.xml is in the wrong place.

**Comment by steosoft** [comment]
I have the same problem.
After copying file Consent.java from 
/plugins/cordova-plugin-consent/src/android
to
/platforms/android/app/src/main/java/cordova/plugin/consent/
plugin starts working.
Before doing that it shows in logs that can't find Consent java class

**Comment by FlorentMasson** [comment]
+1, I have the same issue.
I'm not even sure the plugin ever worked...

**Comment by rastafan** [comment]
I can confirm this behaviour.
If used without copying Consent.java in the right directory, calls simply never return.
After copying the file as described by @steosoft it starts working.

**Comment by rastafan** [comment]
I think the problem may be in plugin.xml for the consent package.
I tried to fix it but cound not find a way to test it.
You can find the edit here: https://github.com/rastafan/admob-plus/commit/33327310446d49160ecc2a7e7d8d2145bd630985
If anyone can test it and confirm it works i can make a pull request.

**Comment by AndreNeves97** [comment]
@rastafan I think that your solution is correct. In the `plugin.xml` file of `admob` package, the `<source-file>` tag is inside `  <platform name="android">` tag, not inside `</config-file>`

Thank's for your solution. I think that you can make a pull request.

**Comment by rastafan** [comment]
Pull request #180 has been merged, so i think this issue should be closed.
