### ISSUE TITLE
please full html js instructions 

### ISSUE THREAD

**Issue by thunderhurt** [admob-plus/admob-plus#150]
hi there , i am new in this world , first of all thank you for making this plugin , my issue :

i am a front end developer , and i do not understand java script that much , anyway , i am really trying my best and i kept reading the installation informations since 3 days and trying to make it work .

i installed plugin successfully but i cannot make codes work , please give us a full documentation about how to install the plugin from scratch , like where to insert codes ,  where we need to edit , please record some videos if possible and upload to youtube too , for me as a starter it is really hard to make it work 

all what i need is making some bottom banners and Interstitial Ad , please help me and be sure that i will not forget to donate , thank you so much again and forgive me because i am a starter , best regards , waiting for your help

**Comment by Samipp1** [comment]
Same here mate, did you get it working?

**Comment by thunderhurt** [comment]
yes i did it , but i still want them to explain more , any way , all whta you need to is to replace the code that was given in instructions with the code in the jave script , and note : in the json file youe need to change the google play version , do not orgot to use your app id and banners id from your admob account , let me know if you have any other issues

**Comment by darchy77** [comment]
I'd apreciate if somebody could explain how to use it, step by step. I've got an app made with visual studio 2017 (it is a simple html/js website), and I really don't understand how or where I must to put de code. I've tried a lot of times with differents placements, but it seems I'm doing wrong :(
