### ISSUE TITLE
does not build on pg build for ios

### ISSUE THREAD

**Issue by Risingson** [admob-plus/admob-plus#156]
"plugman-151 install --platform ios --project /project --plugin cordova-admob-plus@0.35.0 --nohooks=. --var ADMOB_APP_ID=ca-app-pub-6881224627796884~3615930521": Fetching plugin "cordova-admob-plus@0.35.0" via npm
Installing "cordova-admob-plus" at "0.0.0" for ios
Fetching plugin "cordova-plugin-add-swift-support@^2.0.2" via npm
Installing "cordova-plugin-add-swift-support" at "2.0.2" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1

**Comment by juxfr** [comment]
I also got the same problem.
Anyone for fixing it quickly?

**Comment by Risingson** [comment]
https://github.com/admob-plus/admob-plus/issues/137

**Comment by Risingson** [comment]
I moved the plugin to the top of plugins in config.xml and **-without any code changes- do sometimes** get past this error. but then other errors occur. They are different every time. Did not do a list of them but copied one:


_/project/Pods/GoogleUtilities/GoogleUtilities/Network/GULNetwork.m:15:9: fatal error: 'GoogleUtilities/Network/Private/GULNetwork.h' file not found
#import "GoogleUtilities/Network/Private/GULNetwork.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/EE-gflsbjygttvpmwceezpnmiswapyy/Build/Intermediates.noindex/ArchiveIntermediates/EE/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleUtilities.build/Objects-normal/armv7/GULNetwork.o GoogleUtilities/GoogleUtilities/Network/GULNetwork.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)_

**Comment by Risingson** [comment]
@juxfr Did you find a way to get it built ?

**Comment by Risingson** [comment]
Switched to building locally.
