### ISSUE TITLE
banner overlap?

### ISSUE THREAD

**Issue by matrixreal** [admob-plus/admob-plus#157]
Hello,
how can i set banner  overlap to true?
thanks

**Comment by matrixreal** [comment]
any help guys?

**Comment by ano2dev** [comment]
file `AMSBanner.swift`  on `func positionBannerInSafeArea`

`if position == "top" { 
            constraints += [
                bannerView.topAnchor.constraint(equalTo: guide.topAnchor),
                self.plugin.webView.topAnchor.constraint(equalTo: guide.topAnchor), 
                self.plugin.webView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
            ]

        } else { 

            constraints += [
                bannerView.bottomAnchor.constraint(equalTo: guide.bottomAnchor),
                self.plugin.webView.topAnchor.constraint(equalTo: view.topAnchor),
                self.plugin.webView.bottomAnchor.constraint(equalTo: guide.bottomAnchor) 
            ]
        }`

**Comment by ano2dev** [comment]
In case of iOS you can edit file `AMSBanner.swift`  on `func positionBannerInSafeArea`
line 85  from `bannerView.bottomAnchor` to `guide.topAnchor`
line 92  from `bannerView.topAnchor` to `guide.bottomAnchor`

https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/ios/AMSBanner.swift

```swift
if position == "top" { 
     constraints += [
          bannerView.topAnchor.constraint(equalTo: guide.topAnchor),
          self.plugin.webView.topAnchor.constraint(equalTo: guide.topAnchor), //bannerView.bottomAnchor),
          self.plugin.webView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
     ]

} else { 

     constraints += [
          bannerView.bottomAnchor.constraint(equalTo: guide.bottomAnchor),
          self.plugin.webView.topAnchor.constraint(equalTo: view.topAnchor),
          self.plugin.webView.bottomAnchor.constraint(equalTo: guide.bottomAnchor)  // bannerView.topAnchor)
     ]
}
```

**Comment by ano2dev** [comment]
In case of Cordova iOS you can edit file `AMSBanner.swift`  on `func positionBannerInSafeArea`
line 85  from `bannerView.bottomAnchor` to `guide.topAnchor`
line 92  from `bannerView.topAnchor` to `guide.bottomAnchor`

https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/ios/AMSBanner.swift

```swift
if position == "top" { 
     constraints += [
          bannerView.topAnchor.constraint(equalTo: guide.topAnchor),
          self.plugin.webView.topAnchor.constraint(equalTo: guide.topAnchor), //bannerView.bottomAnchor),
          self.plugin.webView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
     ]

} else { 

     constraints += [
          bannerView.bottomAnchor.constraint(equalTo: guide.bottomAnchor),
          self.plugin.webView.topAnchor.constraint(equalTo: view.topAnchor),
          self.plugin.webView.bottomAnchor.constraint(equalTo: guide.bottomAnchor)  // bannerView.topAnchor)
     ]
}
```

**Comment by matrixreal** [comment]
> In case of Cordova iOS you can edit file `AMSBanner.swift` on `func positionBannerInSafeArea`
> line 85 from `bannerView.bottomAnchor` to `guide.topAnchor`
> line 92 from `bannerView.topAnchor` to `guide.bottomAnchor`
> 
> https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/ios/AMSBanner.swift
> 
> ```swift
> if position == "top" { 
>      constraints += [
>           bannerView.topAnchor.constraint(equalTo: guide.topAnchor),
>           self.plugin.webView.topAnchor.constraint(equalTo: guide.topAnchor), //bannerView.bottomAnchor),
>           self.plugin.webView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
>      ]
> 
> } else { 
> 
>      constraints += [
>           bannerView.bottomAnchor.constraint(equalTo: guide.bottomAnchor),
>           self.plugin.webView.topAnchor.constraint(equalTo: view.topAnchor),
>           self.plugin.webView.bottomAnchor.constraint(equalTo: guide.bottomAnchor)  // bannerView.topAnchor)
>      ]
> }
> ```

thanks a lot
what about android?
