### ISSUE TITLE
Is this plugin support adaptive banner ads?

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#158]
Is this plugin support adaptive banner ads? I think this won't, kindly add this feature too.

**Comment by Eonio** [comment]
No it does not support adaptive banner ads.

**Comment by adrianmedeiros** [comment]
Hi @Eonio and @ratson , do you know how can I implement that ( Adaptive Banner ) ? Or someone that can help me with that question ? ( I can pay for this help as a freelancer job ).

**Comment by Carlosps** [comment]
Hello everyone,

Is there any chance the adaptive banner could be implemented in this plugin?

They seem to be planning to deprecate smart banners as stated here [android migration](https://developers.google.com/admob/android/migration.)

> Smart banner ads are deprecated in favor of adaptive banner ads. Adaptive banners provide superior performance and more flexibility in setting ad width.

**Comment by RonnySchleicher** [comment]
Hello everyone,

when are adaptive banners supported? Is that planned for the near future?

I am currently using Adaptive Banners and have had very good experiences with them.

Now I'd like to go to admob-plus-cordova, but that's something that I really miss.

**Comment by IgorSavchenko90** [comment]
Hi, is there any progress on this issue?

**Comment by EYALIN** [comment]
@ratson there are few people here that are willing to pay. can you add this feature?
