### ISSUE TITLE
cordova_not_available

### ISSUE THREAD

**Issue by robcunha** [admob-plus/admob-plus#16]
when i try show banner, i get this error:  "Uncaugth (in promise): cordova_not_available

here is my code to show banner
`this.platform.ready().then(() => {
      this.admob.banner.show({
        id: "ca-app-pub-xxx"
      });
    });`

**Comment by Fearcoder** [comment]
Hi @robcunha,

Use the following commands: 

1: ionic cordova platform add browser
2: npm install
3: ionic cordova run browser

Hope this helps for you

**Comment by ratson** [comment]
@robcunha Is the suggestion from @Fearcoder works for you? The error is typically caused by not including `cordova.js` in your html.
