### ISSUE TITLE
Interstitial are not clickable

### ISSUE THREAD

**Issue by InstantLinkweb** [admob-plus/admob-plus#162]
interstitial can't be click or close (using the close icon) in both dev mode and production...
Any ideas ?
I removed all others plugins but still doesnt work
Thanks

**Comment by InstantLinkweb** [comment]
I found the issue, just in case it happen to you, it was because of this setting in config.xml
<preference name="KeepRunning" value="false"/>.

**Comment by mcfarljw** [comment]
I also had this issue and spent way too long trying to figure out how to fix it. I can confirm though that using the following Android preference fixed the issue: `<preference name="KeepRunning" value="true"/>`

**Comment by nathanael540** [comment]
It could help in the maintenance of the project issues and mark it as resolved.

**Comment by mcfarljw** [comment]
I think this should be documented somewhere, if it already isn't, before marking it as resolved. `KeepRunning` is a fairly common Cordova config and it's not trivial to debug if you set it to default.

**Comment by nathanael540** [comment]
> I think this should be documented somewhere, if it already isn't, before marking it as resolved. `KeepRunning` is a fairly common Cordova config and it's not trivial to debug if you set it to default.

In fact I think this is a matter of prior logic that the programmer should already have.

If your application does not continue to run, when the Admob SDK opens the browser, your application will be stopped without reservations.
Then there will be no loophole for registering the event.

I think that documenting this will be going down the level of the repository for not simple premises. Soon you will need to document the need to have an Admob account to use the plugin or even have to turn on your computer before installing.

**Comment by mcfarljw** [comment]
I don't agree. I don't think it's common knowledge that Admob is opening a browser in the background instead of a popup within the current browser instance. It's a small caveat that if mentioned in the docs could save a future headache. Knowing you need to have an Admob account to use an Admob plugin is way more trivial.
