### ISSUE TITLE
Error after importing to my module: "Object(...) is not a function"

### ISSUE THREAD

**Issue by Zerokk** [admob-plus/admob-plus#165]
I'm in an Ionic project and I tried using this library, with no good results after all. I just followed [this guide](https://admob-plus.github.io/docs/installation.html), installing the plugin with the given AdMob keys, added AdMob to my main module's providers, and...:

> TypeError: Object(...) is not a functionindex.js:33:15
>     Banner index.js:33
>     js index.js:52
>     Webpack 12

I tried to test it in the navigator, and maybe that's part of the problem, but the app needs to be able to be loaded and show ads both in the web version, and the android/ios version.

The error is thrown by simply executing this line after a platform.isReady():
`      this.admob.banner.show({id: 'test'});``

I also tried with the [Ionic Native plugin](https://ionicframework.com/docs/native/admob-plus/), and I don't know if it's related to yours, but I'm getting this other problem after importing it from its /ngx subfolder (maybe again because it's not a valid Android/iOS device?):

```
ERROR Error: "Uncaught (in promise): TypeError: plugin.constructor.getPluginRef is not a function
checkAvailability@http://localhost:8100/vendor.js:84987:40
callCordovaPlugin@http://localhost:8100/vendor.js:85080:46
wrapOtherPromise/<@http://localhost:8100/vendor.js:84914:45
tryNativePromise/<@http://localhost:8100/vendor.js:84856:25
(...)
```

So after these problems, I decided using this second library and try to compile for Android, so I can test whether the problem is happening because of testing at the web, or the plugin itself. Thing is, now I cannot build for Android after using this plugin. See the error log:

`BUILD FAILED in 7s
D:\Dev\bygymapp\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-measurement-api:17.0.0 -> com.google.android.gms:play-services-
  measurement-sdk-api@[17.0.0], but play-services-measurement-sdk-api version was 17.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-ads@19.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-gass@19.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-core@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-ads@16.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-api@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk-api@17.1.0
  -- Project 'app' depends onto com.google.android.gms:play-services-ads-lite@19.0.1
`

These are my dependencies:

"dependencies": {
    "@agm/core": "^1.1.0",
    "@agm/js-marker-clusterer": "^1.1.0",
    "@angular/common": "~8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "~7.2.15",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/pwa": "^0.803.19",
    "@angular/router": "~8.2.14",
    "@ionic-native/background-mode": "^5.16.0",
    "@ionic-native/core": "5.16.0",
    "@ionic-native/date-picker": "^5.16.0",
    "@ionic-native/firebase-x": "^5.16.0",
    "@ionic-native/geolocation": "^5.16.0",
    "@ionic-native/image-picker": "^5.16.0",
    "@ionic-native/splash-screen": "5.16.0",
    "@ionic-native/status-bar": "5.16.0",
    "@ionic-native/stripe": "^5.16.0",
    "@ionic/angular": "5.0.0",
    "@types/chart.js": "^2.9.0",
    "@types/googlemaps": "^3.38.0",
    "@types/parse": "^2.2.15",
    "chart.js": "^2.9.3",
    "cordova-admob-plus": "^0.36.0",
    "cordova-android": "^8.1.0",
    "cordova-clipboard": "^1.3.0",
    "cordova-plugin-androidx": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.0",
    "cordova-plugin-consent": "^0.16.1",
    "cordova-plugin-datepicker": "0.9.3",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-extension": "^1.5.4",
    "cordova-plugin-firebasex": "^7.0.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-image-picker": "^1.1.3",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "2.3.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-res": "^0.8.1",
    "core-js": "^2.5.0",
    "crypto-js": "^3.1.9-1",
    "ion-rangeslider": "^2.3.1",
    "ionic": "^5.4.16",
    "ionic-admob": "^0.19.9",
    "js-marker-clusterer": "^1.0.0",
    "moment": "^2.24.0",
    "ng2-charts": "^2.3.0",
    "ngx-qrcode2": "0.0.9",
    "parse": "^2.13.0",
    "phonegap-plugin-multidex": "^1.0.0",
    "recursive-readdir": "^2.2.2",
    "rxjs": "6.5.3",
    "rxjs-compat": "^6.5.3",
    "sharp": "^0.23.2",
    "whitelist": "^1.0.2",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.19",
    "@angular-devkit/build-angular": "^0.803.19",
    "@angular-devkit/core": "^8.3.19",
    "@angular-devkit/schematics": "^8.3.19",
    "@angular/cli": "^8.3.19",
    "@angular/compiler": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "^3.4.6",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.12.7",
    "codelyzer": "~5.2.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.13.0",
    "protractor": "^5.4.2",
    "ts-node": "~8.5.2",
    "tslint": "~5.20.1",
    "typescript": "^3.4.5"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-telerik-imagepicker": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-firebasex": {
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "true",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "true",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "true",
        "ANDROID_ICON_ACCENT": "#FF00FFFF",
        "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.2.1",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "20.0.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "19.0.3",
        "ANDROID_FIREBASE_PERF_VERSION": "19.0.1",
        "ANDROID_FIREBASE_AUTH_VERSION": "19.1.0",
        "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
        "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.1"
      },
      "cordova-clipboard": {},
      "cordova-admob-plus": {
        "APP_ID_ANDROID": "--hidden--",
        "APP_ID_IOS": "--hidden--",
        "PLAY_SERVICES_VERSION": "19.0.1"
      },
      "cordova-plugin-consent": {
        "CONSENT_SDK_VERSION": "+"
      }
    },
    "platforms": [
      "android"
    ]
  }

**Comment by Zerokk** [comment]
Any help regarding this issue?

I would add another question: is this plugin usable in web version, or does it always throw that "Object(...) is not a function" error?

**Comment by lalalalaluk** [comment]
you can follow this as temporary answer
[https://stackoverflow.com/questions/58977083/admob-plus-and-ionic-results-in-runtime-error-plugin-constructor-getpluginref-i](https://stackoverflow.com/questions/58977083/admob-plus-and-ionic-results-in-runtime-error-plugin-constructor-getpluginref-i)
