### ISSUE TITLE
Build Failure for iOS platform

### ISSUE THREAD

**Issue by kapchew** [admob-plus/admob-plus#166]
Hi,

I tested admob-plus with an empty cordova project, it builds successfully for Android platform, but when I am building for iOS, it shows error:

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /localpath/myapp/src-cordova/platforms/ios/myapp/Plugins/cordova-admob-plus/AMSBanner.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal i386 /localpath/myapp/src-
(2 failures)
xcodebuild: Command failed with exit code 65

Any advice?

**Comment by appit-online** [comment]
**Solution**

Change in AMSBanner.swift file the following code:

Before:

>  view.sendSubviewToBack(background)

After:
`view.sendSubview(toBack:background)`

**Comment by ganreader** [comment]
Error persists even after making changes in AMSBanner.swift.

**Comment by AaronOliver94** [comment]
Hey. I have come across the same error when compiling to iOS:

```
The following build commands failed:
        CompileSwift normal x86_64 /Users/user/Documents/dev/myApp/platforms/ios/MyApp/Plugins/cordova-admob-plus/AMSBanner.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
```

It has occurred since I upgraded cordova-ios from 5.1.1 to 6.0.0.

I have applied the code change mentioned by @appit-online, however this did not solve the problem. If anyone else has solved this issue I would be interested in their solution. 

Many thanks.

**Comment by Neutrify** [comment]
Just a follow up comment. The solution provided by @appit-online does in fact work. Just make sure you change the correct the file at:
`myApp/platforms/ios/MyApp/Plugins/cordova-admob-plus/AMSBanner.swift `
NOT:
`myApp/plugins/cordova-admob-plus/src/ios/AMSBanner.swift`

**Comment by jonworek** [comment]
There's an active PR containing this change that I confirmed will fix the issue https://github.com/admob-plus/admob-plus/pull/167

**Comment by mariusbolik** [comment]
I still get this error. Changing the swift file in the `/platforms/ios` directory doesn't work for me.
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/marius/Projekte/MyApp/App\ Source/myapp/platforms/ios/MyApp/Plugins/cordova-admob-plus/AMSBanner.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```

**Comment by mariusbolik** [comment]
I still get this error. Changing the swift file in the `/platforms/ios` directory doesn't work for me.
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/marius/Projekte/MyApp/App\ Source/myapp/platforms/ios/MyApp/Plugins/cordova-admob-plus/AMSBanner.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```
@ratson do you have any idea?

**Comment by gatelli** [comment]
also I edited line 66
rootview.sendSubview(toBack:background)
to
rootView.sendSubview(toBack:background)

**Comment by ratson** [comment]
See https://admob-plus.github.io/docs/cordova/faq#how-to-fix-sendsubviewtoback-has-been-renamed-to-sendsubviewtoback-error
