### ISSUE TITLE
Reward video load fails

### ISSUE THREAD

**Issue by bil-ash** [admob-plus/admob-plus#17]
The plugin(v 0.3.0) shows banner and interstitial ads but fails to load rewarded video ads.Could you please check if it works now on your setup(things might have changed over the past month). If it works, please share the versions of the play services ads framework and the ios pod in your setup.
Here is the link to the picture of the error object received on the reward_video_load_fail event-
https://drive.google.com/file/d/1L34-3HZsXvGgsaIm8lvWXdIEyYYyELTw/view?usp=drivesdk

**Comment by bil-ash** [comment]
Have you tried on android? If it works,could you specify which version of 'ads framework' are you using?

**Comment by znegva** [comment]
As defined in the plugin.xml always the newest Ads framework version is used and I did not chenged anything.
At the time of setting up the android-platform with the plugin this should have been:  `com.google.android.gms:play-services-ads:16.0.0`

**Comment by bil-ash** [comment]
I have also modified the plugin.xml to pin ads framework to v16.0 because the plugin dosen't copy the android application id to AndroidManifest.xml which is necessary for using ads-framework v17.0 . So might be there is some problem with my setup. Could you please specify which version of cordova-android(6.x.y,7.0.0,7.1.0 or 7.1.1) are you using?

**Comment by znegva** [comment]
```
cordova-android: 7.1.1
cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
Android SDK Tools : 26.1.1
```

after checking my build logs, I found that I am using `com.google.android.gms:play-services-ads:17.0.0` in fact - as mentioned I had to add the app-id to my AndroidManifest.xml by hand, see [here](https://github.com/admob-plus/admob-plus/issues/13#issuecomment-428963974)
