### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by MilkyWayGalaxyUser** [admob-plus/admob-plus#176]
its crashing on app start

ionic start basic settings blank

if i add plugin it crashes tried a lot of things nothing works
editing config file nope basically doesn't work, if works for you send me source code to test on my pc
thanks.

**Comment by matrixreal** [comment]
same here
any solutions ?

**Comment by MilkyWayGalaxyUser** [comment]
> same here
> any solutions ?

I gave up on Ionic and cordova plugins.
I have some legacy projects. but,
I suggest you to try flutter, community is way more active. 
And plugins actually work.

Here I broke head trying. I lost one week. Just to set up non working plugins. I literally tried everything.
So I found solution > **I rewrote app in flutter.**
Tried 4 adMob plugins and nothing.

android sdk is newer and newer, and these plugins are not updated at all. dinosaurs. damn.
just move asap from this framework.

cheers!
