### ISSUE TITLE
banner overlap on android ?

### ISSUE THREAD

**Issue by matrixreal** [admob-plus/admob-plus#177]
Hello guys,
any way to fix the banner overlap on android ?
when the banner is shown ... the content of my app is moved a little up
thanks

**Comment by faytekin** [comment]
+1
Same problem.

https://github.com/ratson/cordova-plugin-admob-free everything is normal in this package

**Comment by matrixreal** [comment]
can anyone help us and fix this?
thanks

**Comment by ollm** [comment]
You can use `offset: 0` to overlap, I used it on android and it works fine.

``` javascript
new admob.BannerAd({
  adUnitId: 'ca-app-pub-xxx/yyy',
  offset: 0,  // overlap with content
})
```

https://github.com/admob-plus/admob-plus/blob/master/website/docs/cordova/ads/banner.md#offset
