### ISSUE TITLE
Cannot install plugin via GIT

### ISSUE THREAD

**Issue by Pl0414141** [admob-plus/admob-plus#178]
Trying to install the plugin with 'master' branch via

cordova plugin add https://github.com/admob-plus/admob-plus.git

is not working

Please, can you upload a new release with the latest changes of **cordova-admob-plus**?.

Thank you very much

**Comment by mcfarljw** [comment]
This is probably because the `plugin.xml` file is not located in the root directory of the repository. It is located here: https://github.com/admob-plus/admob-plus/tree/master/packages/cordova
