### ISSUE TITLE
Build IOS Archive Failed

### ISSUE THREAD

**Issue by lucaele** [admob-plus/admob-plus#183]
Hi all,
on build ios app there are some error (listed below).

Cordova: 9.0.0
platform: ios 5.1.1

On config.xml:
...
<preference name="deployment-target" value="9.0" />
<preference name="UseSwiftLanguageVersion" value="5" />
...

How fix it?
Thanks

-cordova-admob-plus/AMSRewardVideo.swift:2:27: error: use of undeclared type 'GADRewardBasedVideoAd'
    var rewardBasedVideo: GADRewardBasedVideoAd?
                          ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:13:24: error: use of undeclared type 'GADRequest'
    func load(request: GADRequest) {
                       ^~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:28:51: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didRewardUserWith reward: GADAdReward) {
                                                  ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:28:100: error: use of undeclared type 'GADAdReward'
    func rewardBasedVideoAd(_ rewardBasedVideoAd: GADRewardBasedVideoAd, didRewardUserWith reward: GADAdReward) {
                                                                                                   ^~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:32:61: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdDidReceive(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                            ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:36:58: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdDidOpen(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                         ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:40:59: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdDidClose(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                          ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:44:66: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdDidStartPlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                 ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:48:69: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdDidCompletePlaying(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                    ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:52:71: error: use of undeclared type 'GADRewardBasedVideoAd'
    func rewardBasedVideoAdWillLeaveApplication(_ rewardBasedVideoAd: GADRewardBasedVideoAd) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:1:34: error: use of undeclared type 'GADRewardBasedVideoAdDelegate'
class AMSRewardVideo: AMSAdBase, GADRewardBasedVideoAdDelegate {
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:9:28: error: use of unresolved identifier 'GADRewardBasedVideoAd'
        rewardBasedVideo = GADRewardBasedVideoAd.sharedInstance()
                           ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSRewardVideo.swift:14:28: error: use of unresolved identifier 'GADRewardBasedVideoAd'
        rewardBasedVideo = GADRewardBasedVideoAd.sharedInstance()
                           ^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:1:2: error: @objc attribute used without importing module 'Foundation'
@objc(AMSPlugin)
~^~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:27:6: error: @objc attribute used without importing module 'Foundation'
    @objc(ready:)
    ~^~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:38:6: error: @objc attribute used without importing module 'Foundation'
    @objc(set_app_muted:)
    ~^~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:52:6: error: @objc attribute used without importing module 'Foundation'
    @objc(set_app_volume:)
    ~^~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:66:6: error: @objc attribute used without importing module 'Foundation'
    @objc(banner_show:)
    ~^~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:88:6: error: @objc attribute used without importing module 'Foundation'
    @objc(banner_hide:)
    ~^~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:104:6: error: @objc attribute used without importing module 'Foundation'
    @objc(interstitial_is_loaded:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:118:6: error: @objc attribute used without importing module 'Foundation'
    @objc(interstitial_load:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:138:6: error: @objc attribute used without importing module 'Foundation'
    @objc(interstitial_show:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:154:6: error: @objc attribute used without importing module 'Foundation'
    @objc(reward_video_is_ready:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:168:6: error: @objc attribute used without importing module 'Foundation'
    @objc(reward_video_load:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~
-cordova-admob-plus/AMSPlugin.swift:188:6: error: @objc attribute used without importing module 'Foundation'
    @objc(reward_video_show:)
    ~^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by andreyavram** [comment]
Same error here. Any solution to this? Seems the same error as here https://github.com/admob-plus/admob-plus/issues/132

**Comment by tadeukaiba** [comment]
Same error here

**Comment by s3ppo** [comment]
i have the same issue.. any news on this ?

**Comment by jmelvin** [comment]
Starting to evaluate this plugin as an alternative to admobpro.  I am able to build successfully on Mac OS X with the following platform...

```
$ cordova platform ls
Installed platforms:
  ios 6.1.1
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

$ cordova plugin ls
cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-ats-rules 1.0.0 "App Transport Security Rules"
cordova-plugin-camera 5.0.1 "Camera"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.5 "Launch Navigator"
```

I did have to set the Swift version to 5.3 in config.xml as the installation instructions say.

**Comment by vietnux** [comment]
i same

`'GADRewardBasedVideoAd' is deprecated: Use GADRewardedAd instead. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-rewarded-migration. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/admanager-ios-rewarded-migration.`

**Comment by sprengerst** [comment]
> Starting to evaluate this plugin as an alternative to admobpro. I am able to build successfully on Mac OS X with the following platform...
> 
> ```
> $ cordova platform ls
> Installed platforms:
>   ios 6.1.1
> Available platforms: 
>   android ^9.0.0
>   browser ^6.0.0
>   electron ^1.0.0
>   osx ^6.0.0
> 
> $ cordova plugin ls
> cordova-admob-plus 0.0.0 "@admob-plus/cordova"
> cordova-plugin-actionsheet 2.3.3 "ActionSheet"
> cordova-plugin-ats-rules 1.0.0 "App Transport Security Rules"
> cordova-plugin-camera 5.0.1 "Camera"
> cordova-plugin-contacts 3.0.1 "Contacts"
> cordova-plugin-device 2.0.3 "Device"
> cordova-plugin-dialogs 2.0.2 "Notification"
> cordova-plugin-file 6.0.2 "File"
> cordova-plugin-geolocation 4.0.2 "Geolocation"
> cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
> cordova-plugin-media-capture 3.0.3 "Capture"
> cordova-plugin-network-information 2.0.2 "Network Information"
> cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova.plugins.diagnostic 6.0.2 "Diagnostic"
> phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
> uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.5 "Launch Navigator"
> ```
> 
> I did have to set the Swift version to 5.3 in config.xml as the installation instructions say.



Hi, could you please attach your config.xml?

**Comment by jmelvin** [comment]
@sprengerst and @vietnux  Here is our config.xml.  We are able to build and submit to Apple successfully.  We only use banner and interstitials for now.  Native and reward ads will come later.  Make sure to choose <proj>.xcworkspace and not <proj>.xcodeproj when importing/building with Xcode.

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.tramplezone.sizzlescene" version="6.1.0" ios-CFBundleVersion="0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>SizzleScene</name>
    <preference name="DisallowOverscroll" value="true" />
    <preference name="FadeSplashScreenDuration" value="800" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashScreen" value="screen" />
    <description>
        Track the Herd! Find and report crowded places worldwide. Why wait in line unless you want to?  Find where it is busy before you go. Be smart. Use SizzleScene!
    </description>
    <author email="support@tramplezone.com" href="http://tramplezone.com/sizzlescene/index.html">
        SizzleScene Development Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-navigation href="about:*" />
    <access origin="geo:*" launch-external="yes" />
    <access origin="tel:*" launch-external="yes" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <config-file parent="NSBluetoothAlwaysUsageDescription" target="*-Info.plist">
            <string>Improve location accuracy when finding nearby services</string>
        </config-file>
        <config-file parent="NSPhotoLibraryAddUsageDescription" target="*-Info.plist">
            <string>Include photos or videos with ratings</string>
        </config-file>
        <config-file parent="NSPhotoLibraryUsageDescription" target="*-Info.plist">
            <string>Include photos or videos with ratings</string>
        </config-file>
        <config-file parent="NSMicrophoneUsageDescription" target="*-Info.plist">
            <string>Include audio tracks with ratings</string>
        </config-file>
        <config-file parent="NSCameraUsageDescription" target="*-Info.plist">
            <string>Include photos or videos with ratings</string>
        </config-file>
        <config-file parent="NSContactsUsageDescription" target="*-Info.plist">
            <string>Allow users to select friends from their contacts list</string>
        </config-file>
        <splash src="res/ios/splashscreens/Default@2x~ipad~comany.png" width="1278" height="2732" />
        <splash src="res/ios/splashscreens/Default@2x~ipad~anyany.png" width="2732" height="2732" />
        <splash src="res/ios/splashscreens/Default@3x~iphone~comany.png" width="1242" height="2208" />
        <splash src="res/ios/splashscreens/Default@3x~iphone~anycom.png" width="2208" height="1242" />
        <splash src="res/ios/splashscreens/Default@3x~iphone~anyany.png" width="2208" height="2208" />
        <splash src="res/ios/splashscreens/Default@2x~iphone~comcom.png" width="1334" height="750" />
        <splash src="res/ios/splashscreens/Default@2x~iphone~comany.png" width="750" height="1334" />
        <splash src="res/ios/splashscreens/Default@2x~iphone~anyany.png" width="1334" height="1334" />
        <splash src="res/ios/splashscreens/Default-667h.png" width="375" height="667" />
        <splash src="res/ios/splashscreens/Default-667h@2x.png" width="750" height="1334" />
        <splash src="res/ios/splashscreens/Default-736h.png" width="414" height="736" />
        <splash src="res/ios/splashscreens/Default-736h@3x.png" width="1242" height="2208" />
        <splash src="res/ios/splashscreens/Default-812h.png" width="375" height="812" />
        <splash src="res/ios/splashscreens/Default-812h@3x.png" width="1125" height="2436" />
        <splash src="res/ios/splashscreens/Default-Landscape-568h.png" width="568" height="319" />
        <splash src="res/ios/splashscreens/Default-Landscape-568h@2x.png" width="1136" height="639" />
        <splash src="res/ios/splashscreens/Default-Landscape-667h.png" width="667" height="375" />
        <splash src="res/ios/splashscreens/Default-Landscape-667h@2x.png" width="1334" height="750" />
        <splash src="res/ios/splashscreens/Default-Landscape-736h.png" width="736" height="414" />
        <splash src="res/ios/splashscreens/Default-Landscape-736h@3x.png" width="2208" height="1242" />
        <splash src="res/ios/splashscreens/Default-Landscape-812h.png" width="812" height="375" />
        <splash src="res/ios/splashscreens/Default-Landscape-812h@3x.png" width="2436" height="1125" />
        <icon src="res/ios/icons/MarketingIcon.png" width="1024" height="1024" />
        <icon src="res/ios/icons/icon@2x.png" width="114" height="114" />
        <icon src="res/ios/icons/icon.png" width="57" height="57" />
        <icon src="res/ios/icons/icon-40.png" width="40" height="40" />
        <icon src="res/ios/icons/icon-40@2x.png" width="80" height="80" />
        <icon src="res/ios/icons/icon-50.png" width="50" height="50" />
        <icon src="res/ios/icons/icon-50@2x.png" width="100" height="100" />
        <icon src="res/ios/icons/icon-60.png" width="60" height="60" />
        <icon src="res/ios/icons/icon-60@2x.png" width="120" height="120" />
        <icon src="res/ios/icons/icon-60@3x.png" width="180" height="180" />
        <icon src="res/ios/icons/icon-72.png" width="72" height="72" />
        <icon src="res/ios/icons/icon-72@2x.png" width="144" height="144" />
        <icon src="res/ios/icons/icon-76.png" width="76" height="76" />
        <icon src="res/ios/icons/icon-76@2x.png" width="152" height="152" />
        <icon src="res/ios/icons/icon-83.5@2x.png" width="167" height="167" />
        <icon src="res/ios/icons/icon-Small.png" width="29" height="29" />
        <icon src="res/ios/icons/icon-Small@2x.png" width="58" height="58" />
        <icon src="res/ios/icons/icon-Small@3x.png" width="87" height="87" />
        <icon src="res/ios/icons/icon-Small-40.png" width="40" height="40" />
        <icon src="res/ios/icons/icon-Small-40@2x.png" width="80" height="80" />
        <icon src="res/ios/icons/icon-Small-40@3x.png" width="120" height="120" />
        <icon src="res/ios/icons/icon-Small-50.png" width="50" height="50" />
        <icon src="res/ios/icons/icon-Small-50@2x.png" width="100" height="100" />
        <preference name="SwiftVersion" value="5.3" />
        <preference name="orientation" value="all" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>
```

**Comment by vietnux** [comment]
> 
> 
> @sprengerst and @vietnux Here is our config.xml. We are able to build and submit to Apple successfully. We only use banner and interstitials for now. Native and reward ads will come later. Make sure to choose .xcworkspace and not .xcodeproj when importing/building with Xcode.
> 
> ```
> <?xml version='1.0' encoding='utf-8'?>
> <widget id="com.tramplezone.sizzlescene" version="6.1.0" ios-CFBundleVersion="0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
>     <name>SizzleScene</name>
>     <preference name="DisallowOverscroll" value="true" />
>     <preference name="FadeSplashScreenDuration" value="800" />
>     <preference name="FadeSplashScreen" value="true" />
>     <preference name="AutoHideSplashScreen" value="false" />
>     <preference name="SplashScreen" value="screen" />
>     <description>
>         Track the Herd! Find and report crowded places worldwide. Why wait in line unless you want to?  Find where it is busy before you go. Be smart. Use SizzleScene!
>     </description>
>     <author email="support@tramplezone.com" href="http://tramplezone.com/sizzlescene/index.html">
>         SizzleScene Development Team
>     </author>
>     <content src="index.html" />
>     <access origin="*" />
>     <allow-navigation href="about:*" />
>     <access origin="geo:*" launch-external="yes" />
>     <access origin="tel:*" launch-external="yes" />
>     <allow-intent href="http://*/*" />
>     <allow-intent href="https://*/*" />
>     <allow-intent href="tel:*" />
>     <allow-intent href="sms:*" />
>     <allow-intent href="mailto:*" />
>     <allow-intent href="geo:*" />
>     <platform name="android">
>         <allow-intent href="market:*" />
>     </platform>
>     <platform name="ios">
>         <config-file parent="NSBluetoothAlwaysUsageDescription" target="*-Info.plist">
>             <string>Improve location accuracy when finding nearby services</string>
>         </config-file>
>         <config-file parent="NSPhotoLibraryAddUsageDescription" target="*-Info.plist">
>             <string>Include photos or videos with ratings</string>
>         </config-file>
>         <config-file parent="NSPhotoLibraryUsageDescription" target="*-Info.plist">
>             <string>Include photos or videos with ratings</string>
>         </config-file>
>         <config-file parent="NSMicrophoneUsageDescription" target="*-Info.plist">
>             <string>Include audio tracks with ratings</string>
>         </config-file>
>         <config-file parent="NSCameraUsageDescription" target="*-Info.plist">
>             <string>Include photos or videos with ratings</string>
>         </config-file>
>         <config-file parent="NSContactsUsageDescription" target="*-Info.plist">
>             <string>Allow users to select friends from their contacts list</string>
>         </config-file>
>         <splash src="res/ios/splashscreens/Default@2x~ipad~comany.png" width="1278" height="2732" />
>         <splash src="res/ios/splashscreens/Default@2x~ipad~anyany.png" width="2732" height="2732" />
>         <splash src="res/ios/splashscreens/Default@3x~iphone~comany.png" width="1242" height="2208" />
>         <splash src="res/ios/splashscreens/Default@3x~iphone~anycom.png" width="2208" height="1242" />
>         <splash src="res/ios/splashscreens/Default@3x~iphone~anyany.png" width="2208" height="2208" />
>         <splash src="res/ios/splashscreens/Default@2x~iphone~comcom.png" width="1334" height="750" />
>         <splash src="res/ios/splashscreens/Default@2x~iphone~comany.png" width="750" height="1334" />
>         <splash src="res/ios/splashscreens/Default@2x~iphone~anyany.png" width="1334" height="1334" />
>         <splash src="res/ios/splashscreens/Default-667h.png" width="375" height="667" />
>         <splash src="res/ios/splashscreens/Default-667h@2x.png" width="750" height="1334" />
>         <splash src="res/ios/splashscreens/Default-736h.png" width="414" height="736" />
>         <splash src="res/ios/splashscreens/Default-736h@3x.png" width="1242" height="2208" />
>         <splash src="res/ios/splashscreens/Default-812h.png" width="375" height="812" />
>         <splash src="res/ios/splashscreens/Default-812h@3x.png" width="1125" height="2436" />
>         <splash src="res/ios/splashscreens/Default-Landscape-568h.png" width="568" height="319" />
>         <splash src="res/ios/splashscreens/Default-Landscape-568h@2x.png" width="1136" height="639" />
>         <splash src="res/ios/splashscreens/Default-Landscape-667h.png" width="667" height="375" />
>         <splash src="res/ios/splashscreens/Default-Landscape-667h@2x.png" width="1334" height="750" />
>         <splash src="res/ios/splashscreens/Default-Landscape-736h.png" width="736" height="414" />
>         <splash src="res/ios/splashscreens/Default-Landscape-736h@3x.png" width="2208" height="1242" />
>         <splash src="res/ios/splashscreens/Default-Landscape-812h.png" width="812" height="375" />
>         <splash src="res/ios/splashscreens/Default-Landscape-812h@3x.png" width="2436" height="1125" />
>         <icon src="res/ios/icons/MarketingIcon.png" width="1024" height="1024" />
>         <icon src="res/ios/icons/icon@2x.png" width="114" height="114" />
>         <icon src="res/ios/icons/icon.png" width="57" height="57" />
>         <icon src="res/ios/icons/icon-40.png" width="40" height="40" />
>         <icon src="res/ios/icons/icon-40@2x.png" width="80" height="80" />
>         <icon src="res/ios/icons/icon-50.png" width="50" height="50" />
>         <icon src="res/ios/icons/icon-50@2x.png" width="100" height="100" />
>         <icon src="res/ios/icons/icon-60.png" width="60" height="60" />
>         <icon src="res/ios/icons/icon-60@2x.png" width="120" height="120" />
>         <icon src="res/ios/icons/icon-60@3x.png" width="180" height="180" />
>         <icon src="res/ios/icons/icon-72.png" width="72" height="72" />
>         <icon src="res/ios/icons/icon-72@2x.png" width="144" height="144" />
>         <icon src="res/ios/icons/icon-76.png" width="76" height="76" />
>         <icon src="res/ios/icons/icon-76@2x.png" width="152" height="152" />
>         <icon src="res/ios/icons/icon-83.5@2x.png" width="167" height="167" />
>         <icon src="res/ios/icons/icon-Small.png" width="29" height="29" />
>         <icon src="res/ios/icons/icon-Small@2x.png" width="58" height="58" />
>         <icon src="res/ios/icons/icon-Small@3x.png" width="87" height="87" />
>         <icon src="res/ios/icons/icon-Small-40.png" width="40" height="40" />
>         <icon src="res/ios/icons/icon-Small-40@2x.png" width="80" height="80" />
>         <icon src="res/ios/icons/icon-Small-40@3x.png" width="120" height="120" />
>         <icon src="res/ios/icons/icon-Small-50.png" width="50" height="50" />
>         <icon src="res/ios/icons/icon-Small-50@2x.png" width="100" height="100" />
>         <preference name="SwiftVersion" value="5.3" />
>         <preference name="orientation" value="all" />
>         <allow-intent href="itms:*" />
>         <allow-intent href="itms-apps:*" />
>     </platform>
> </widget>
> ```

oh. I`m thank you very much!
But. I fixed my mistakes long ago and its cause is plugin cordova-plugin-wkwebview-engine not support ios 6.1.1 => remove. Update Plugin cordova-plugin-inappbrowser to new version.
And belown is my config:
`<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="8" id="net.thegioilaptrinh.scanner" version="1.2.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Qrcode Scanner</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <icon src="www/logo.png" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    
    <allow-navigation href="*" />

    
    <allow-navigation href="http://*/*" />
    <allow-navigation href="https://*/*" />
    <allow-navigation href="data:*" />

    <preference name="DisallowOverscroll" value="true" />
    <preference name="SetFullscreen" value="true" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="ShowTitle" value="false" />
    <preference name="android-build-tool" value="gradle" />
    <preference name="Fullscreen" value="true" />
    <preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
    <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
    <preference name="AndroidPersistentFileLocation" value="Internal" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <preference name="AndroidXEnabled" value="true" />
    <platform name="android">
        <allow-intent href="market:*" />
        <config-file parent="/*" target="AndroidManifest.xml">
            <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxx~xxx" />
            <uses-permission android:name="com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY" />
        </config-file>
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference default="NO" name="KEEP_AVAUDIOSESSION_ALWAYS_ACTIVE" />
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="HideKeyboardFormAccessoryBar" value="false" />
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="SwiftVersion" value="5.3" />
        <config-file parent="/*" target="config.xml">
            <feature name="Media">
                <param name="ios-package" value="CDVSound" />
            </feature>
            <preference name="KeepAVAudioSessionAlwaysActive" value="$KEEP_AVAUDIOSESSION_ALWAYS_ACTIVE" />
        </config-file>
        <config-file parent="GADIsAdManagerApp" platform="ios" target="*-Info.plist">
            <true />
        </config-file>
        <config-file parent="GADApplicationIdentifier" target="*-Info.plist">
            <string>ca-app-pub-xxx~xxx</string>
        </config-file>
    </platform>
</widget>
`

And my app is runned very OK

- Android: https://play.google.com/store/apps/details?id=net.thegioilaptrinh.scanner
- IOS: https://a

pps.apple.com/us/app/qrcode-scanner-scan-create/id1508683075
