### ISSUE TITLE
Concent plugin not working on cordova

### ISSUE THREAD

**Issue by brunoalex** [admob-plus/admob-plus#185]
### Is this a bug report?

yes

### Environment

its the normal cordova env:

cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx
cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
cordova plugin add cordova-plugin-consent

(Write what you thought would happen.)
the form would show up

### Actual Behavior
cant get the form to open and adb logcat says :
08-25 15:35:29.576  4184  4430 I System.out: Error adding plugin cordova.plugin.consent.Consent.

inspector console.log says : show consent form and i can see consent plug on the source (inspctor) 

cant get the test device id from log cat ..dont show

**Comment by alexp25** [comment]
Same issue here: https://github.com/admob-plus/admob-plus/issues/184#issue-685477104

**Comment by NLueg** [comment]
I have the same problem ... how did you manage to implement the concent in your app @brunoalex?
