### ISSUE TITLE
is npa: 1 an option 

### ISSUE THREAD

**Issue by brunoalex** [admob-plus/admob-plus#187]
as i am unable to use the consent plugin i am trying to make my ads dialog ...but npa: 1 dosent seams to work... i was using 

admob.banner.show({id: {android: 'ca-app-pub-9718633180389415/5096728138', npa: '1' }})

any one have used this ? is npa 1 an option ?

**Comment by dcarvajal7** [comment]
> as i am unable to use the consent plugin i am trying to make my ads dialog ...but npa: 1 dosent seams to work... i was using
> 
> admob.banner.show({id: {android: 'ca-app-pub-9718633180389415/5096728138', npa: '1' }})
> 
> any one have used this ? is npa 1 an option ?

Hi! You should use it in the following way:

`admob.banner.show({id: {android: 'ca-app-pub-9718633180389415/5096728138'}}, npa: '1'})`

npa is not part of the id object, it must be outside.
