### ISSUE TITLE
Cannot show interstitial ad, even after signed

### ISSUE THREAD

**Issue by manel00** [admob-plus/admob-plus#189]
Ionic 4.X

I'm using this code, via cordova (the one i saw a lot of people speaking about it) and still not working, desesperating... don't know what else to do, it looks nothing of this works...

`declare var admob;  // Before @Component
`

```
    //admob.setDevMode(false)
    admob.interstitial.load({
      id: {
        // replace with your ad unit IDs
        android: 'ca-app-pub-38XX125961300XXXX/XXX',
        ios: 'test',
      },
    }).then(() => admob.interstitial.show())
```

**Comment by emi415064** [comment]
document.addEventListener('deviceready', () => {
  admob.interstitial.load({
    id: {
      // replace with your ad unit IDs
      android: 'ca-app-pub-xxx/yyy',
      ios: 'ca-app-pub-xxx/zzz',
    },
  }).then(() => admob.interstitial.show())
}, false)
