### ISSUE TITLE
Banner Ads Settings not working

### ISSUE THREAD

**Issue by faytekin** [admob-plus/admob-plus#190]
Hello,

@ratson I would like to thank you for this beautiful and useful open source project.

As indicated in the banner ads [here](https://admob-plus.github.io/docs/show-banner.html#methods) it doesn't work when I set it up.

Since the banner ads does not enter the webview (overlap), the places where the advertisement appeared remain black and a bad view appears. How can it be set to appear in Webview?

I used to use [cordova-plugin-admob-free](https://ratson.github.io/cordova-plugin-admob-free/variable/index.html#static-variable-banner) plugin so these settings can be done without any problems and banner ads appearing in the application's web view. I am using admob-plus because it is a newer plugin.

**Comment by ratson** [comment]
@faytekin Would you try https://github.com/admob-plus/admob-plus/tree/master/examples/basic to see if it is working for you. I am not sure about your problem, it would be helpful if you could share a repo with the issue for me to check.

**Comment by matrixreal** [comment]
it's overlapping true or false but it's not working in this plugin

**Comment by jptrainor** [comment]
I'm switching to admob-plus from cordova-admob-pro. I've also noticed that there is no overlap configuration option for banners in admob-plus.  My application code is all setup assuming overlay. Of course, I can adapt, but it's a nuisance.

**Comment by matrixreal** [comment]
any help guys ?
thanks in advance

**Comment by momikus** [comment]
Actually there is no difference functionally. However, overlap true/false feature would be great for a more native view when the banner is smaller than the screen width. I agree with @faytekin @matrixreal

**Comment by jptrainor** [comment]
There is a functional difference. In my case I all sorts of code set up to deal with an overlapping ad of varying size. It affects styling and positioning  because the size of the document is different depending on whether the ad overlays the window or not. I had to back away from a switch from admob-pro to admob-plus at this time because I can't tackle updating the rest of the app simply to make this switch. It also affects testing. (But I'd like to switch, and will return in the future when the time is better).

**Comment by matrixreal** [comment]
any news abot this guys?

**Comment by darkguy2008** [comment]
This project does not seem active. Does anybody know an alternative we can use? For iOS if possible?

**Comment by eliadAfeka** [comment]
@matrixreal are you having a problem with IOS only?

**Comment by matrixreal** [comment]
ios ok
android no overlap true false and it make the webview look bad

**Comment by ratson** [comment]
Duplicate to https://github.com/admob-plus/admob-plus/issues/54
