### ISSUE TITLE
Interstitial and RewardVideo Ads appears one time only.

### ISSUE THREAD

**Issue by hypesol** [admob-plus/admob-plus#198]
Hi
I am using this plugin banner ads are working fine but Interstitial and RewardVideo Ads appear only the first time, not after that. 
I am using this code in my function which call on the click event of button. "admob.interstitial.show

**Comment by darchy77** [comment]
you need to load it again after showing

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
**Just re-initialize the instance again after closing the first one.**

Once the first ad is closed, you have to load a new one (set it up in the queue) and then it can be shown again.

Same instance, different ad - it works perfectly (once you have a good rate-fill, which depends on the quality of your app).

**Comment by ratson** [comment]
Documentation has been updated to show how to load ads after display.
