### ISSUE TITLE
Implement Banner Ads

### ISSUE THREAD

**Issue by Screeze** [admob-plus/admob-plus#2]
2nd priority for me would be Banner ads.
I don't know if its possible due to admob or not, but I would like to have different banner ads loaded simultanously. E.g. cordova-admob-pro is not able to do so.

Use case:
Have a small banner ad on bottom of a game level. When switching to a pause screen I would have space for some bigger banner. Switching to another view there might be other space available. 
Additionally, for the statistics in admob it would be nice to also have a way to separate the incoms by different types of views so I would like to use different ad IDs for different views for which this feature would also be nice.
Otherwise loading banners will always take some time before I can show them. Additionally, with the other library I had issues when quickly switching between views with different banners, especially on iOS: There it happened that sometimes the wrong banner was shown then above the content as in this view a smaller banner should have been loaded, but that seemed to be a library bug. So maybe have an eye on doing this right from beginning please ;)

Thanks for starting this new project!

**Comment by ratson** [comment]
Duplicate to https://github.com/admob-plus/admob-plus/issues/3
