### ISSUE TITLE
Bug, cannot create release

### ISSUE THREAD

**Issue by VictorHugoDotVn** [admob-plus/admob-plus#20]
The issue as below when create the release (after add the admob plus plugin):

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/abc/.gradle/caches/transforms-1/files-1.1/play-services-base-11.0.4.aar/6c61d7814c0dd0361967e6ea4349b41f/jars/classes.jar

Please help to advise

**Comment by Fearcoder** [comment]
Can you try this command? Then run `cordova build`

`cordova plugin add cordova-android-play-services-gradle-release`

**Comment by VictorHugoDotVn** [comment]
Thanks bro a lot. It works now. 
Cheer.

**Comment by Fearcoder** [comment]
Glad I could help!
