### ISSUE TITLE
Plugin contains references to UIWebView which Apple rejects

### ISSUE THREAD

**Issue by jmelvin** [admob-plus/admob-plus#200]
Starting to evaluate this plugin as an alternative to cordova-plugin-admobpro.  Apple will reject any app with references to UIWebView.  All new apps must now use WKWebView exclusively.  Here are the references to UIWebView in this plugin and dependencies...

```
$ findit UIWebView
./platforms/ios/SizzleScene.xcarchive/Products/Applications/SizzleScene.app/SizzleScene
./platforms/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds
./platforms/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-armv7_arm64/GoogleMobileAds.framework/GoogleMobileAds
./platforms/ios/build/device/SizzleScene.app.dSYM/Contents/Resources/DWARF/SizzleScene
./platforms/ios/build/device/GoogleUtilities.framework.dSYM/Contents/Resources/DWARF/GoogleUtilities
./platforms/ios/build/sharedpch/Bridging-Header-swift_1ZA6QDFXL3HBP-clang_2D2FWECK3259W.pch
./platforms/ios/build/sharedpch/SizzleScene-Prefix-gttwvlguggdqdbencnauxptvmnfp/SizzleScene-Prefix.pch.data
./platforms/ios/build/sharedpch/SizzleScene-Prefix-gttwvlguggdqdbencnauxptvmnfp/SizzleScene-Prefix.pch.d
./platforms/ios/build/sharedpch/SizzleScene-Prefix-enujushvstribfgwjoarrltunmjk/SizzleScene-Prefix.pch.pch
./platforms/ios/build/sharedpch/SizzleScene-Prefix-enujushvstribfgwjoarrltunmjk/SizzleScene-Prefix.pch.data
./platforms/ios/build/sharedpch/SizzleScene-Prefix-enujushvstribfgwjoarrltunmjk/SizzleScene-Prefix.pch.d
./plugins/cordova-plugin-inappbrowser/RELEASENOTES.md
./plugins/cordova-plugin-whitelist/README.md
./plugins/cordova-plugin-camera/RELEASENOTES.md
./node_modules/cordova-ios/RELEASENOTES.md
./node_modules/cordova-plugin-inappbrowser/RELEASENOTES.md
./node_modules/cordova-plugin-whitelist/README.md
./node_modules/cordova-plugin-camera/RELEASENOTES.md
```

The READMEs aside, can these references be removed?  (I'm not sure all other references actually make it into the binary submitted and reviewed by Apple.)  I would hate to spend a great deal of time porting from admobpro to this plugin, only to find that Apple rejects it too.  Can you please advise?  Are there new apps that are using this plugin that have successfully been submitted to Apple?

For your reference, here is the admobpro references to UIWebView that cause a rejection by Apple...

```
./platforms/ios/SizzleScene.xcarchive/Products/Applications/SizzleScene.app/SizzleScene
./platforms/ios/SizzleScene/Plugins/cordova-admobsdk/GoogleMobileAds.framework/GoogleMobileAds
./platforms/ios/SizzleScene/Plugins/cordova-plugin-extension/libCordovaGenericAd.a
./platforms/ios/build/device/SizzleScene.app.dSYM/Contents/Resources/DWARF/SizzleScene
./platforms/ios/build/sharedpch/SizzleScene-Prefix-fvtixirimlntmndktgxhipkjobel/SizzleScene-Prefix.pch.pch
./platforms/ios/build/sharedpch/SizzleScene-Prefix-fvtixirimlntmndktgxhipkjobel/SizzleScene-Prefix.pch.data
./platforms/ios/build/sharedpch/SizzleScene-Prefix-fvtixirimlntmndktgxhipkjobel/SizzleScene-Prefix.pch.d
./platforms/ios/build/sharedpch/SizzleScene-Prefix-bahnraclpvwwcsegobuzkdjrlyty/SizzleScene-Prefix.pch.data
./platforms/ios/build/sharedpch/SizzleScene-Prefix-bahnraclpvwwcsegobuzkdjrlyty/SizzleScene-Prefix.pch.d
./plugins/cordova-plugin-inappbrowser/RELEASENOTES.md
./plugins/cordova-plugin-whitelist/README.md
./plugins/cordova-admobsdk/GoogleMobileAds.framework/GoogleMobileAds
./plugins/cordova-plugin-extension/src/ios/libCordovaGenericAd.a
./plugins/cordova-plugin-camera/RELEASENOTES.md
./node_modules/cordova-ios/RELEASENOTES.md
./node_modules/cordova-plugin-inappbrowser/RELEASENOTES.md
./node_modules/cordova-plugin-whitelist/README.md
./node_modules/cordova-admobsdk/GoogleMobileAds.framework/GoogleMobileAds
./node_modules/cordova-plugin-extension/src/ios/libCordovaGenericAd.a
./node_modules/cordova-plugin-camera/RELEASENOTES.md
```

**Comment by ratson** [comment]
@jmelvin https://admob-plus.github.io/docs/faq#how-to-use-wkwebview-instead-of-the-default-uiwebview-for-ios

**Comment by jmelvin** [comment]
@ratson Thanks for the link.  However, I'm using Cordova 10 (ios 6.1.1) which exclusively uses WKWebView and the separate engine plugin is not needed.  Has Apple accepted any **new** apps that use this plugin (admob-plus)?

$ cordova -version
10.0.0

$ cordova platform ls
Installed platforms:
  ios 6.1.1
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

$ cordova plugin ls
cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-ats-rules 1.0.0 "App Transport Security Rules"
cordova-plugin-camera 5.0.1 "Camera"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.5 "Launch Navigator"

Also, why is the admob-plus version 0.0.0?  Is that a bug perhaps?

**Comment by jmelvin** [comment]
I have done the port from AdMobPro to AdMobPlus and successfully uploaded a build to Apple.  The upload was no blocked on UIWebView references in GoogleMobileAds framework.  Closing this Issue as there is a path forward.
