### ISSUE TITLE
Ionic 5 (Vue) - cordova-admob-plus breaks building

### ISSUE THREAD

**Issue by pawel-marciniak** [admob-plus/admob-plus#204]
Hello,

I started a new app recently in Ionic 5 with Vue and wanted to test AdMob integration with this plugin, but when I install cordova-admob-plus:
```
npm i @admob-plus/ionic 
npm i cordova-admob-plus 
npx cap sync android 
```
and try to build application in Android Studio it tells me that build is successful but application don't start on device :/ There is some error in build process:
```
> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
Is this the problem? Or should I enter some more configuration somewhere?

**EDIT**

I see now that I have crash log in logcat:
```
2020-11-30 19:02:23.848 3696-3696/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 3696
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
```

but I have app ID configuration in my capacitor.config.json ("(...)xxx~yyy" is to hide my real id):

```

  "cordova": {
    "plugins": {
      "cordova-admob-plus": {
        "APP_ID_ANDROID": "ca-app-pub-xxx~yyy"
      }
    },
    "platforms": [
      "android"
    ]
  }
```

**EDIT 2**

I found out that if I add new item in `android/app/src/main/res/values/strings.xml` and use this new string in `android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml` like this:
```
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id"/>
```

instead of

```
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="$APP_ID_ANDROID"/>
```

App starting to work, but this AndroidManifest.xml file getting overwritten on every `ionic cap sync` run...

**Comment by darkguy2008** [comment]
This project does not seem active. Does anybody know an alternative we can use? For iOS if possible?
