### ISSUE TITLE
iOS 14 and SKAdNetwork/App Tracking Transparency authorization?

### ISSUE THREAD

**Issue by matrixreal** [admob-plus/admob-plus#207]
Hello,
Is this plugin ready for ios14 and the new SKAdNetwork/App Tracking Transparency authorization?
Thanks

**Comment by Be4t5** [comment]
Hi, I am also interested in this.

Checking the cordova-consent plugin I found this part of code:

![image](https://user-images.githubusercontent.com/11178416/101881001-1a74e880-3b94-11eb-95a1-9de7305a0fa8.png)

So I think that we could use this method to request the consent to the user before showing ads. But I don't know if this is enough to be fully compliant with the Apple new policy.

It will be great if someone could answer this or (better) if the plugin creator could provide a code example of how should we implement the tracking request flow to be fully compliant.

Thanks!

**Comment by gatelli** [comment]
+1

**Comment by darkguy2008** [comment]
This project does not seem active. Does anybody know an alternative we can use? For iOS if possible?

**Comment by matrixreal** [comment]
> We are aiming to release a fork with few updates for iOS 14 and Mediation in the few next months, I all goes ok, I'll share it below.
> 
> Regards.

thanks

**Comment by matrixreal** [comment]
> We are aiming to release a fork with few updates for iOS 14 and Mediation in the few next months, I all goes ok, I'll share it below.
> 
> Regards.

the great idea about mediation is to convert appodeal sdk to cordova plugin as it already has admob sdk as controller.

**Comment by ratson** [comment]
Close as it is fixed in latest release.
