### ISSUE TITLE
Related to this plugin "Add or update apps-ad.txt"?

### ISSUE THREAD

**Issue by sprengerst** [admob-plus/admob-plus#209]
Hi, at first thank you for your amazing work. You do a great job!!!

Second, yesterday I received the following message in the AdMob console.
Is this plugin related or needed?

![image](https://user-images.githubusercontent.com/6854862/102018466-b279fa00-3d6d-11eb-90df-3c5218ff935a.png)

**Comment by darkguy2008** [comment]
This project does not seem active. Does anybody know an alternative we can use? For iOS if possible?

**Comment by sprengerst** [comment]
Hi, use Tapdaq. Its far better.

**Comment by darkguy2008** [comment]
> Hi, use Tapdaq. Its far better.

Thanks, but I'm not looking for an AdMob alternative, but for an Ionic/Cordova plugin that'll work with AdMob as of date for iOS :)

**Comment by sprengerst** [comment]
Tapdaq does have a well maintained, easy to understand Cordova plugin. With them you can use any Ad Mediation service, they are somehow the man in the middle who decides which advertiser is delivering the ad, Admob, Facebook, Unity, ... but you can also select only a single advertiser and its free. We have it up and running for iOS and Android in one of our apps.

**Comment by darkguy2008** [comment]
> Tapdaq does have a well maintained, easy to understand Cordova plugin. With them you can use any Ad Mediation service, they are somehow the man in the middle who decides which advertiser is delivering the ad, Admob, Facebook, Unity, ... but you can also select only a single advertiser and its free. We have it up and running for iOS and Android in one of our apps.

Thanks for your explanation :) I did give it a look, and while it looks good, unfortunately it doesn't have an Ionic version, so I can't use it 😅 nice suggestion though, appreciate it. Also, Merry Christmas!

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> Hi, at first thank you for your amazing work. You do a great job!!!
> 
> Second, yesterday I received the following message in the AdMob console.
> Is this plugin related or needed?

It's not direct related to this plug-in.

But when you use this plug-in to show AdMob ads, you can better do what the console says;

---

`app-ads.txt` is kind of a certification file for all your mobile ads.

https://support.google.com/admob/answer/9363762?hl=en

`ads.txt` is somehow for protecting your default website ads.

https://support.google.com/adsense/answer/7532444?hl=en

---

So just read the Google manuals and place this file / those files in the root of your developer webserver.

The plug-in does work without those files, but your commercial workflow with those files will be much better.

**Comment by ratson** [comment]
Added to FAQ
https://admob-plus.github.io/docs/cordova/faq#how-to-handle-add-or-update-app-adstxt-in-admob-console
