### ISSUE TITLE
Where to add the Admob Ads ID

### ISSUE THREAD

**Issue by VictorHugoDotVn** [admob-plus/admob-plus#21]
Dear,
Please advise me the place to add the admob ads ID (ad banner/interstitial/Video Award), please.
I have an html5 page, and try to add admob.
I also have tried as the example file but the ads is not show.

Appreciate your help please.
- where to add the Admob ads ID exactly.

Thanks a lot.

**Comment by Fearcoder** [comment]
Are you working with Ionic?

**Comment by VictorHugoDotVn** [comment]
No bro, I am working in html5 game, which created by createjs.
Please advise me bro. Thanks

**Comment by Fearcoder** [comment]
Have you check the documentation? 

https://admob-plus.github.io/docs/show-interstitial.html

**Comment by VictorHugoDotVn** [comment]
Thanks bro.
I follow the documentation, Should I just change the ads ID unit only right?

ca-app-pub-123456789/123456789


Or anything else, please advise me. 
------------------
document.addEventListener('deviceready', () => {
  admob.interstitial.load({
    id: {
      // replace with your ad unit IDs
      android: 'ca-app-pub-xxx/yyy',
      ios: 'ca-app-pub-xxx/zzz',
    },
  }).then(() => admob.interstitial.show())
}, false)

**Comment by Fearcoder** [comment]
Yes sir it will be like this: 
`document.addEventListener('deviceready', () => {
admob.interstitial.load({
id: {
// replace with your ad unit IDs
android: 'ca-app-pub-123456789/123456789',
ios: 'ca-app-pub-123456789/123456789',
},
}).then(() => admob.interstitial.show())
}, false)`

**Comment by VictorHugoDotVn** [comment]
Hi bro,
I still cannot find the file to insert these ad unit IDs.
please help me which file should i modify it.
FYI, i am not using ionic.
Thanks bro

**Comment by Fearcoder** [comment]
You have a HTML page right? You have to put this code in the javascript file that is linked with the HTML file.

**Comment by naveed-ahmad** [comment]
@VictorHugoDotVn let me help you :) you can use following template I've used for my html5 games. Past this code snippet in a js file ( ads.js lets say ) and include it in html. 

```js
var admobid = {
  pub_id: "APP-ID",
  banner: "BANNER-ID",
  interstitial: "INTERSTITIAL-ID",
  rewardvideo: "REWARD-ID"
};

function prepareAdmobInterstitial ( autoShow ) {
  admob.interstitial.load ( {
    id: admobid.interstitial
  } );
}

function initAds () {
  document.addEventListener ( 'admob.interstitial.close', function () {
  
  } );

  document.addEventListener ( 'admob.interstitial.load_fail', function () {
   
  } );

  document.addEventListener ( 'admob.reward_video.load_fail', function () {
  } );

  document.addEventListener ( 'admob.reward_video.reward', function () {
    
  } );

  prepareAdmobInterstitial ();
}

function  showRewardVideo () {
  admob.rewardVideo.load ( {
    id: admobid.rewardvideo
  } ).then ( function () {
    return admob.rewardVideo.show ();
  } );
}

function  hideBanner () {
   admob.banner.hide();
}

function showBannerAd () {
  admob.banner.show ( {
    id: admobid.banner
  } );
}

function showInterstitialAd () {
  admob.interstitial.show ();
}

document.addEventListener ( "start_session", function ( evt ) {
    initAds ();
} );

document.addEventListener ( "show_banner", function ( evt ) {
   showBannerAd ();
} );

document.addEventListener ( "hide_banner", function ( evt ) {
  hideBanner ();
} );


document.addEventListener ( "show_interlevel_ad", function ( evt ) {
   showInterstitialAd ();
} );

```


I've removed game specific logic, like logging events on firebase and other stuff. 

On game loading screen you need to fire `session_start` event `cordova.fireDocumentEvent('session_start')` which will load ads. Then when you want to show interstitial ad, fire `show_interlevel_ad` event. 

Good luck.

**Comment by VictorHugoDotVn** [comment]
> On game loading screen you need to fire `session_start` event `cordova.fireDocumentEvent('session_start')` which will load ads. Then when you want to show interstitial ad, fire `show_interlevel_ad` event.
> 
> Its very bad idea to load ads on ondeviceready event imo.

Dear Bro,
Thanks Bro a lot.
Can you please help me a bit more detail on the steps in Cordova:

> On game loading screen you need to fire session_start event cordova.fireDocumentEvent('session_start') which will load ads. Then when you want to show interstitial ad, fire show_interlevel_ad event.

I am new with cordova, please help me ya bro. can you guide me a bit more detail, please.
Really appreciate your help and advice, please.

**Comment by riteshtajrajchavhan** [comment]
this thing is not working
