### ISSUE TITLE
Ads not shown unless setDevMode(true)

### ISSUE THREAD

**Issue by okwei2000** [admob-plus/admob-plus#212]
The banner or Interstitial are not displayed in Android unless the dev mode is set to true

`admob.setDevMode(true)`

**Comment by philippogol** [comment]
are you calling the methods in the correct order and syntax? test this on a fresh build with the plugin.

`
  admob.setDevMode(true);
  admob.interstitial.load({
        id: {
         android: 'ca-app-pub-***',
        },
      }).then(() => admob.interstitial.show())
`

**Comment by okwei2000** [comment]
I pushed my app into beta testing in playstore and everything works OK.. must have something to do with local testing.
