### ISSUE TITLE
Update for full compatibility with iOS 14

### ISSUE THREAD

**Issue by realn3rd** [admob-plus/admob-plus#213]
Is there a chance that there will be an update for this plugin to make it fully compatible with iOS 14.

Apple will soon require apps to ask if tracking can be enabled or not during updates.

If the plugin gets an appropriate update, I will also donate in the future.

**Comment by ratson** [comment]
@realn3rd `admob-plus-cordova` is using the latest SDK, please give it a try.

**Comment by ratson** [comment]
Close as it is fixed in latest release.
