### ISSUE TITLE
Need help with cordova-plugin-consent

### ISSUE THREAD

**Issue by cyclonmaster** [admob-plus/admob-plus#217]
### Is this a bug report?

No

I need help on how to use cordova-plugin-consent.

This is my code:
`async function showConsent(testDeviceId) {
    const publisherIds = ["pub-xxx"];

    await consent.addTestDevice(testDeviceId);
    await consent.setDebugGeography("EEA");
    console.log(await consent.checkConsent(publisherIds));

    const ok = await consent.isRequestLocationInEeaOrUnknown();
    if (!ok) {
        alert("please update testDeviceId from logcat");
    }

    const form = new consent.Form({
            privacyUrl: "https://policies.google.com/privacy",
            adFree: true,
            nonPersonalizedAds: true,
            personalizedAds: true,
        });
    await form.load();
    const result = await form.show();
    console.log("consentStatus", consentStatus);
    console.log("result", result);
    return result;
}

function admobshowBannerAd() {
    // NOTE: update the following to make it works
    const testDeviceId = "xxx";
    console.log("show consent form");
    showConsent(testDeviceId).then(async({
            consentStatus
        }) => {
        console.log("consentStatus", consentStatus);
        if (consentStatus === "PERSONALIZED") {
            await admob.banner.show({
                id: "test",
                testDevices: [testDeviceId],
            })
        } else {
            await admob.banner.show({
                id: "test",
                testDevices: [testDeviceId],
                npa: "1",
            })
        }
    }).catch(console.error);
}`

I follow the code example in the docs.
My questions is, I know that testDeviceId is from logcat. But in this code example, what does it use for?
Does it mean, it read every user device id, and use it to get user consent or not? And it is required in live app?
How do I get testDeviceId from my cordova app? 

I try using plugin cordova-plugin-device and call device.uuid, unfortunately, this is not testDeviceId value that I'm looking for.

Please help, how do I write and use this cordova-plugin-consent. Thank you.

**Comment by dkstraub** [comment]
I have the same problem and the same question.

The example is not clear.

Could you discover something?

**Comment by cyclonmaster** [comment]
Still not work here. Given is a test code. Looking for a sample live code.

Btw, even with the test code, it compile ok, except that consent not pop up anyway.

Looking at this line,
const ok = await consent.isRequestLocationInEeaOrUnknown();
I wonder if this code refer to use had to be located in Europe for it to trigger. If that is the case, how to test it out?

Hope somebody can help guide how to proceed.

**Comment by ratson** [comment]
Outdated issue, see https://admob-plus.github.io/docs/cordova/consent for latest API.
