### ISSUE TITLE
Errors in Xcode and live iOS device

### ISSUE THREAD

**Issue by bradical1379** [admob-plus/admob-plus#219]
When I attempt to install the app on my device through Xcode after I compile the app with `ionic cordova build ios` I see these messages on my Xcode console:

```
<Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-XXX~XXX
THREAD WARNING: ['AdMob'] took '83.675049' ms. Plugin should use a background thread.
Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"9ad73c39e153f4090995b0805ed4d50a" ];
THREAD WARNING: ['AdMob'] took '39.002930' ms. Plugin should use a background thread.
banner show success true
```
I am unsure if I need to run the -prod flag on my build in order for the ads to surface on a live device, and until then it assumes we are in dev? The console message about the App ID changed is strange, because it displays my actual publisher ID correctly. I am seeing hits in my admob dashboard, and it works when deploying to a simulator or on Android OS. 

Any thoughts with the plugin is running twice?

Based on a number of posts here, it appears that the Ionic wrapper for this plugin has some issues, so I have stripped out all of the Ionic wrappers and installed it through the vanilla cordova method, and invoke then declare the variable in my `app.component.ts`.

`declare var admob;
`
I've wrapped admob banner call in my `this.platform.ready()` function like this:

```
admob.banner.show({
    id: {
      ios: "ca-app-pub-XXX/XXX",
      android: "ca-app-pub-XXX/XXX"
    }
  }).then((res) => {
    console.log('banner show success ' + res);
  }).catch(err => {
    console.log('banner show failure ' + err);
  });
```
Any thoughts on other things I should be looking at to try and trouble shoot what's causing these errors and the ads to not appear?

**Comment by ratson** [comment]
Close as related to the old version.
