### ISSUE TITLE
Ads showed in development with emulator, but not in published apps listed in Google Play.

### ISSUE THREAD

**Issue by AlvinStefanus** [admob-plus/admob-plus#220]
I follow every step from:

https://admob-plus.github.io/docs/

and

https://admob-plus.github.io/docs/show-banner

The ad is shown fine within development environment with emulator. It was perfect. Then I publish my app to Google Play. The ad does not show at all. Not even an empty black space at the top of the screen.

------

Cordova version: 10.0.0
Installed plugins: only cordova-sqlite-storage

------

I installed:

cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
cordova plugin add cordova-plugin-consent

and added <preference name="AndroidXEnabled" value="true" /> to config.xml.

I am using banner ads btw.

Please help.

**Comment by AlvinStefanus** [comment]
does google app play store version should be updated with the latest play store version?

**Comment by CaturViriyananda** [comment]
it usually took 2 - 3 days after your release. try checking your admob console and play console for any notification.

**Comment by AlvinStefanus** [comment]
I got an error message: "isTrusted: false". What is this? How can I fix it?

**Comment by ratson** [comment]
@AlvinStefanus See https://admob-plus.github.io/docs/cordova/faq#what-does-istrusted-false-event-message-means
