### ISSUE TITLE
Not able to show admob ads

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#223]
While run the code after adding admob plugin, it show the following error.
Kindly help me.
```
/Users/merbinjoe/LearnHTML/platforms/ios/Learn HTML/Bridging-Header.h:29:9: note: in file included from /Users/merbinjoe/LearnHTML/platforms/ios/Learn HTML/Bridging-Header.h:29:
#import "AMSPlugin-Bridging-Header.h"
        ^
/Users/merbinjoe/LearnHTML/platforms/ios/Learn HTML/Plugins/admob-plus-cordova/AMSPlugin-Bridging-Header.h:2:9: error: 'GoogleMobileAds/GoogleMobileAds.h' file not found
#import <GoogleMobileAds/GoogleMobileAds.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/merbinjoe/Library/Developer/Xcode/DerivedData/Learn_HTML-byesqoxaqobftubfzgapsgfpjmyc/Build/Intermediates.noindex/PrecompiledHeaders/Bridging-Header-swift_2OI441CGMURNS-clang_2U3QCTS2L16WS.pch' for bridging header '/Users/merbinjoe/LearnHTML/platforms/ios/Learn HTML/Bridging-Header.h'
```

![screenshot-github com-2021 02 09-13_51_15](https://user-images.githubusercontent.com/3687184/107335692-3df9d800-6ade-11eb-8bcd-12f6401781b6.png)

**Comment by ratson** [comment]
@merbin2012 I cannot tell what goes wrong from just the error message, can you prepare a repo for me to check?

**Comment by merbin2012** [comment]
After one day research, I fixed it by adding the pod project into the my project. Should we do the same to all projects? I thought all the process will automatically update.

I don't know I did the right or not. But now the ads showing in my project.

**Comment by thomasmso** [comment]
You should move over to [AppLovin MAX](https://github.com/AppLovin/AppLovin-MAX-Cordova) instead, you'll get better support there.

**Comment by merbin2012** [comment]
> @merbin2012 - You should move over to [AppLovin MAX](https://github.com/AppLovin/AppLovin-MAX-Cordova) instead, you'll get better support there.

Span

**Comment by merbin2012** [comment]
> @merbin2012 - You should move over to [AppLovin MAX](https://github.com/AppLovin/AppLovin-MAX-Cordova) instead, you'll get better support there.

Spam

**Comment by ratson** [comment]
@merbin2012 If you install the plugin with cordova CLI, the project should setup automatically as the plugin has included the SDK pod as dependency.

**Comment by merbin2012** [comment]
Yes I am using cordova CLI only, also all the pod and its dependence added
automatically. But need to import the pod module manually, otherwise the
above error is shown.

**Comment by ratson** [comment]
@merbin2012 I have no idea how the error is occurred, would you provide steps how is it happened?

**Comment by gigafishapps** [comment]
Same issue here. This plugin is broken.

**Comment by ratson** [comment]
Close as not enough way to reproduce.
