### ISSUE TITLE
Cannot find module '@admob-plus/ionic/ngx' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ahunter135** [admob-plus/admob-plus#224]
### Is this a bug report?

Yes

### Environment

Cannot find module '@admob-plus/ionic/ngx' or its corresponding type declarations.

### Steps to Reproduce

(Write your steps here:)

1. Install the plugin as shown in the documentation
2. Try to import the file into ionic 5.4.16
3. See error

### Expected Behavior

The import would not throw an error

### Actual Behavior

Import throws an error. ngx folder exists, but only contains a package.json.
Started a new ionic project and followed the tutorial; same outcome.
Also installed the ionic-angular example; Shows the same outcome.

**Comment by ratson** [comment]
@ahunter135 Republished the package, please let me know if it works now.

**Comment by ratson** [comment]
Close as it is fixed in latest release.

**Comment by Pilonetto** [comment]
I tested it today with the ionic-angular example and got the same error.

**Comment by lsantaniello** [comment]
I have the same issue

@ionic-native/admob-plus version": "5.31.1"

Did you solde it?
