### ISSUE TITLE
The following build commands failed: CompileSwift normal x86_64 /Users/manel/Documents/ionic_projects/xstories/xstories/platforms/ios/XStories/Plugins/cordova-admob-plus/AMSRewardVideo.swift

### ISSUE THREAD

**Issue by manel00** [admob-plus/admob-plus#225]
### Is this a bug report?

YES

### Environment

(paste the output of the command here)

### Steps to Reproduce

ionic cordova build ios

### Expected Behavior

Compile without errors

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

```
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/manel/Documents/ionic_projects/xstories/xstories/platforms/ios/XStories/Plugins/cordova-admob-plus/AMSRewardVideo.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Cannot build on iOS

**Comment by Ricardo385** [comment]
Do you solved it? I have the same issue...

**Comment by manel00** [comment]
Hola Ricardo!

Tienes que cambiar esta parte: didReceiveRegistrationToken

tiene que quedarte asi: 

**didReceiveRegistrationToken:(NSString *)deviceToken**

;)

**Comment by Ricardo385** [comment]
> Hola Ricardo!
> 
> Tienes que cambiar esta parte: didReceiveRegistrationToken
> 
> tiene que quedarte asi:
> 
> didReceiveRegistrationToken:(NSString *)deviceToken
> 
> ;)

Gracias Manuel, pero donde lo debo cambiar?

**Comment by manel00** [comment]
Donde te sale el error? (Visual studio code? XCode?...)

**Comment by Ricardo385** [comment]
> Donde te sale el error? (Visual studio code? XCode?...)

Visual Studio, acompañado de 
Plugins/cordova-admob-plus/AMSRewardVideo.swift:6:28: error: cannot find 'GADRewardedAd' in scope
        rewardBasedVideo = GADRewardedAd(adUnitID: adUnitID)

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/cordova-admob-plus/AMSBanner.swift
        CompileSwift normal x86_64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/cordova-admob-plus/AMSInterstitial.swift
        CompileSwift normal x86_64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/cordova-admob-plus/AMSPlugin.swift
        CompileSwift normal x86_64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/cordova-admob-plus/AMSRewardVideo.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

**Comment by manel00** [comment]
Me puedes dar mas info por favor? mi LinkedIn es Manuel Mariscal... hablame por ahi que intentare ayudar

**Comment by Ricardo385** [comment]
> Me puedes dar mas info por favor? mi LinkedIn es Manuel Mariscal... hablame por ahi que intentare ayudar
> 
> Otra cosa... No tengo ese archivo yo (AMSRewardVideo.swift)... te recomiendo añadir esto en config.xml:
> 
> ```
>     <platform name="ios">
>         <preference name="deployment-target" value="11.0" />
>         <preference name="SwiftVersion" value="5.3" />
>         ......
> ```
> 
> Es para Android o iOS?

No te encontré en LinkedIn, pero gracias por tu ayuda, es para iOS, y si, ya tengo agregado eso en mi config.xml, estoy utilizando admob plus 0.42.0 iOS 6.2.2 y ionic 5

**Comment by Ricardo385** [comment]
My Ionic Info

Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : android 7.1.4, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v15.3.0 (/usr/local/bin/node)
   npm        : 7.0.14
   OS         : macOS Big Sur
   Xcode      : Xcode 12.4 Build version 12D4e

**Comment by manel00** [comment]
mandame un email, encontraras mi info en mi perfil de github ;)

**Comment by ratson** [comment]
@manel00 @Ricardo385 Please try with `admob-plus-cordova`, `cordova-admob-plus` is discontinued.

**Comment by Ricardo385** [comment]
> @manel00 @Ricardo385 Please try with `admob-plus-cordova`, `cordova-admob-plus` is discontinued.

Thank you ratson, i will try with `cordova-admob-plus` and for npm i will be `npm i admob-plus-cordova` right?

**Comment by ratson** [comment]
@Ricardo385 You may need to remove the plugin with `cordova plugin remove cordova-admob-plus`, please follow instructions in https://admob-plus.github.io/docs/ionic to install `admob-plus-cordova`.

**Comment by Ricardo385** [comment]
> @Ricardo385 You may need to remove the plugin with `cordova plugin remove cordova-admob-plus`, please follow instructions in https://admob-plus.github.io/docs/ionic to install `admob-plus-cordova`.

I followed the instructions but when i build for ios it's showing the same issue:

/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:2:21: error: cannot find type 'GADRewardedAd' in scope
    var rewardedAd: GADRewardedAd?
                    ^~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:16:57: error: cannot find type 'GADRequest' in scope
    func load(_ command: CDVInvokedUrlCommand, request: GADRequest) {
                                                        ^~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:47:38: error: cannot find type 'GADFullScreenPresentingAd' in scope
    func adDidRecordImpression(_ ad: GADFullScreenPresentingAd) {
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:51:19: error: cannot find type 'GADFullScreenPresentingAd' in scope
    func ad(_ ad: GADFullScreenPresentingAd, didFailToPresentFullScreenContentWithError error: Error) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:55:46: error: cannot find type 'GADFullScreenPresentingAd' in scope
    func adDidPresentFullScreenContent(_ ad: GADFullScreenPresentingAd) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:59:46: error: cannot find type 'GADFullScreenPresentingAd' in scope
    func adDidDismissFullScreenContent(_ ad: GADFullScreenPresentingAd) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:1:31: error: cannot find type 'GADFullScreenContentDelegate' in scope
class AMSRewarded: AMSAdBase, GADFullScreenContentDelegate {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:9:20: error: type of expression is ambiguous without more context
        rewardedAd = nil
        ~~~~~~~~~~~^~~~~
/Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift:17:9: error: cannot find 'GADRewardedAd' in scope
        GADRewardedAd.load(withAdUnitID: adUnitId, request: request, completionHandler: { ad, error in
        ^~~~~~~~~~~~~

** ARCHIVE FAILED **


The following build commands failed:
        CompileSwift normal arm64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSBanner.swift
        CompileSwift normal arm64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSInterstitial.swift
        CompileSwift normal arm64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSPlugin.swift
        CompileSwift normal arm64 /Users/ricardomadrid/Documents/lnp-app/lnphn-app/platforms/ios/LNFP/Plugins/admob-plus-cordova/AMSRewarded.swift
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.

**Comment by ratson** [comment]
Could you try
> Run pod repo update or cd platforms/ios && pod install --repo-update to ensure latest SDK is ready.

Or prepare the repo to show the error?

**Comment by Ricardo385** [comment]
> @Ricardo385 Could you try
> 
> > Run pod repo update or cd platforms/ios && pod install --repo-update to ensure latest SDK is ready.
> 
> Or prepare the repo to show the error?

Same error @ratson, tried all but no success results building for iOS.

**Comment by ratson** [comment]
@Ricardo385 The latest release updated to use SDK v8.1.0, see if it fixes your problem.

**Comment by Ricardo385** [comment]
> @Ricardo385 The latest release updated to use SDK v8.1.0, see if it fixes your problem.
> And your Cordova version is a bit old, which may be the cause.

Thank you @ratson it worked! But now, i only see a black display instead a real banner, i'm using the plugin with the following code:
async showBanner() {
    await this.admob.start();

    const banner = new this.admob.BannerAd({
      adUnitId: 'myiOSbannerId',
    });
    await banner.show();
  }

**Comment by ratson** [comment]
@Ricardo385 Do you still getting black screen from the latest release?
I use the same code for testing without problem.
If the problem persist, would create a repo for me to look into?

**Comment by Ricardo385** [comment]
> @Ricardo385 Do you still getting black screen from the latest release?
> I use the same code for testing without problem.
> If the problem persist, would you create a repo for me to look into?

Hi @ratson, thanks for your answer, the black screen disappeared until Google Admob allowed me to find my application in the App Store to connect with my account, I waited like 2 or 3 hours for the ads to start appearing in my application but the Request impressions haven't generated revenue on iOS when viewing video rewards and clicking ads, but on Android I'm already generating revenue.

**Comment by ratson** [comment]
@Ricardo385 Nice, the latest release emits event with reward, which you may find useful.
https://admob-plus.github.io/docs/cordova/ads/rewarded#admobrewardedreward
