### ISSUE TITLE
plugin not working for IOS 14, cordova.

### ISSUE THREAD

**Issue by hisoka-sama** [admob-plus/admob-plus#227]
I'm trying to use this plugin for iOS 14. When I add the plugin I get these warnings:

`[!] The 'TestAPP [Debug]' target overrides the 'LD_RUNPATH_SEARCH_PATHS' build setting defined in 'Pods/Target Support Files/Pods-TestAPP/Pods-TestAPP.debug.xcconfig'. This can lead to problems with the CocoaPods installation`

`[!] The 'TestAPP[Release]' target overrides the 'LD_RUNPATH_SEARCH_PATHS' build setting defined in 'Pods/Target Support Files/Pods-TestAPP/Pods-TestAPP.release.xcconfig'. This can lead to problems with the CocoaPods installation`

`Script file does't exist and will be skipped: /Users/mac/Desktop/cordova/testapp/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js`

`Adding admob-plus-cordova to package.json
Script file does't exist and will be skipped: /Users/mac/Desktop/cordova/testapp/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js`

And when I try to use the plugin I get this for interstitial ads:
`Unhandled Promise Rejection: Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target`

And banner ads, I get this:
`TypeError: banner.load is not a function. (In 'banner.load()', 'banner.load' is undefined)`

I must be doing something wrong. please help me.

Note: I was using cordova-plugin-admob-free without an issue but now I wanted to update for tracking transpancy. Tried using cordova-plugin-admob-tomitank but for some reason, no ads appeared when tracking was disabled. So I wanted to test this plugin and I ran into these issues.

**Comment by ratson** [comment]
Please try out `admob-plus-cordova@1.0.0-alpha.9` see if it fixes the issues.

**Comment by kosbar** [comment]
> Please try out `admob-plus-cordova@1.0.0-alpha.10` see if it fixes the issues.

get error on 'plugin add' stage:

```
cordova "plugin" "add" "admob-plus-cordova@1.0.0-alpha.10"

Installing "admob-plus-cordova" for ios
Running command: pod install --verbose
Failed to install 'admob-plus-cordova': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/bartashevich/projects/native-builds/jam-ios-assembled/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
pod: Command failed with exit code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jam-ios-assembled@1.0.0 cordova: `cordova "plugin" "add" "admob-plus-cordova@1.0.0-alpha.10"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jam-ios-assembled@1.0.0 cordova script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bartashevich/.npm/_logs/2021-03-01T14_17_51_169Z-debug.log
```

**Comment by ratson** [comment]
@kosbar Did you run `pod repo update`?

**Comment by ratson** [comment]
Close as related to the old version.
