### ISSUE TITLE
New Features Request Like App Open Ads

### ISSUE THREAD

**Issue by krunalsk007** [admob-plus/admob-plus#228]
i am using you admob free from 2-3 years in Ionic V3 in ADVANCE LEVEL after seen this plugin i want to use this plugin but your this project have still need proper doc for IONIC and some features.
****
1. App Open Ads (it's in beta now)  [https://developers.google.com/admob/android/app-open-ads](url)
2. interstitial Ad close event.
3. ads load failed event.
4. Rewarded Interstitial.

**Comment by EMI-INDO** [comment]
I'm also looking forward to it being added

**Comment by ratson** [comment]
@krunalsk007 @EMI-INDO I am actively working on 2-4.
For Open Ads, I plan to explorer it after v1.0.0 is finalized.
Stay tuned.

**Comment by ratson** [comment]
2-4 has been implemented in the latest release.
I will track https://github.com/admob-plus/admob-plus/issues/202 for 1.
