### ISSUE TITLE
!!! Latest AdMob including migration to SKAdNetwork [Crucial for all to continue displaying ads] !!!

### ISSUE THREAD

**Issue by gigafishapps** [admob-plus/admob-plus#230]
Google announced it will discontinue IDFA on all iOS devices using AdMob to take full advantage of Apple's SKAdNetwrok, so iOS apps won't need to display popups.

The problem is they announced they are discontinuing IDFA with AdMob on all iOS devices, so if there will be no update, probably no ads will show.

My question is, will the latest version of the AdMob plugin be implemented so we can continue displaying any Ads on iOS?

The messages you will see in your AdMob panel soon are:

Some apps haven't been configured to use Apple's SKAdNetwork To ensure you're getting credit for all ads activity, like app installs, be sure to configure SKAdNetwork with Google's network IDs.

Some of your iOS apps require a GMA SDK update To keep ads serving normally and minimize a loss in ad revenue, implement the GMA SDK 7.64.0 (or later) for your iOS apps. And configure the SKAdNetwork in your apps with Google's network ID.

**Comment by ratson** [comment]
@gigafishapps It has been added for the latest version.
https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/plugin.xml#L86

Are you having any issue with it?

**Comment by gigafishapps** [comment]
Thanks for your reply, I am now testing it. Where can I purchase the pro plugin, or tip you? (You should be selling it for at least 20-30 dollars) will let you know if any other questions. Thank you so much.

**Comment by ratson** [comment]
Everything is open sourced and you can use it for free.
If you are interested in sponsor my work, please check out https://admob-plus.github.io/funding/

**Comment by gigafishapps** [comment]
> Everything is open sourced and you can use it for free.
> If you are interested in sponsoring my work, please check out https://admob-plus.github.io/funding/

Just a question. Do I need to enable SKAdNetwork manually or it is automatically enabled for iOS? Google suggests adding special key to Info.plist

**Comment by ratson** [comment]
@gigafishapps Please refer the answer in https://admob-plus.github.io/docs/cordova/faq/#do-i-need-to-enable-skadnetwork-manually
