### ISSUE TITLE
Error IOS build: CompileSwift normal x86_64 ios/projectname/Plugins/admob-plus-cordova/AMBPlugin.swift

### ISSUE THREAD

**Issue by caiotiengo** [admob-plus/admob-plus#233]
Please, I need help with this.
I've been stucked many days with admob-free problems and now I'm facing this error in admob-plus.

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/macbook/Desktop/CaioDEV/project/platforms/ios/project/Plugins/admob-plus-cordova/AMBPlugin.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

I've did everything, even remove ios platforms and all many times.

Thank you!

**Comment by Ricardo385** [comment]
> Please, I need help with this.
> I've been stucked many days with admob-free problems and now I'm facing this error in admob-plus.
> 
> ** BUILD FAILED **
> 
> The following build commands failed:
> CompileSwift normal x86_64 /Users/macbook/Desktop/CaioDEV/project/platforms/ios/project/Plugins/admob-plus-cordova/AMBPlugin.swift
> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)
> 
> I've did everything, even remove ios platforms and all many times.
> 
> Thank you!

Hi @caiotiengo I had the same issue few weeks ago and I resolved it by update my Cordova Cli to latest (10.0.0), make sure you have the latest version by typing in your terminal `cordova -v` and if not uninstall cordova and install it again, then make sure you are using the latest version of Admob Plus that is admob-plus-cordova@1.0.0-alpha.11. If you're compiling for iOS you need to add to your config.xml inside your <platform name="ios"> tag this code
`<preference name="deployment-target" value="11.0" />`
`<preference name="SwiftVersion" value="5.3" />`
Remove platform and add it again.

Hope it solve your problem.

**Comment by caiotiengo** [comment]
Everything normal, same things that you mentioned... but still gives me the same error!

warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'Macumbeijo' from project 'Macumbeijo')
warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'Macumbeijo' from project 'Macumbeijo')
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/macbook/Desktop/CaioDEV/macumbeijo/platforms/ios/Macumbeijo/Plugins/admob-plus-cordova/AMBPlugin.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by Ricardo385** [comment]
> Everything normal, same things that you mentioned... but still gives me the same error!
> 
> warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'Macumbeijo' from project 'Macumbeijo')
> warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'Macumbeijo' from project 'Macumbeijo')
> ** BUILD FAILED **
> 
> The following build commands failed:
> CompileSwift normal x86_64 /Users/macbook/Desktop/CaioDEV/macumbeijo/platforms/ios/Macumbeijo/Plugins/admob-plus-cordova/AMBPlugin.swift
> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

Could you provide what's your ionic info says? Do you have up to date or installed Cocoapods?

**Comment by caiotiengo** [comment]
I have it all up to date!

Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 7 other plugins)

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.3.0) : 1.0.0

System:

   ios-deploy : 1.11.1
   ios-sim    : 8.0.2
   NodeJS     : v12.18.3 (/usr/local/bin/node)
   npm        : 7.5.6
   OS         : macOS Catalina
   Xcode      : Xcode 11.7 Build version 11E801a

**Comment by caiotiengo** [comment]
@ratson do you guys know any answer for this?

**Comment by ratson** [comment]
@caiotiengo I suspect that because you are using npm@7, which you may need to use cordova@nightly.
If that is not the case, would you prepare a repo for me to check?

**Comment by FischerTech** [comment]
@caiotiengo did you find a fix to your problem? I'm having the same issue with xcode 12.4 on both my 2012 mac and new M1 mac books. Thanks.

**Comment by caiotiengo** [comment]
Tried @ratson solution but didn't worked, did you find any solution @FischerTech ?

**Comment by FischerTech** [comment]
@caiotiengo Just took another shot at it this morning, and got it working. I first would suggest updating to the lastest version of xcode, but what worked for me was removing the ios platform after adding admob-plus-cordova and admob-plus/ionic. Then add the platform back, admob-plus-cordova plugin will run pod install for you. DO NOT run `pod repo update` or `cd platforms/ios && pod install --repo-update` after you add the platform.

I had some other issues as well with `npm install admob-plus/ionic` requiring me to use sudo (only usually need for global installs) to get the ngx folder to install and having to manually add my admob app id to the plist manually.

**Comment by ratson** [comment]
Close as related to the old version.

**Comment by caiotiengo** [comment]
@ratson still nothing works.. even in the latest version! how can we solve that?

**Comment by ratson** [comment]
@caiotiengo Please setup a test repo for me to check.

**Comment by caiotiengo** [comment]
@ratson just sent a invitation for you! [heres the link](https://github.com/caiotiengo/macu)
