### ISSUE TITLE
Rewarded Interstitial does not work (Basic Example) @admob-plus-cordova@1.0.0-alpha.11

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#234]
`cordova plugin add admob-plus-cordova@1.0.0-alpha.11 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713`

### and I also tried
`cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713 --variable PLAY_SERVICES_VERSION=19.7.0`

### detail

`CORDOVA CLI: 10.0.0`
`CORDOVA ANDROID : 9.0.0`

I'm trying `Basic Example`

### screenshot
/
/

![Screenshot_2021-03-06-00-03-50-636_example admob basic](https://user-images.githubusercontent.com/78555833/110157961-60e88500-7e1b-11eb-8aaa-1e1f22789735.jpg)

//////////////
//////////////
### and I also saw double banners.
/////////
////

![Screenshot_2021-03-06-00-03-28-416_example admob basic](https://user-images.githubusercontent.com/78555833/110157971-62b24880-7e1b-11eb-8c9e-909dc6b7114a.jpg)

**Comment by EMI-INDO** [comment]
### initially failed to add plugins


```
<plugin name="admob-plus-cordova" spec="../../packages/cordova">
        <variable name="APP_ID_ANDROID" value="ca-app-pub-3940256099942544~3347511713" />
        <variable name="APP_ID_IOS" value="ca-app-pub-3940256099942544~1458002511" />
    </plugin>
```


### error CLI


```
Discovered plugin "admob-plus-cordova". Adding it to the project
Failed to fetch plugin ../../packages/cordova via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: ENOENT: no such file or directory

```

### and I deleted the error section in config.xml = `spec="../../packages/cordova"`


### build success

```
<plugin name="admob-plus-cordova" >
        <variable name="APP_ID_ANDROID" value="ca-app-pub-3940256099942544~3347511713" />
        <variable name="APP_ID_IOS" value="ca-app-pub-3940256099942544~1458002511" />
    </plugin>
```

**Comment by ratson** [comment]
@EMI-INDO Rewarded Interstitial Ad is in development, I will finish some final touches these two days before publishing a new release.
I will check why the example is failing.
Did you do a git clone to run the example?

**Comment by emi415064** [comment]
### I will try later.

sorry I don't have much money for monthly support,
But I will send a cup of coffee 1 to 2 times every month.


thank you. @ratson
