### ISSUE TITLE
Consent: getFormAvailable is not a function

### ISSUE THREAD

**Issue by SeVeNDuS** [admob-plus/admob-plus#235]
### Is this a bug report?

I am getting this error trying to show the consent

Unhandled Promise Rejection: TypeError: consent.getFormAvailable is not a function. (In 'consent.getFormAvailable()', 'consent.getFormAvailable' is undefined)
(función anónima) — app.html:422
asyncFunctionResume
(función anónima)
promiseReactionJobWithoutPromise
promiseReactionJob
callbackFromNative — cordova.js:297

I encapsulate your sample code into a function that is called from onDeviceReady

async function requestConsent() {
            if (cordova.platformId === 'ios') {
                await admob.requestTrackingAuthorization()
            }

            const consentStatus = await consent.getConsentStatus()
            if (consentStatus === consent.ConsentStatus.Required) {
                await consent.requestInfoUpdate()
            }

            const formStatus = await consent.getFormAvailable()
            if (formStatus === consent.FormStatus.Available) {
                const form = await consent.loadForm()
                form.show()
            }
        }

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 11.2.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 185.34 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_232 - /usr/bin/javac
    npmPackages:
      @globules-io/cordova-plugin-ios-xhr: ^1.2.1 => 1.2.1 
      admob-plus-cordova: ^1.0.0-alpha.11 => 1.0.0-alpha.11 
      branch-cordova-sdk: ^4.2.1 => 4.2.1 
      cordova-ios: ^6.2.0 => 6.2.0 
      cordova-plugin-apprate: ^1.7.2 => 1.7.2 
      cordova-plugin-badge: ^0.8.8 => 0.8.8 
      cordova-plugin-buildinfo: ^4.0.0 => 4.0.0 
      cordova-plugin-consent: ^1.0.0-alpha.8 => 1.0.0-alpha.8 
      cordova-plugin-device: ^2.0.3 => 2.0.3 
      cordova-plugin-dialogs: ^2.0.2 => 2.0.2 
      cordova-plugin-globalization: ^1.11.0 => 1.11.0 
      cordova-plugin-inappbrowser: ^5.0.0 => 5.0.0 
      cordova-plugin-inapppurchase: ^1.2.0 => 1.2.0 
      cordova-plugin-network-information: ^2.0.2 => 2.0.2 
      cordova-plugin-sign-in-with-apple: ^0.1.2 => 0.1.2 
      cordova-plugin-splashscreen: ^6.0.0 => 6.0.0 
      cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
      cordova-plugin-x-socialsharing: ^6.0.3 => 6.0.3 
      cordova-plugin-x-toast: ^2.7.2 => 2.7.2 
      onesignal-cordova-plugin: ^2.11.3 => 2.11.3 
    npmGlobalPackages:
      cordova: 10.0.0

### Steps to Reproduce

1. Open the app
2. Execute await requestConsent()
3. Exception

**Comment by ratson** [comment]
@SeVeNDuS It should be `getFormStatus()`, fixed the doc.
Thank you for reporting.
