### ISSUE TITLE
iOS Error: <Google> Invalid Request. Invalid ad width or height: (320, 0)

### ISSUE THREAD

**Issue by maihannijat** [admob-plus/admob-plus#237]
### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 10.15.7
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 523.30 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      admob-plus-cordova: ^1.0.0-alpha.11 => 1.0.0-alpha.11 
    npmGlobalPackages:
      cordova: 10.0.0

### Steps to Reproduce

This is how I implemented:
```
    async showBanner() {
        this.platform.ready().then(async () => {
            await this.admob.start();

            const banner = new this.admob.BannerAd({
                adUnitId: bannerAdIOS,
            });
            await banner.show();
        });
    }

```

### Expected Behavior

The ad should appear on the bottom

### Actual Behavior

The ad does not load and I get an error in the console

### Error

> 
> 2021-03-06 13:33:56.270823-0500 App[26931:240418] [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x600002d3ce60 GADBannerView:0x7f8da9412d20.height == 50   (active)>",
>     "<NSLayoutConstraint:0x600002d3cf50 GADBannerView:0x7f8da9412d20.bottom == UILayoutGuide:0x600003701500'UIViewSafeAreaLayoutGuide'.bottom   (active)>",
>     "<NSLayoutConstraint:0x600002d3cfa0 WKWebView:0x7f8da983da00'Ionic App'.bottom == GADBannerView:0x7f8da9412d20.top   (active)>",
>     "<NSLayoutConstraint:0x600002d3cbe0 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x600003701500'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':WKWebView:0x7f8da983da00'Ionic App' )>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x600002d3ce60 GADBannerView:0x7f8da9412d20.height == 50   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
> 2021-03-06 13:34:24.074851-0500 App[26931:242685] <Google> Invalid Request. Invalid ad width or height: (320, 0)

**Comment by maihannijat** [comment]
2021-03-17 22:08:22.676493-0400 App[37935:2164985] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000037d3ac0 GADBannerView:0x7ff8f6c18a00.height == 50   (active)>",
    "<NSLayoutConstraint:0x6000037d3bb0 GADBannerView:0x7ff8f6c18a00.bottom == UILayoutGuide:0x600002df5dc0'UIViewSafeAreaLayoutGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x6000037d3c00 WKWebView:0x7ff8f9022a00'Ionic App'.bottom == GADBannerView:0x7ff8f6c18a00.top   (active)>",
    "<NSLayoutConstraint:0x6000037d3840 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x600002df5dc0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':WKWebView:0x7ff8f9022a00'Ionic App' )>"

**Comment by ratson** [comment]
@maihannijat Is it still occurred for the latest release?
If the problem persist, would you create a repo for me to look into?

**Comment by maihannijat** [comment]
@ratson resolved. It was happening on a simulator only - not on a real device.
