### ISSUE TITLE
GoogleMobileAds/GoogleMobileAds.h file not found

### ISSUE THREAD

**Issue by gigafishapps** [admob-plus/admob-plus#238]
This occurs on a clean installation, empty Cordova project with test ads when launching in XCode to create an archive for App Store.

AMBPlugin-Bridging-Header.h

#import <Cordova/CDV.h>
#import <GoogleMobileAds/GoogleMobileAds.h>

'GoogleMobileAds/GoogleMobileAds.h' file not found

Followed by:

1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/c/Library/Developer/Xcode/DerivedData/adTest-bkgomwiaxvdnlihfzcrkfngmcjmd/Build/Intermediates.noindex/PrecompiledHeaders/Bridging-Header-swift_HXF936JKEDKS-clang_3Q4HOD9RVGPRF.pch' for bridging header '/Users/c/Desktop/project/adTest/platforms/ios/adTest/Bridging-Header.h'

**Comment by gigafishapps** [comment]
I would like to at least start the plugin. I would be happy to see how it works, but the documentation is lacking. I am very much confused. Followed all the basic steps.

**Comment by ratson** [comment]
@gigafishapps Did you run `pod repo update`?
What steps are you using the created project?
Please post the result of `npx admob-plus@latest info` for me to know what environment you are running.

**Comment by gigafishapps** [comment]
Thanks for your reply. I will document the steps and post them here in a few hours. Let's try to get it right so everyone can benefit. If we can solve this I am happy to volunteer to create a simple step-by-step guide as a supplement for all the users.

Kind regards
David

**Comment by gigafishapps** [comment]
This is what I did:
(I am working on a Mac)

1. Installed fresh cordova project called test01 -> tested working by itself all good.
2. Installed your latest plugin via cordova with the following command:

```
x@Davids-iMac test01 % cordova plugin add admob-plus-cordova@1.0.0-alpha.10 --variable APP_ID_IOS=ca-app-pub-hidden-in-example~hidden-in-example
Adding admob-plus-cordova to package.json
Script file does't exist and will be skipped: /Users/x/Desktop/project/test01/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js
```

It reported the following errors when adding to a clean project by itself: 

```
Script file does't exist and will be skipped: /Users/x/Desktop/project/test01/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js
Installing "cordova-plugin-whitelist" for ios
Script file does't exist and will be skipped: /Users/x/Desktop/project/test01/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js
```

3. I added the target and swift version to config.xml
4. I ran **cordova platform remove ios** and then **cordova platform add ios**

It keeps reminding:

`Script file does't exist and will be skipped: /Users/x/Desktop/project/test01/plugins/admob-plus-cordova/scripts/iosNSAppTransportSecurity.js`

5. I ran **pod repo update**
6. I copied code for interstitial from this place: https://admob-plus.github.io/docs/cordova/ads/interstitial/#usage with google's test adUnit IT ca-app-pub-3940256099942544/4411468910 from here: https://developers.google.com/admob/ios/test-ads#demo_ad_units

7. Project built fine, emulator ran the app but the Interstitial **never** showed.

8. I downloaded the examples file from here: https://github.com/admob-plus/admob-plus/tree/master/examples/cordova
9. Replaced the default file with it and ran again.
10. The app ran and errors showed:

`AdmobBasicExample TypeError: undefined is not a constructor (evaluating 'new admob.RewardedInterstitialAd({adUnitId: 'ca-app-pub-3940256099942544/6978759866'})')`

Then only the rewarded video showed, and the bottom banner, despite top banner and intersitial being clearly enabled by default:

```
    admob
      .start()
      .then(() =>
        Promise.all([
          this.showBannerAd(),
          this.showBannerAdTop(),
          this.showInterstitialAd(),
          this.showRewardedAd(),
          this.showRewardedInterstitialAd(),
        ]),
      )
      .catch(alert)
  },
```

11. I tried changing default adUnitIds to the ones from Google: https://developers.google.com/admob/ios/test-ads#demo_ad_units

The error reoccured:
`AdmobBasicExample TypeError: undefined is not a constructor (evaluating 'new admob.RewardedInterstitialAd({adUnitId: 'ca-app-pub-3940256099942544/6978759866'})')`

And only the Rewarded Video and the bottom banner showed.

12. I then tried removing the banner, then rewarded the video, then interstitial initializations. The same errors occurred, there was no IntersitialAd at all it never showed when Rewarded video or the banner was removed from initialization.

13. IDFA consent form showed once, during the second testing.


There are two things that are the issues here, and I think it is the major one for everyone using your piece of work.

a) there is not enough up to date examples. I believe an example with only one type of Ad and enabled SKAdNetwork by default would be of great help.
b) The documentation from the technical point of view is succinct and great looking but I believe that many people here are on a much lower technical level than you as an author and will find it very difficult to navigate. There are no clear examples with explanations for beginners. I believe many people turn to this plugin because they need a simple solution for their home made Cordova apps. 

I think you made a great plugin and your work are of great value to everyone, and I think it is a shame many people who could benefit and thank you in form of patronage never can use it.

As mentioned before, if we can solve the issues I am happy to voluntarily help you with creating the simple guides for people free of charge just for the sake of helping everybody, especially the little guys creating their simple apps from home.

**Comment by ratson** [comment]
@gigafishapps Thank you for stepping up to write a beginner guide, it is always welcome to improve the documentation.

I don't see you mention `GoogleMobileAds/GoogleMobileAds.h file not found` in your latest comment, is that fixed?

Would you re-run your test with the latest version?
`RewardedInterstitialAd` was introduced after `v1.0.0-alpha.10`.

**Comment by gigafishapps** [comment]
Thank you for your reply.

I will retry all the steps with cordova plugin add admob-plus-cordova --variable APP_ID_IOS=ca-app-pub-xxx~xxx

And send yo the documented process here.

I did not try to archive in XCode yet as the initial setup is not working.

Please correct me if I should use any other initialization instructions, I will follow the steps exactly as per https://admob-plus.github.io/docs/cordova again.

**Comment by Carlosps** [comment]
@gigafishapps and @ratson Any updates on that? 

I am facing exactly the same issue, I run the on my device and it works perfectly great but when I try to archive I get No such module 'GoogleMobileAds'

**Comment by gigafishapps** [comment]
Try copying in AdMob manually into the project and then in your Project
file make sure to include the dependencies. You add that in Build Phases
tab.

**Comment by Carlosps** [comment]
@gigafishapps Yes, I have seen some people mentioning I would have to import it in the build phases but I couldn't find in the list.

Can you please specify where I could copy the Admob from and where to?

Thank you for your help.

**Comment by gigafishapps** [comment]
body{font-family:Helvetica,Arial;font-size:13px}I just did that in my previous reply.   On 8 April 2021 at 21:23:50, Antonio Carlos Reis ***@***.***) wrote: 
@gigafishapps Yes, I have seen some people mentioning I would have to import it in the build phases but I couldn't find in the list.
Can you please specify where I could copy the Admob from and where to?
Thank you for your help.

**Comment by Carlosps** [comment]
@gigafishapps  Can you tell me how your Podfile looks like?
I am guessing it might be some dependency not being listed there.

**Comment by gigafishapps** [comment]
I told you to do it manually not with Pods, try that. Cheers.

**Comment by Carlosps** [comment]
@gigafishapps I have tried what you mention. I did work, I was able to create the archive.

But I have some points to mention. 

I was not able to run on a device without errors anymore
I did face another issue related to deploying to the store 'unexpected Mach-O header code' and it seems to be related to adding the frameworks manually.
So, I believe it would be better for us to solve it using the [recommended option](https://developers.google.com/admob/ios/quick-start#cocoapods)


Were you able to deploy to TestFight?

**Comment by gigafishapps** [comment]
To be honest, for me this plugin and others were so full of occurring
issues I just went with rewriting all my apps in native iOS. I recommend
this approach to you.

**Comment by Carlosps** [comment]
@gigafishapps Thank you for your help.

I was able to solve this issue by going to XCode Targets -> Build Phases -> Link Binary With Libraries

Next I just needed to click the + button and search for
GoogleMobileAds.xcframework
UserMessagingPlatform.xcframework
