### ISSUE TITLE
hide banner is not working

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#239]
**all ads are displayed successfully**

![Screensho](https://user-images.githubusercontent.com/78555833/110544942-0b83df00-815f-11eb-9b5b-9ae872ad8e94.jpg)

`cordova plugin add admob-plus-cordova@1.0.0-alpha.12 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713 --variable PLAY_SERVICES_VERSION=19.7.0`

**detail**
`CORDOVA CLI: 10.0.0`
`CORDOVA ANDROID : 9.0.0`

maybe this is my code error.

I have tried many ways.

### this doesn't work

`Bannerhide() {
    const banner = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
    })
    return banner.show().then(() => banner.hide())`

### this doesn't work

`Bannerhide() {
    const banner = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
    })
    return banner.hide()`

### this doesn't work

`document.addEventListener('admob.banner.impression', async () => {
  const banner = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
    })
    await banner.hide()
});`

### this doesn't work

`document.addEventListener('admob.banner.impression', async () => {
  const banner = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
    })
    await banner.show().then(() => banner.hide())
});`

### Thank you friend

**Comment by ratson** [comment]
@EMI-INDO Would you try the latest release?
`await banner.show()` is resolved as soon as the load request is sent, but not waiting the banner being loaded.

I have updated the example code to be a functional one,
https://admob-plus.github.io/docs/cordova/ads/banner

**Comment by EMI-INDO** [comment]
@ratson 

**Thank you for replying **

### Nothing worked


`remove the platform`
`remove plugins`
`add it back`


### and try them all one by one
admob-plus-cordova@1.0.0-beta.1
admob-plus-cordova@1.0.0-beta.0
admob-plus-cordova@1.0.0-alpha.15


`cordova plugin add admob-plus-cordova@1.0.0-beta.1 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713`


### my code

`document.addEventListener('deviceready', async () => {
  await admob.start()

  const banner = new admob.BannerAd({
    adUnitId: 'ca-app-pub-3940256099942544/6300978111',
   position: 'top',
  })

  await banner.show()
}, false)

document.addEventListener('admob.banner.impression', async () => {
  await banner.hide()
})`


### and I also tested it with examples code, and I've been waiting a few minutes

`nothing happens`

### screenshots


![Screenshot](https://user-images.githubusercontent.com/78555833/111085279-43b56400-8549-11eb-8397-105f53c4dd74.jpg)

**Comment by ratson** [comment]
@EMI-INDO I have made a mistake in the example code, `const banner` should be pull up to `let banner` for the event handler. I have updated the docs to reflect this.

Why are there 2 banners shown? Is that you have created `admob.BannerAd` somewhere?
Note that you have to using the same banner instance to hide the ad.

**Comment by EMI-INDO** [comment]
### works perfectly.
[https://admob-plus.github.io/docs/cordova/](url)

### 2 banners because I tested it with basic example of cordova
[https://github.com/admob-plus/admob-plus/blob/master/examples/cordova/www/js/index.js](url)
`Promise.all([
          this.showBannerAd(),
          this.showBannerAdTop(),
          this.showInterstitialAd(),
          this.showRewardedAd(),
          this.showRewardedInterstitialAd(),
        ])`

### Now there are no more problems.

Thank you friend
