### ISSUE TITLE
Disable tracking by default

### ISSUE THREAD

**Issue by martijnmichel** [admob-plus/admob-plus#241]
I have just started this plugin and decided I do not want to track people in my app and when updating it in the App Store it got rejected with the message that I should ask for permission or not use it.

Apple Reply:
**Next Steps**

_If your app integrates AppTrackingTransparency, please indicate where in your app we can find the AppTrackingTransparency permission request._

_If your app does not integrate AppTrackingTransparency, please indicate this information in the Review Notes section for each version of your app in App Store Connect when submitting for review._

How can I disable AppTracking by default?

**Comment by ratson** [comment]
@martijnmichel You can use the following code for AppTrackingTransparency integration,
```js
  if (cordova.platformId === 'ios') {
    await admob.requestTrackingAuthorization()
  }
```

**Comment by martijnmichel** [comment]
@ratson Thanks for replying, but doesn't that make the modal appear? I want to disable tracking without user interaction.

**Comment by ratson** [comment]
@martijnmichel https://developers.google.com/admob/ios/data-disclosure listed the data need to be collected for AdMob.
I don't see the SDK provide a way to disable tracking, did I miss something?

**Comment by martijnmichel** [comment]
Probably you didn't miss anything. I just don't understand. So what does apple mean with the following?

**If your app does not integrate AppTrackingTransparency**, please indicate this information in the Review Notes section for each version of your app in App Store Connect when submitting for review.

**Comment by rahmadid** [comment]
Hi, if i understand it correctly, it means:

If you integrate ATT into your code (swift/obj-c part), then you must show the ATT permission request to the user.
If you don't show (or don't want to show) the ATT permission request, then you must delete ATT integration from your code (swift/obj-c part).

That makes sense, because ATT is optional. Even admob help site states that:
Decide whether Apple’s ATT prompt is right for your app
As part of iOS 14, you may choose to employ the new ATT framework.
...

Source: https://support.google.com/admob/answer/9997589?hl=en

**Comment by ratson** [comment]
Added to FAQ
https://admob-plus.github.io/docs/cordova/faq#shoud-i-use-apples-att-prompt

**Comment by martijnmichel** [comment]
New binary is now rejected because of the same reason. 
```
Your app contains NSUserTrackingUsageDescription, indicating that you will request permission to track users. To update this information on your app's product page, you must indicate which data types are tracking users. If this is incorrect, update your app binary and upload a new build to App Store Connect.
```
although I am not requesting the auth, removed the NSUserTrackingUsageDescription from info.plist they still say:
--
Guideline 2.1 - Information Needed

We continue to find that your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request.

Since you indicated in App Store Connect that you collect data in order to track the user, we need to confirm that App Tracking Transparency has been correctly implemented.

**Comment by krunalsk007** [comment]
i got same error today at time of my app update i cant understand ATT is optional then why  `NSUserTrackingUsageDescription`
available or automatically added in info.plist ? is this key is added in by you @ratson  in plugin ? is there is a way to delete it. 
have you found any solution for that ? @martijnmichel
