### ISSUE TITLE
How to pass consent "personalized" ads to admob

### ISSUE THREAD

**Issue by SeVeNDuS** [admob-plus/admob-plus#243]
### Is this a bug report?

This is a request of help, so no, is not a bug

Can you help me with an example to show the consent for "Personalized ads" and how to pass that variable to the banner?

Thanks

**Comment by ratson** [comment]
@SeVeNDuS You can pass `npa="1"` to indicate that, see https://admob-plus.github.io/docs/cordova/consent#forward-consent
