### ISSUE TITLE
Request Event Video Cancelled [ admob.rewarded.cancelled ]

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#245]
### Hi, friend

Can this be added?

`document.addEventListener('admob.rewarded.cancelled', async () => {
                //   Triggers when a video advert has been cancelled.
            });`

### thank you

**Comment by ratson** [comment]
@EMI-INDO Probably not going to add that as the official SDK does not provide such callback directly.
However, you should be able to simulate that by listen to the dismiss and reward events.

**Comment by EMI-INDO** [comment]
### well i will try it.

**Thank you friend**
