### ISSUE TITLE
Is the beta version compatible with cordova-admob-plus?

### ISSUE THREAD

**Issue by felipe-ff** [admob-plus/admob-plus#246]
I get this error when I upgrade to the beta:

"Cannot find module 'admob-plus-cordova' or its corresponding type declarations" at index.d.ts in this line: 

import { AdMob as IAdMob, BannerAd as IBannerAd, BannerAdOptions, InterstitialAd as IInterstitialAd, NativeActions, RewardedAd as IRewardedAd, RewardedAdOptions, RewardedInterstitialAd as IRewardedInterstitialAd, RewardedInterstitialAdOptions, TrackingAuthorizationStatus } from 'admob-plus-cordova';

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
*The namespace for the `alpha` version of this plug-in is different from the `beta` (and `final`) version.*

It's done to keep the `branches` separate from each other and prevent updating the wrong version.

## CORDOVA CLI

So if you want the `alpha` version, you can use this command;

`cordova plugin add cordova-admob-plus@0.37.0 --variable APP_ID_ANDROID="ca-app-pub-123~456"`

And for the `beta` (or `final`) version, just use;

`cordova plugin add admob-plus-cordova@1.0.0-alpha.11 --variable APP_ID_ANDROID=ca-app-pub-123~456`

---

Of course the examples above are... examples. So you can remove the specific versioning with the `@` character or the variables with the `--` sign.

_(I am not the author, but I think this can be the reason why you can not update - it's common use in development)._
