### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by Sirioxstar** [admob-plus/admob-plus#248]
Hi All,
i have this problem when build:

AndroidManifest.xml:23: error: unexpected element \<queries\> found in \<manifest\>.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt

Can you help me?

ionic info:

Ionic:

   Ionic CLI                     : 6.13.1 (C:\Users\disk\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1102.4
   @angular-devkit/schematics    : 11.2.4
   @angular/cli                  : 11.2.4
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v10.22.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
`error: unexpected element <queries> found in <manifest>` can be thrown by everything - it's not specifically linked to this plug-in (it could be, but it's not clear with the information you provided).

Just check out this common error : https://stackoverflow.com/questions/62969917/

`Cordova CLI : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms : android 7.1.4`

Also, the CLI is rather old (version 10 is already around on the block) as is the Android platform ([number 9](https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html) is here to stay).

So if your workflow supports is (specially AndroidX, which is introduced by default @9) you can consider an upgrade while debugging the error you mentioned.
