### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =>& Uncaught Error: Module cordova-admob-plus.AdMob does not exist

### ISSUE THREAD

**Issue by wahidung** [admob-plus/admob-plus#25]
when I want to display AdMob ads with the AdMob Plus plugin, an error appears on the console like this : 

Uncaught SyntaxError: Unexpected token => ......................... plugins/cordova-admob-plus/www/admob.js:7
Uncaught Error: Module cordova-admob-plus.AdMob does not exist.......................................... cordova.js:1462

**Comment by Fearcoder** [comment]
You working with ionic?

**Comment by wahidung** [comment]
@Fearcoder no , im working just with cordova & framework7

**Comment by ychsue** [comment]
1. Clone this repository.
2. Edit "packages/cordova/tsconfig.json" and set its "target" to be "es5".
3. Run `$npm install` in the folder "packages/cordova". 
4. Copy "packages/cordova/www/admob.js" to your plugins.
    For my case, I copy its content and substitute the es6 part of the file "...../platforms/android/platform_www/plugins/cordova-admob-plus/www/admob.js", i.e. just keeping its head line and end line.

Hm... The method I used is dirty, but works.

**Comment by combatdave** [comment]
If this is happening in your browser, disable your adblocker.

**Comment by Stewcha** [comment]
> If this is happening in your browser, disable your adblocker.

I was trying everything to solve this but all this time it was this simple, just turn off my adblocker, THANK YOU!
