### ISSUE TITLE
Google play services conflict

### ISSUE THREAD

**Issue by piernik** [admob-plus/admob-plus#250]
I'm trying clean ionic install with `google-maps` and `admob-plus` plugins and I cannot compile.

If I install google maps or admob plus without each other everything is working, but when I install them both I got compilation error:
```
> Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
```

I bet it is conflict with google play services, but I have `<preference name="AndroidXEnabled" value="true" />` enabled as in Your docs (also tried with disabled).
I also have `cordova-plugin-androidx-adapter` installed.

I also tried to change `google-maps` service version with `ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="xxx" --variable GOOGLE_MAPS_PLAY_SERVICES_VERSION="19.7.0"` but result is the same

I also tried:
```
ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="xxx" --variable GOOGLE_MAPS_PLAY_SERVICES_VERSION="17.0.0"
ionic cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID="ca-app-pub-xxx" --variable PLAY_SERVICES_VERSION=17.0.0
```
But then I have errors:
```
> Task :app:compileDebugJavaWithJavac FAILED
C:\strony\www\_del\corApp\platforms\android\app\src\main\java\admob\plugin\ExecuteContext.java:10: error: cannot find symbol
import com.google.android.gms.ads.RequestConfiguration;
                                 ^
  symbol:   class RequestConfiguration
  location: package com.google.android.gms.ads

```

I have `cordova@10`

My plugins are:
```
"dependencies": {
    "@admob-plus/ionic": "^1.0.0-beta.2",
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@ionic-native/core": "^5.22.0-beta-1",
    "@ionic-native/google-maps": "^5.27.0-beta-20200630",
    "@ionic/angular": "^5.5.2",
    "cordova-browser": "6.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.4",
    "@angular/cli": "~11.1.4",
    "@angular/compiler": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@angular/language-service": "~11.2.0",
    "@ionic/angular-toolkit": "^3.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "admob-plus-cordova": "^1.0.0-beta.2",
    "codelyzer": "^6.0.0",
    "cordova-android": "^9.0.0",
    "cordova-androidx-build": "^1.0.4",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  },
```

Help please !

**Comment by ratson** [comment]
@piernik Would you prepare a repo for me to check?

**Comment by piernik** [comment]
@ratson  I've sent You invitation to project.

**Comment by ratson** [comment]
@piernik You need to use the latest play services version,
https://admob-plus.github.io/docs/cordova/faq#how-to-use-with-cordova-android-play-services-gradle-release

**Comment by piernik** [comment]
@ratson You did it :) Thank You.
But there is some issues in docs. Here https://admob-plus.github.io/docs/cordova/installation is that all I need to do is to enable `AndroidX` (I have cordova 10). But it does not work.
So I have to install `cordova-android-play-services-gradle-release`.  Maybe there should be tip to use `cordova-android-play-services-gradle-release` if previuos fails.

**Comment by piernik** [comment]
@ratson it is not working :/ I didn't had time back then so I just try build project and it did worked, but now I see that it didn't has `admob-plus-cordova` plugin in `package.json` :/

I came back to project and tried to build it with no success. Can You take a look once more time?
If I remove one of plugins all works but I need both of them :)

Is You plugin dependent only on `play-services-ads` ?

**Comment by piernik** [comment]
I solved problem 
I had to manually add
```
cordova.system.library.6=com.google.android.gms:play-services-maps:17.0.0
cordova.system.library.7=com.google.android.gms:play-services-location:17.0.0
```
In `platforms/android/project.properties`.

No `cordova-plugin-androidx` and `cordova-android-play-services-gradle-release` is needed.
