### ISSUE TITLE
Banner wrong position after use camera

### ISSUE THREAD

**Issue by jonatarussi** [admob-plus/admob-plus#251]
Hi guys. 
I am having a problem with this plugin. When I show the banner the first time, the banner appears in correct position (bottom), but when I open the camera using the plugin `cordova-plugin-camera-preview` and then close the camera, the ad shows up in the top.

**Comment by maihannijat** [comment]
I confirm this bug. It happens on iOS 14. For me, it happens from start (first page) without using the camera or any other plugin. and without any interaction.

**Comment by ratson** [comment]
@jonatarussi @maihannijat Would you prepare a repo for me to check?

**Comment by ratson** [comment]
Close as related to the old version.
