### ISSUE TITLE
duplicated with element declared at AndroidManifest.xml

### ISSUE THREAD

**Issue by lsantaniello** [admob-plus/admob-plus#252]
I integrated admob-plus plugin into my ionic5 app but I have issue at building time.

After build, AndroidManifest.xml has been updated. APPLICATION_ID has been added. It's perfect but the value is not correct. It'a a hardcoded value

```
        <meta-data android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" android:value="true" />
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxx~yyy" />
```

I inserted real id into package.json as reported by official docs.

```
"cordova": {
      "admob-plus-cordova": {
        "APP_ID_ANDROID": "ca-app-pub-1234567890~123456", //obfuscated id
        "PLAY_SERVICES_VERSION": "19.7.0"
      }
    }
```

I tried to change manually the is into my AndroidManifest.xml file and rebuilt the app.

Now I receive duplication field.

```
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-1234567890~123456" />
        <meta-data android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" android:value="true" />
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxx~yyy" />
```

How I can set correct ID?

Some info:
```
Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\l.santaniello\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.15.3)
   native-run  : 0.2.8 (update available: 1.3.0)

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

package.json contains:
```
"@admob-plus/ionic": "^1.0.0-beta.2",
"@ionic-native/admob-plus": "^5.31.1",
"admob-plus-cordova": "^1.0.0-beta.2",
```

Any help would be much appreciated

Thanks in advance

**Comment by ratson** [comment]
@lsantaniello Did you try delete `platforms`, `plugins` then rebuild the project after changed id?
You may also try update your Cordova CLI to v10 to see if it fixes it.

**Comment by lsantaniello** [comment]
Thanks for reply. What is the best practice to upgrade cordova release?

**Comment by lsantaniello** [comment]
Removed android platform and plugins folder. Rebuild completed successfully

But my ad now show.

Load Fail event has been triggered

I tried to use my App Id and goole test banner id (androidandroid)

I inserted my test device id on admob platform.

I'm very confused.

In the log:
`{
	"isTrusted": false,
	"cause": null,
	"code": 3,
	"adId": 1,
	"message": "Publisher data not found. <https://support.google.com/admob/answer/9905175#9>"
}`

**Comment by ratson** [comment]
@lsantaniello Did you try adding your device via code and use your own ad unit id?
```js
admob.configRequest({
  testDeviceIds: ['33BE2250B43518CCDA7DE426D04EE231']
})
```
https://admob-plus.github.io/docs/cordova/test-ads

**Comment by lsantaniello** [comment]
> @lsantaniello Did you try adding your device via code and use your own ad unit id?
> 
> ```js
> admob.configRequest({
>   testDeviceIds: ['33BE2250B43518CCDA7DE426D04EE231']
> })
> ```
> 
> https://admob-plus.github.io/docs/cordova/test-ads

yes, alredy add my deviceId programmatically

**Comment by lsantaniello** [comment]
> Additional note:
> My testDeviceIs has different format
> 
> ```js
> this.admob.configRequest({
>                 testDeviceIds: ['797583ad-7ef8-4c62-ac95-xxxxxxxxxxxx']
>             })
> ```

Found into logcat, sorry.

`Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("3338DEE2C06**********D71E5BE5D82")) to get test ads on this device.`

Setted into my app but the issue is not solved.

:(

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> It seems that the problem is real banner. test banner works

Real banners never work when the app is not released.

It needs to be `signed` and you can't sign an app while developing it.

That's why you should always develop with `test units`.

Once the app is ready for release, change the ID's to the real ones and release the app.

Or create a special `bèta-branche` for your app, so you can test it (once signed) in a semi-live production workflow.

*BTW - this is for Android.*

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Also see your own logs;

1. `NETWORK 400`
2. `Publisher data not found.`

The first one indicates a bad request (from your site) to the AdMob server.

The second one implies there's something wrong with your account.

So that makes sense to your findings : test-ads works, but real-ads not.

**Comment by lsantaniello** [comment]
App has been released. 

It is not a spam. hxxxs://play.google.com/store/apps/details?id=it.mgdlab.napadel

I checked my account. It seems correct.

Some advice? in addition to creating unity, do I have to do anything else?

Thanks

**Comment by ratson** [comment]
@lsantaniello Would you run `npx admob-plus@1.4.0 doctor` in your cordova project root directory to see if it detects any issues?
