### ISSUE TITLE
Crash on iOS while init banner

### ISSUE THREAD

**Issue by maihannijat** [admob-plus/admob-plus#254]
### Is this a bug report?

Yes

### Error
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'CALayerInvalid', reason: 'layer <CALayer: 0x2832217c0> is a part of cycle in its layer tree'
terminating with uncaught exception of type NSException

Thread 1: "layer <CALayer: 0x2832217c0> is a part of cycle in its layer tree"
Thread 1: AMBBanner.initi(id: adUnitId, adSize, position)

## Steps to reproduce
1- Updated to 1.0.0-rc.0
2- Build with `ionic cap build --prod ios`

**Comment by ratson** [comment]
@maihannijat Would you try 1.0.0-rc.1 to see if it fixes your problem?
I cannot reproduce your exception, it would be great if you could setup a repo for me to test.

**Comment by maihannijat** [comment]
@ratson I am using Ionic Angular with Capacitor. I have installed Admob Plus Ionic with Admob Plus Cordova and that's why it was crashing. I removed both plugins and installed Admob Capacitor only but it does not compile now. See the below error:

> ERROR in ./node_modules/@admob-plus/capacitor/dist/esm/index.js 2:18-32
> "export 'registerPlugin' was not found in '@capacitor/core'

**Comment by ratson** [comment]
@maihannijat I am not sure what is going wrong with your setup by looking at the error message.
You could clone and try https://github.com/ratson/AdmobPlusDemo

**Comment by maihannijat** [comment]
@ratson 

I can see you are using the beta version of the Capacitor which fixes the compile issue.

>  "@capacitor/core": "^3.0.0-rc.0",
>  "@capacitor/ios": "^3.0.0-rc.0",

I am testing your repo and get back to you.

**Comment by maihannijat** [comment]
Closing this issue since crashing fixed with using Admob Plus Capacitor and using the above-mentioned versions of the Capacitor and iOS.
But with these changes, bug #256 appears. I also see a black screen and the banner ad at the bottom.

**Comment by ratson** [comment]
@maihannijat Would try apply the fix and let me know the result? I cannot see the black screen problem.
