### ISSUE TITLE
'No ad config.' Presenting live ads in Android

### ISSUE THREAD

**Issue by Calsy** [admob-plus/admob-plus#255]
Hi,

Might be missing something obvious.  Test ads work fine on Android build, but when I attempt to run live ads I get the following message in console

```
Uncaught (in promise) {
  "Code": 3,
  "Message": "No ad config.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null",
  "Response Info": {
    "Response ID": "null",
    "Mediation Adapter Class Name": "",
    "Adapter Responses": []
  }
}
```

What config setting am I missing?

**Comment by ratson** [comment]
@Calsy Is you app published to app store?

**Comment by Calsy** [comment]
@ratson Thanks for reply.  Yes app is published on Google Play. Previously using admob-free without issue but moving over to admob-plus.  Everything seems fine, the app builds on android without issue and I can display test Interstitial ads.  It's when I try live ads that I get the issue.  The message 'No ad config.' obviously gives the impression I'm missing some setting.

I add the plugin using the command shown on the admob-plus docs page

```
cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx
```

I have not added any extra settings to ```config.xml```.  However, ```AndriodManifest.xml``` looks to have the necessary details

```
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxx~xxx" />
```

Double checked the APP ID in admob and its correct.

**Comment by ratson** [comment]
If you confirm your setting is correct, there is not much can be done other than waiting.
>    #### Error Code 3 : ERROR_CODE_NO_FILL
>
>    Description (Dev Docs Link) : The ad request was successful, but no ad was returned due to lack of ad inventory.
>
>    Why is  it Happening : Advertisers can target specific regions, platforms and user profiles based on business relevance, which can sometimes result in lower availability of Ads for a particular region or user profile. Error code suggests that the implementation is correct, and that the Ad Request was not filled because of lack of availability of a suitable Ad at that particular instant of time when an Ad Request was sent from the app.
>
>    Policy related restrictions on certain Apps or Ad Units will also lead to Error Code 3 being returned in response to Ad Requests.
>
>    What Can The Pub Do About it :
>
>    → As we cannot manipulate advertiser demand, there are no particular ‘fixes’ for this error - the pub can cross-check the Ad Unit implementation to ensure that the Ad Units are implemented correctly.
>
>    → Mediation : In some instances, certain Ad Networks may have limited performance in some regions or for specific formats, in which case the pubs can try using mediation to add other Ad Networks that may potentially perform well.
>
>    → Check for Policy status for the Pub ID, the App and the Ad Unit ID. Also check the Brand Safety flags and Coppa status.
>
>    → If the Pub can obtain Test Ads for an Ad Unit (Instructions) - then their implementation is correct, and the Ad Units will serve Ads normally when an Ad is available depending on advertiser demand.

**Comment by richwebapps** [comment]
I'm having the same issue. I had Admob Pro amd moving to Admob Plus. Everything works fine on the Simulator but not on a real device. The app is live and showing ads correctly with the other plugin, but not with Admob Plus. I can't publish until I can verify that ads run. There must be a reason why it says "No ad config."

**Comment by richwebapps** [comment]
@Calsy were you able to resolve this?   @ratson I think there's more to it than lack of inventory. I've tried existing ad units that are working fine with the existing release as well as brand new ad units, banner and interstitial. If I add the testDeviceIds in the configRequest, it shows a test ad on the devices, but I can't get a real ad to show.

**Comment by bartboersma** [comment]
Same issue. IOS works fine, Android works fine on emulator but not on real device.

**Comment by richwebapps** [comment]
For others experiencing this, I tried building a production APK and deployed it manually and it finally shows ads. It seems the debug build has this issue. I still think there's something in this plugins since other plugins don't seem to have this issue.

**Comment by bartboersma** [comment]
@richwebapps same for me. I think it has something to do with 'filling the advertisement inventory'. There simply seems to be no advertisements, but this was resolved on production.

**Comment by acedigibits** [comment]
i am facing ads issue on production. 
i installed previous production app from play store with admob-free and it showed banner ads instantly.
Then i installed current production app from play store with admob-plus (all admob-free plugins removed, no banner ads shown.

Current production app was tested with test ads that worked wonderfully, but production ads on app downloaded from play store not working. Plz help as i have to update all my apps to admob-plus.

**Comment by leandronorcio** [comment]
Same for me, only production ads work, Test ads don't work, it just keeps firing the 'loadfail' event.
