### ISSUE TITLE
hi friend how is this?

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#257]
### hi friend how is this?

_If my code is wrong, please correct it_

### click the Show banner button
`Double Ad`

_How to prevent ads from becoming double_

### Check  app-release-SIGNED_ALIGNED.apk
[app-release-SIGNED_ALIGNED.zip](https://github.com/admob-plus/admob-plus/files/6177768/app-release-SIGNED_ALIGNED.zip)

### VIDEO

https://www.youtube.com/watch?v=hCNbmD27qag

_Thank you friend_

**Comment by ratson** [comment]
@EMI-INDO You are create `BannerAd` every time when calling `showBannerAd()`, wrap it like this to avoid that,
```
if (!banner) {
   banner = new admob.BannerAd({ ... })
}
await banner.show()
```

**Comment by EMI-INDO** [comment]
### perfect it worked

_Thanks a friend_
