### ISSUE TITLE
examples cordova consent does not work (Android)

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#261]
### I tried this it doesn't work on android
https://github.com/admob-plus/admob-plus/tree/master/examples/cordova-consent

`cordova plugin add cordova-plugin-consent@1.0.1`
`cordova plugin add admob-plus-cordova@1.0.1 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713`

### Ad no show

_thank you_

**Comment by Carlosps** [comment]
Is not user consent only for iOS platform?

**Comment by EMI-INDO** [comment]
@Carlosps 

### I don't know, Sorry🙏

### This old version supports android and ios, works for me.
https://github.com/admob-plus/admob-plus/blob/cordova-plugin-consent%400.19.0/examples/consent/www/js/index.js

Thank you.

**Comment by ratson** [comment]
@EMI-INDO Try remove the if block
```js
if (
        [
          consent.ConsentStatus.NotRequired,
          consent.ConsentStatus.Obtained,
        ].includes(await consent.getConsentStatus())
      ) {
...
}
```

**Comment by EMI-INDO** [comment]
@ratson 

### Hi, friend

_I tried this, it didn't work (android)_

_remove plugins and platforms, re-add_

https://admob-plus.github.io/docs/cordova/consent

document.addEventListener('deviceready', async () => {
  if (cordova.platformId === 'ios') {
    await admob.requestTrackingAuthorization()
  }

  const consentStatus = await consent.getConsentStatus()
  if (consentStatus === consent.ConsentStatus.Required) {
    await consent.requestInfoUpdate()
  }

  const formStatus = await consent.getFormStatus()
  if (formStatus === consent.FormStatus.Available) {
      const form = await consent.loadForm()
      form.show()
  }else{
  
  
            await admob.start()
           let banner
           banner = new admob.BannerAd({
           adUnitId: 'ca-app-pub-3940256099942544/6300978111',
           })

          await banner.show()

         }
  
}, false)


### For now  I'm still sticking with the old version

`cordova-plugin-consent@0.19.0`

### thank you

**Comment by ratson** [comment]
@EMI-INDO What values do you get from `consentStatus` and `formStatus`?

**Comment by EMI-INDO** [comment]
@ratson 

no value I got from `form.show (). catch (alert)`

### is pub-xxxx required?

`await consent.requestInfoUpdate(['pub-xxxxxxxxxxxxxx'])`


I tested it with an application that has been released in the Play Store

and the admob Funding Choices account
has been activated


thank you
