### ISSUE TITLE
IOS Capacitor - black status bar and safe area on IOS devices after banner.show()

### ISSUE THREAD

**Issue by kevinainleywalker** [admob-plus/admob-plus#265]
### Is this a bug report?

Yes

### Environment

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0

Plugins:
"@admob-plus/capacitor": "^1.0.2"
```

### Steps to Reproduce

1. install @admob-plus/capacitor@1.0.2
2. use the following code in the app component:
```
await this.platform.ready();
await AdMobPlus.start();

const banner = new BannerAd({
  adUnitId: 'ca-app-pub-3940256099942544/6300978111'
});

await banner.show();
```
3. Run the app

### Expected Behavior

Banner ad will insert into the safe area at the bottom position and the status bar/bottom safe area offset will remain the default app color

### Actual Behavior

The status bar and bottom safe area offset color is changed to black as soon as banner ad is first shown.

The official capacitor docs say they don't support amending status bar color on their plugin as apple don't export an api for it. (Status bar on ios devices being transparent), so I can't set the status bar color back to the default after the banner is shown on IOS.

Included before and after from the demo project:

![Before](https://user-images.githubusercontent.com/1355081/112204092-306e5c80-8c0b-11eb-969a-c40cc3ced6ae.png)
![After](https://user-images.githubusercontent.com/1355081/112204295-67447280-8c0b-11eb-949d-fc09947d63db.png)

### Reproducible Demo

[Demo Project](https://github.com/kevinainleywalker/AdmobPlusDemo)

**Comment by ratson** [comment]
@kevinainleywalker Fixed in v1.1.0
Instead of setting the background color as the app color (which I don't know how to read from the webview), I make the text visible with light color.

**Comment by kevinainleywalker** [comment]
Works for me @ratson , thanks!

**Comment by fseve** [comment]
Could you please explain what is the specific solution? I can't understand it
