### ISSUE TITLE
cordova-plugin-consent ( error: Method must be call on main thread )

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#273]
### Hi, friend
_If my code is wrong please correct it_

### Produce `Method must be call on main thread`

`The original admob app id`
`The original admob AD ID`
`Admob Funding Choices ACTIVATED`
`com.package app original`

### Action  get Consent Status

            `const consentStatus = async () => {
            const Status = await consent.getConsentStatus()
        
            if (Status == consent.ConsentStatus.Unknown) {
           
            console.log('Unknown consent status')
            
            } else if (Status == consent.ConsentStatus.Required) {
            await consent.requestInfoUpdate()
           
            console.log('User consent required but not yet obtained.')
        
            } else if (Status == consent.ConsentStatus.NotRequired) {
           
            console.log('User consent not required. For example, the user is not in the EEA or the UK.');
           
           }
           
          };`

     

### action get Form Status

```
`      const formStatus = async () => {
        const s = await consent.getFormStatus()
            if (s == consent.FormStatus.Unknown) {
          
          console.log('Unknown consent form status')
       
        } else if (s == consent.FormStatus.Available) {
         
        return this.formshow()

        console.log('Available consent form status')
 
        } else if (s == consent.FormStatus.Formunavailable) {
           
            console.log('Unavailable consent form status')
        }
       };
`
```

![Screenshot_2021-03-28-07-41-27-206_com on off](https://user-images.githubusercontent.com/78555833/112739604-d7eae680-8f9f-11eb-9f7d-61adbebfbc7d.jpg)

### form show

         const formshow = async () => {
         let form
         try {
          form = await consent.loadForm()
          await form.show()
         } catch (err) {
         console.log(JSON.stringify('Error form show :' +err))
        
        }
      };

![Screenshot_2021-03-28-07-41-38-758_com on off](https://user-images.githubusercontent.com/78555833/112739577-90fcf100-8f9f-11eb-9370-ae1d3f1573a1.jpg)

### I tried this and got the same error
https://github.com/admob-plus/admob-plus/tree/master/examples/cordova-consent

**Comment by ratson** [comment]
@EMI-INDO Thank you for reporting it, I will soon release the fix.
