### ISSUE TITLE
Cannot find an ad network adapter with the name(s): com.google.DummyAdapter.

### ISSUE THREAD

**Issue by sqapli** [admob-plus/admob-plus#277]
Hi

Working with the Reward Ad Test ID for ios, I get the following error after requesting an ad on the xcode-simulator:

"Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target."

**Plugins:**
@admob-plus/ionic: 1.0.5
admob-plus-cordova: 1.2.2

**iOS Test ID:**
ca-app-pub-3940256099942544/1712485313

It works on Android!
Does anyone have an idea what the problem could be?

Thanks

**Comment by ratson** [comment]
@sqapli I am able to use it to display ads.
Would you create a test repo for me to check?
