### ISSUE TITLE
Are there any plans to add mediation ads

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#282]
### Hi, friend

Are there any plans to add mediation ads?

https://developers.google.com/admob/android/mediate

thank you

**Comment by ratson** [comment]
@EMI-INDO No plan to add that, unless someone would fund it for supporting a particular ad networking.
You vote and continue the discussion in https://github.com/admob-plus/admob-plus/discussions/269

**Comment by Carlosps** [comment]
> ### Hi, friend
> Are there any plans to add mediation ads?
> 
> https://developers.google.com/admob/android/mediate
> 
> thank you

Have you found any solution to include mediation in your app?
