### ISSUE TITLE
Ad doesn't work

### ISSUE THREAD

**Issue by NeroNekro** [admob-plus/admob-plus#284]
Hello there,

the app doesnt show any adds. I dont get any errors. 

I added the scripts at the bottom from my html page.
<script src="js/admob.js"></script>

```
let banner;

document.addEventListener("deviceready", onDeviceReady, false);

async function onDeviceReady() {
    fileTransfer = new FileTransfer();
    await admob.start()
    banner = new admob.BannerAd({
        adUnitId: 'ca-app-pub-3940256099942544/6300978111',
    })
    interstitial = new admob.InterstitialAd({
        adUnitId: 'ca-app-pub-3940256099942544/1033173712',
    })
    await interstitial.load()
    await interstitial.show()
    await banner.show()


}

document.addEventListener('admob.banner.impression', async () => {
    await banner.hide()
})

document.addEventListener('admob.interstitial.dismiss', async () => {
    // Once a interstitial ad is shown, it cannot be shown again.
    // Starts loading the next interstitial ad as soon as it is dismissed.
    await interstitial.load()
})
```

Plugin is installed
`cordova plugin ls
admob-plus-cordova 0.0.0 "admob-plus-cordova"`

AndroidManifest.xml : In my file is the right ID
`<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-11111111111~1111111" />
        <meta-data android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" android:value="true" />`

Where is my issue? 

Thanks

**Comment by ratson** [comment]
@NeroNekro I don't see anything wrong in the code.
Did you read https://admob-plus.github.io/docs/troubleshooting?

**Comment by EMI-INDO** [comment]
@NeroNekro 

Your banner is correct, but because there is `await banner.hide ()` the banner is immediately missing.

interstitial will not appear, add `let interstitial`


###  try the sample code that has been provided.

https://github.com/admob-plus/admob-plus/tree/master/examples/cordova

**Comment by NeroNekro** [comment]
Thanks for the tips.

I have now tried out a few things.

The example from you works immediately as a separate app.

Then I copied the Javascript code and used it 1:1. Then the Deviceready div and a banner plus a InterstitialAd transferred as a button. In my app it shows device ready, but pressing the banner buttons has no success.

I have compared the missing Config.xml with mine and added missing content.

A renewed call of npx admob-plus doctor now led to new errors

i package.json
  √ cordova.plugins.admob-plus-cordova.APP_ID_ANDROID
  √ cordova.plugins.admob-plus-cordova.APP_ID_IOS
i config.xml
  √ APP_ID_ANDROID
  √ APP_ID_IOS
  × PLAY_SERVICES_VERSION
   i Replace undefined with 19.8.0
  × USAGE
   i Replace undefined with This identifier will be used to deliver personalized ads to you.
  × DISABLESDKCRASHREPORTING
   i Replace undefined with false
i plugins\admob-plus-cordova\package.json
  √ admob-plus-cordova: 1.3.0
× Found 3 issues.

I dont find in both Config.xml files any row with play services.  
Where and how to set up the play service version?

Thanks for your help

**Comment by EMI-INDO** [comment]
@NeroNekro 

### in config.xml

[config.zip](https://github.com/admob-plus/admob-plus/files/6239165/config.zip)


```
<plugin name="admob-plus-cordova">
<variable name="APP_ID_ANDROID" value="ca-app-pub-3940256099942544~3347511713"/>
<variable name="APP_ID_IOS" value="ca-app-pub-3940256099942544~1458002511" />
<variable name="PLAY_SERVICES_VERSION" value="19.8.0"/>
</plugin>
```




### index.html + JS

_try this simple code_


[index.zip](https://github.com/admob-plus/admob-plus/files/6239206/index.zip)

**Comment by NeroNekro** [comment]
@EMI-INDO 

cool, thats work beautiful :) Thanks

Can I put the Banner in a div? At the moment the banner moves my entire layout and some offset it breaks my background

**Comment by EMI-INDO** [comment]
@NeroNekro 

https://admob-plus.github.io/docs/cordova/ads/banner

**Comment by ratson** [comment]
@NeroNekro You cannot put the ads in div since they are not HTML element.
You could use `offset=0` to overlay the banner.

Close as the issue is resolved.
