### ISSUE TITLE
Banner Ad show() causing ad to be re-created each time

### ISSUE THREAD

**Issue by harryt2** [admob-plus/admob-plus#286]
When you `hide()` and then `show()` the banner ad, it gets re-created. This is a problem because it causes you to make too many ad requests, which can affect your CPM. Each advertiser is getting less screen time (lowers CTR) since it's switching so quickly.

You can test this by running `hide()` and `show()` a few times and you'll see the ad flash and change each time you call `show()`. It should just resume the ad instead of re-creating it. Maybe split the methods up into `show() hide() create() destroy()` ??

I looked at the code and it seems to attempt to do things the right way on Android, but it's not working for some reason. 

Any help would be appreciated because everything else about this plugin is really awesome and easy to use.

**Comment by ratson** [comment]
@harryt2 Would you try with `admob-plus-cordova@1.4.0` to see if it fixes the issue?

**Comment by harryt2** [comment]
I just tested it. I can confirm that this is working perfectly. Thank you so much, amazing plugin!! :)
