### ISSUE TITLE
'bringSubviewToFront' has been renamed to 'bringSubview(toFront:)'

### ISSUE THREAD

**Issue by osben** [admob-plus/admob-plus#289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

```
(paste the output of the command here)
```

**Additional context**

https://prnt.sc/113o7ha

**Comment by osben** [comment]
https://prnt.sc/113o7ha

**Comment by ratson** [comment]
@osben Please run `npx admob-plus@1.6.0 doctor` to check if you are build with old swift version.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Run the following command in your project root directory,

`npx admob-plus doctor`

*This will scan for common errors and provide suggestions how to fix them.*

Ref. https://admob-plus.github.io/docs/troubleshooting
