### ISSUE TITLE
The click event does not work

### ISSUE THREAD

**Issue by dkstraub** [admob-plus/admob-plus#292]
Hi,

The click event does not work. I am trying to detect when the user interacts with the banner but I am not successful

            document.addEventListener('admob.banner.click', async () => {
                alert(1);
            })

in version 0.X the detection was done with the following event -> admob.banner.exit_app

I hope you can help me.

Thanks for the excellent work!

**Comment by EMI-INDO** [comment]
@dkstraub 

https://admob-plus.github.io/docs/cordova/api/enums/events

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
`click` does work, even `close` (on Android) does work.

See https://github.com/admob-plus/admob-plus/pull/259

---

But you are using the alpha / bèta version of this plug-in with a different namespace.

*Please update / upgrade to the production version as mentioned above.*

**Comment by ratson** [comment]
@dkstraub There is not official way to listen the banner click from the iOS SDK. If you know one, please let me know.
The `exit_app` event has been removed because the the latest SDK has removed it.
