### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by kotran88** [admob-plus/admob-plus#293]
I just follow as installation guide says
 ```

import { AdMob } from '@admob-plus/ionic/'

this.platform.ready().then( async () => {

      console.log("1111platform ready! in home")
      console.log(this.admob);
      await this.admob.start();
       this.admob.start().then(()=>{
        console.log("1111start done")
      }).catch((e)=>{
        console.log("1111start error")
        console.log(e);
      })
     
      const banner = new this.admob.BannerAd({
        adUnitId: 'ca-app-pub-7362472663019563/xxxxxxxxx',
      });
      console.log("1111 banner is "+banner);
       banner.show().then(()=>{
console.log("1111show then come")
      }).catch((e)=>{
        console.log("1111error in show "+e);
      })

```
but the problem is that it cause below error on this.admob.start()
why is it happened? 

``ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at AdMob.start (index.js:191)
    at HomePage.<anonymous> (home.ts:138)
    at step (main.js:1816)
    at Object.next (main.js:1797)
    at main.js:1791
    at new t (polyfills.js:3)
    at webpackJsonp.31.__awaiter (main.js:1787)
    at home.ts:134
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
```

admob-plus-cordova 0.0.0 "admob-plus-cordova"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-kakao-sdk 3.0.6 "KakaoCordovaSDK"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.5 "ImagePicker"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 6.0.3 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"
onesignal-cordova-plugin 2.11.0 "OneSignal Push Notifications"

**Comment by piernik** [comment]
I have the same problem. 
If You are using it in browser (as `ng serve`) it is not working.
It works only when it is built with cordova.

**Comment by ratson** [comment]
@kotran88 You need to import `'@admob-plus/ionic/ngx` and inject the AdMob instance in `AppModule`.
Update the docs, https://admob-plus.github.io/docs/ionic#initialize-admob-sdk

**Comment by piernik** [comment]
@ratson it is not a solution. I have AdMob provided. If I didn't it wouldnt work also when build with cordova.

**Comment by ratson** [comment]
@kotran88 @piernik I can tell the cause just from the error, a test repo will help me to see the problem.
