### ISSUE TITLE
offset not work properly

### ISSUE THREAD

**Issue by shadiawad** [admob-plus/admob-plus#294]
Hi
When I try to use offset: 0, then I click hardware back button then return to app to show ads again ( app crash) .

  showBannerAd() {
    const banner = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
	  offset: 0,
    })
    return banner.show()
  },

https://user-images.githubusercontent.com/24823430/113705043-9d8ef100-96e5-11eb-8a57-d54682cac184.mp4

Thanks

**Comment by Mou95** [comment]
Hi, how did you manage to use this plugin? I am not able to call admob.start(). Looks like admob is always undefined even after deviceready event is triggered

Thanks

**Comment by ratson** [comment]
@shadiawad Would you confirm if this is fixed in `admob-plus-cordova@1.5.0`?

**Comment by shadiawad** [comment]
Works for me Thank you so much for excellent plugin
