### ISSUE TITLE
get consentType with consent plugin

### ISSUE THREAD

**Issue by MrRotella** [admob-plus/admob-plus#295]
To make best use of the recent property 'npa' in the creation of the banner, it would be useful to implement the new method getConsentType.
[https://developers.google.com/admob/ump/android/api/reference/com/google/android/ump/ConsentInformation.ConsentType](https://developers.google.com/admob/ump/android/api/reference/com/google/android/ump/ConsentInformation.ConsentType)
Thanks for your valuable work on this project.

**Comment by ratson** [comment]
@MrRotella The consent type API has been removed from the iOS SDK, see https://developers.google.com/admob/ump/ios/download
