### ISSUE TITLE
StatusBar.overlaysWebView is overwritten from admob plus

### ISSUE THREAD

**Issue by bardgr** [admob-plus/admob-plus#297]
**Describe the bug**
I have in my cordova app the plugin cordova-plugin-statusbar version 2.4.3
I set in the preferences at config xml for ios the StatusBar.overlaysWebView to False
**To Reproduce**
1. Create a cordova app for ios that has a long index html
2. install cordova-plugin-statusbar version 2.4.3
3. In config xml for platform ios add the following 

> preference name="StatusBarOverlaysWebView" value="false" 
>         preference name="StatusBarBackgroundColor" value="#D66C6E" 
>         preference name="StatusBarStyle" value="lightcontent" 

4. install admob-plus-cordova version 1.4.0
5. Have a bottom banner 
6. run the app
7. The status bar is transparent
8. in Safari console run StatusBar.overlaysWebView(false);
9. You will see the app getting covered
10. uninstall admob-plus-cordova and run the app again
11. issue is not there

**Expected behavior**
StatusBar.overlaysWebView value should not be overwritten

**Screenshots**
Added screenshot

**Environment**
iOS
<img width="321" alt="Screenshot 2021-04-08 at 4 48 22 PM" src="https://user-images.githubusercontent.com/48242586/114079465-e7790200-98b2-11eb-97f3-b594a6713679.png">

```
(paste the output of the command here)
```

**Additional context**

**Comment by omedina72** [comment]
I have been using admob-plus for quite a while now. Now I'm trying to update to comply with the new consent requirements. BUT I'm having exactly the same issue about the statusbar. Whenever the ad banner is shown at the bottom the webview overlaps the statusbar. This happens in iOS at least.

**Comment by ratson** [comment]
@omedina72 @bardgr Would you create a test repo for me to check?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
I tested this on `Android 5, 6, 7, 8, 9` and `10` (all real world devices, not simulators) - but I can not reproduce the issue on this OS.

(just to narrow the bug)

**Comment by bardgr** [comment]
Hello @ratson ,
Here -> https://github.com/bardgr/testing-repo-admob-plus-297/tree/main/testing you can find a test repo
you need to run cordova platform ad ios and add the plugins.

ca-app-pub-3940256099942544~1458002511 is a generic variable for  APP_ID_IOS.

Try loading first only the status bar plugin then add the admob-plus-cordova. You will see the statusbar when you do not have admob plus cordova. Once you install both you will see that the status bar is lost and the bottom banner is visible.

Thanks for looking at this :)

**Comment by ratson** [comment]
@bardgr Thank you for setting up the repo, it really helps me to identify the issue.
Please try `admob-plus-cordova@1.5.1` and report back if the issue is resolved.

**Comment by bardgr** [comment]
Hello @ratson ,

Thank you very much the issue is resolved :)
