### ISSUE TITLE
Open Bidding support (Mediation to maximize revenue)

### ISSUE THREAD

**Issue by ShakesVision** [admob-plus/admob-plus#300]
I need a little help with this beta program called **Open Bidding** by admob. Is there a way to achieve this (mediation thing?) via your plugin + ionic? 

[Overview of Open Bidding (Beta)
](https://support.google.com/admob/answer/9234488?hl=en#zippy=%2Cexample-open-bidding-mediation-group)

The official website suggests some native code here:
https://developers.google.com/admob/android/mediate

The instructions on how to implement such system is still not very clear. Please add an example in your well-maintained documentation if you have this feature. 

**P.s:** I'm pretty noob in this and have been using your admob-free plugin without any clue how it's working.
Thanks in advance.

**Comment by ratson** [comment]
see https://github.com/admob-plus/admob-plus/discussions/269
