### ISSUE TITLE
Banner not correctly shown after rotate

### ISSUE THREAD

**Issue by 1n3JgKl9pQ6cUMrW** [admob-plus/admob-plus#301]
### **Describe the bug**

Banners are not resized when the device is rotated, even when a new banner is loaded after the rotation itself.

### **To Reproduce**

1. Hold your device in `portrait-mode` and start the app
2. A banner is shown, e.g. 320x50 dimension **(see image 1)**
3. Rotate the device to `landscape-mode`
4. The same banner is shown **(see image 2)**

The above will show "portrait-mode" banners after the rotation, *which is fine* because portrait-mode banners do fit in width on a landscape-mode device.

1. Hold your device in `landscape-mode` and start the app
2. A banner is shown, e.g. 480x32 dimension **(see image 3)**
3. Rotate the device to `portrait-mode`
4. The same banner is shown **(see image 4)**

This way the landscape-mode banner *will not fit / resize* in portrait-mode and all the new banners are also loaded in the initial landscape-mode dimensions.

### **Expected behavior**

Auto-rotate  (re-size / re-initialize) of the banner, with updated dimensions when a user rotates the device.

Of course I can attach a listener `onDeviceRotate` but even than I have to `destroy()` the banner (is there an API for `destroy`?) and reload / re-initialize the whole thing again.

### Image 1 - Initially portrait

![image](https://user-images.githubusercontent.com/15701574/114200209-43946280-9955-11eb-8fde-e92b978f3e3b.png)

### Image 2 - Rotate portrait to landscape

![image](https://user-images.githubusercontent.com/15701574/114200224-47c08000-9955-11eb-9505-c6183426c73d.png)

### Image 3 - Initially landscape

![image](https://user-images.githubusercontent.com/15701574/114200242-4bec9d80-9955-11eb-9f3a-3674fdd584bb.png)

### Image 4 - Rotate landscape to portrait

![image](https://user-images.githubusercontent.com/15701574/114200260-5018bb00-9955-11eb-9eda-539989c64389.png)

----

I did check this with `cordova plugin 1.4.0` on several tablets, phones and laptops (all Android).

_Images are somehow cropped for visual purposes, but all used devices have industry-standard dimensions._

### **Used code**

I did not test with the option `BANNER_SIZE` so this defaults to `SMART_BANNER` I guess.

`let banner;`
`document.addEventListener( "deviceready", async () => {`
`  await admob.start();`
`  banner = new admob.BannerAd({`
`    adUnitId: 'ca-app-pub-xxx/yyy'`
`  })`
`  await banner.show();`
`}, false )`

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
I **color-coded** the areas / behavior what (I think) causes the problem.

![image](https://user-images.githubusercontent.com/15701574/114202819-df26d280-9957-11eb-928f-960acca88bea.png)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
**The issue was closed while I was adding my solution. So I will add my solution for future reference, while this may be deprecated.**

---

I fetched the Cordova Orientation plug-in from https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-screen-orientation/

After that, I used a listener that hides the current banner and creates a new one when the device is rotated.

### BEFORE ROTATION

![image](https://user-images.githubusercontent.com/15701574/114270944-5cf9e500-9a0f-11eb-8539-87796c9b281c.png)

### AFTER ROTATION

![image](https://user-images.githubusercontent.com/15701574/114270935-510e2300-9a0f-11eb-8168-0281364b3b46.png)

## INDEX.HTML

```
<!DOCTYPE html>
<html>
  <head>
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no">
    <link rel="stylesheet" href="css/style.css">
    <title>Ad Tester</title>
  </head>
<body>

  <h1 id="device_orientation">Orientation</h1>

  <button type="button" onclick="app__ad_interstitial();">Interstitial</button>

  <script type="text/javascript" src="cordova.js"></script>
  <script type="text/javascript" src="js/index.js"></script>

</body>
</html>
```
## STYLE.CSS

```
* {
  -webkit-tap-highlight-color: rgba( 0, 0, 0, 0 );
  -webkit-touch-callout: none;
  -webkit-text-size-adjust: none;
  -webkit-user-select: none;
  outline: none;
}

body {
  background-color: rgb( 33, 32, 34 );
  overflow: hidden;
}

h1 {
  text-align: center;
  color: #ccc;
  font-family: 'Courier New', Courier, monospace;
  font-size: 1.5rem;
  line-height: 1.5;
  border-bottom: 1px solid #ccc;
  padding: 0 0 1rem 0;
  margin: 2rem auto;
}

button {
  display: block;
  width: 10rem;
  border: 1px solid #ccc;
  background-color: rgb( 96, 96, 97 );
  color: #ccc;
  padding: 1rem;
  border-radius: .25rem;
  margin: 1.5rem auto;
  text-transform: uppercase;
  font-weight: bold;
  cursor: pointer;
}

button:hover,
button:focus,
button:active {
  opacity: .75;
}
```

## INDEX.JS

```
/* ADMOB VARIABLES */

var $app__ad_banner;
var $app__ad_banner_id = 'ca-app-pub-3940256099942544/6300978111' /* test #ID */;

var $app__ad_interstitial;
var $app__ad_interstitial_id = 'ca-app-pub-3940256099942544/1033173712' /* test #ID */;

var $app__ad_delay = 500; /* delay in ms. */

/* BASIC LISTENERS */

document.addEventListener( 'deviceready', function() {

/* show interstitial when loaded */

  document.addEventListener( 'admob.interstitial.load', function() { app__ad_interstitial_show() } );

/* update orientation on rotate (switch banner) */

  window.addEventListener( 'orientationchange', function() { app__orientation( true ) } );

/* initialize banner at start */

  app__ad_banner();

/* update orientation at start (don't switch banner) */

  app__orientation( false );

} );

/* CREATE ADS */

function app__ad_banner() {

  $app__ad_banner = new admob.BannerAd( {

    adUnitId: $app__ad_banner_id

  } );

  $app__ad_banner.show();

}

function app__ad_interstitial() {

  $app__ad_interstitial = new admob.InterstitialAd( {

    adUnitId: $app__ad_interstitial_id

  } );
  
  document.querySelector( 'button' ).innerHTML = 'Loading...';
  $app__ad_interstitial.load();

}

function app__ad_interstitial_show() {

  document.querySelector( 'button' ).innerHTML = 'Interstitial';
  $app__ad_interstitial.show();

}

/* ORIENTATION CHANGE */

function app__orientation( $app__ad_hide ) {

document.getElementById( 'device_orientation' ).innerHTML = screen.orientation.type;

  if ( $app__ad_hide === true ) {

    $app__ad_banner.hide();

    setTimeout( function() {

      app__ad_banner();

    }, $app__ad_delay );

  }

}
```

**Comment by ratson** [comment]
@1n3JgKl9pQ6cUMrW Would you check if `admob-plus-cordova@1.5.0` fixes this?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> @1n3JgKl9pQ6cUMrW Would you check if `admob-plus-cordova@1.5.0` fixes this?

**Yes, I can confirm `1.5.0` fixes the rotation issue.**

---

I tested it on a couple of phones and tablets, using Android 6, 7 and 10.

So my own solution (posted earlier in this thread) is now deprecated.
