### ISSUE TITLE
Cannot find name 'Omit' on install latest version 1.4.0

### ISSUE THREAD

**Issue by Ricardo385** [admob-plus/admob-plus#302]
Hi @ratson i updated from ^1.0.0-alpha.12 to ^1.4.0 yesterday, but when i'm trying to serve or build the app it's take me this error:
`ERROR in node_modules/@admob-plus/ionic/ngx/index.d.ts:4:68 - error TS2304: Cannot find name 'Omit'.
[ng] 4 export declare class BannerAd extends IonicNativePlugin implements Omit<IBannerAd, 'opts'> {
[ng]                                                                      ~~~~
[ng] node_modules/@admob-plus/ionic/ngx/index.d.ts:10:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 10     get adUnitId(): string;
[ng]            ~~~~~~~~
[ng] node_modules/@admob-plus/ionic/ngx/index.d.ts:11:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 11     get id(): number;
[ng]            ~~
[ng] node_modules/@admob-plus/ionic/ngx/index.d.ts:16:74 - error TS2304: Cannot find name 'Omit'.`

My Ionic Info:
`Ionic:

   Ionic CLI                     : 6.13.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.15.5 (/usr/local/bin/node)
   npm        : 6.14.11
   OS         : macOS Big Sur
   Xcode      : Xcode 12.4 Build version 12D4e`

**Comment by ratson** [comment]
@Ricardo385 Make sure your TypeScript >= 3.5.1 or set `skipLibCheck` to `true`.

**Comment by Ricardo385** [comment]
> @Ricardo385 Make sure your TypeScript >= 3.5.1 or set `skipLibCheck` to `true`.

@ratson that's not resolved my problem, if I set `skipLibCheck` to `true` the app compile well but when open it's stay in a white screen after splash screen hide.

**Comment by ratson** [comment]
@Ricardo385 I don't the issue on my setup. I will check if you setup a test repo.
