### ISSUE TITLE
Capacitor "AdMobPlus" Plugin is not implemented on Android.

### ISSUE THREAD

**Issue by AlvinStefanus** [admob-plus/admob-plus#303]
`npx admob-plus doctor`

`npx: installed 293 in 13.823s`
`✔ googleads.g.doubleclick.net`
`❯ CocoaPods`
`  ✖ Google-Mobile-Ads-SDK not found`
`✔ package.json`
`↓ Cordova Android dependencies [SKIPPED]`
`↓ config.xml [SKIPPED]`
`↓ platforms/ios/*.xcodeproj [SKIPPED]`
`↓ plugins/admob-plus-cordova/package.json [SKIPPED]`

**Describe the bug**
Unhandled Rejection (Error):
"AdMobPlus" plugin is not implemented on android.

**To Reproduce**
In App.js:

    import { AdMobPlus, BannerAd } from '@admob-plus/capacitor'

    ...
    constructor(props) {
        super(props);
        Util.initGlobalState(this);

        this.admob = this.admob.bind(this);
    }

    componentDidMount() {
        this.admob();
    }

    async admob() {
        await AdMobPlus.start(); <-- This throws error
        const banner = new BannerAd({
            adUnitId: 'ca-app-pub-3566267745046770/4126753556'
        });
        await banner.show();
    }

**Expected behavior**
AdMobPlus should be available for Android.

**Environment**
Ionic React

```
  AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.19042
      CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
      Memory: 5.42 GB / 15.37 GB
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom     
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Languages:
      Java: 1.8.0_261 - C:\Program Files\Java\jdk1.8.0_261\bin\javac.EXE
    npmPackages:
      typescript: ^3.7.5 => 3.7.5
    Cordova:
      Version: 10.0.0
    Ionic:
      Version: 6.12.4
    AndroidManifest.xml:
      Version: -
```

**Additional context**

`npx cap doctor` result:

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
```

**Comment by ratson** [comment]
@AlvinStefanus Cannot recreate the issue. Would you setup a test repo for me to check?

**Comment by ratson** [comment]
Close as not enough information to proceed.
