### ISSUE TITLE
IOS Banner ads cannot be clicked.

### ISSUE THREAD

**Issue by yigit-serin** [admob-plus/admob-plus#306]
**Describe the bug**
IOS Banner ads cannot be clicked.
When you try to click ads, nothing happens.

**To Reproduce**
1.const banner = new admob.BannerAd({
adUnitId: 123
})
2.Run in IOS simulator: Iphone 8 plus, IOS 14
3.banner.show();
4.Click banner, nothing opened.

**Expected behavior**
Ad url must be opened.

**Environment**
```
cordova: 10.0.0
cordova-ios: 6.2.0
cordova-android: 9.1.0
admob-plus-cordova: 1.5.2
```

**Comment by Sirioxstar** [comment]
I have the same problem. how did you solve?
