### ISSUE TITLE
Display Interstitial with Onclick event

### ISSUE THREAD

**Issue by yanbaha** [admob-plus/admob-plus#31]
I want to display the interstitial Ad with an Onclick event.
I did it with Admob free. but Admob plus I can't:
document.addEventListener('deviceready', () => {
  admob.interstitial.load({
    id: {
      // replace with your ad unit IDs
      android: 'ca-app-pub-xxx/yyy',
      ios: 'ca-app-pub-xxx/zzz',
    },
  }).then(() => admob.interstitial.show())
}, false)

any solution?
thanks

**Comment by yanbaha** [comment]
I found the solution:


document.addEventListener('deviceready', () => {
  admob.interstitial.load({
    id: {
      // replace with your ad unit IDs
      android: 'ca-app-pub-1266469958489664/1154250177',
      ios: 'ca-app-pub-xxx/zzz',
    },
  })
}, false)

document.addEventListener('admob.interstitial.load', () => {
  // handle event
   document.getElementById('showAd').onclick = function() {
      admob.interstitial.show()
    }

})

but the problem is that the Ad is displayed once as it is linked to Deviceready.

any solution to load and display the Ad on each new click??

**Comment by ratson** [comment]
Doable with latest API.

**Comment by DhruvGajera9022** [comment]
loda
