### ISSUE TITLE
Plugin version 0.0.0 - Error on iOs 

### ISSUE THREAD

**Issue by cagb80** [admob-plus/admob-plus#32]
I getting an error when I try to add the iOS platform to my project.
Failed to install 'cordova-admob-plus': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'

The current version of the admob-plus plugin is: 0.0.0 
`> cordova plugin ls
cordova-admob-plus 0.0.0 "@admob-plus/cordova"`

**Comment by ratson** [comment]
Would you run `npx admob-plus info --clipboard` to provide more information? Also, you may try out the latest version first to see if your problem is fixed.
