### ISSUE TITLE
Android hardware back button closes app after banner ad display

### ISSUE THREAD

**Issue by yigit-serin** [admob-plus/admob-plus#326]
**Describe the bug**
When I opened a new page and after that called banner.show() screen makes a lightning effect.
After that banner ad shown.
When I clicked header back button and I can go back without any problem.
When I clicked hardware back button, app closed.

**To Reproduce**
1. Go to a new page
2. this.banner = new admob.BannerAd({
          adUnitId: 123,
          size: 0
        });
2. await this.banner.show();
3. Click hardware back button.
4. App closed.

**Expected behavior**
Go back to the previous page.

**Screenshots**

**Environment**

```
AdMob Plus Environment Info:
    npmPackages:
      admob-plus-cordova: ^1.7.0 => 1.8.2 
      cordova-android: ^9.0.0 => 9.1.0 
      cordova-ios: ^6.0.1 => 6.2.0 
      typescript: ~2.6.2 => 2.6.2 
    npmGlobalPackages:
      cordova: 10.0.0
    Cordova:
      Version: 10.0.0
      Plugins:
        cordova-plugin-device: ^2.0.3
        cordova-plugin-app-version: ^0.1.9
        cordova-plugin-statusbar: ^2.4.3
        cordova-plugin-splashscreen: ^5.0.3
        admob-plus-cordova: ^1.7.0
       
    Ionic:
      Version: 6.12.3```

**Comment by ratson** [comment]
@yigit-serin Looks like you have installed old version of the plugin `admob-plus-cordova: ^1.7.0 => 1.8.2 `.

**Comment by yigit-serin** [comment]
I updated to 1.9.0, the problem continues.

**Comment by ratson** [comment]
@yigit-serin I tried your code without issue, would you setup a test repo for me to check?

**Comment by yigit-serin** [comment]
@ratson You can check out on this repo.
https://github.com/yigit-serin/lightningt

You can see the problems on emulator.
1. Lightning effect
2. Hardware back button problem

**Comment by zeezonez** [comment]
I having the same problem, after several hours investigation. I finally found the root of this problem.

Because when admob add a banner view, it (bannerview) takes a focus from parent view.
That's why any button events won't be fired. 

So, I tried to get the focus back to parent view, and It's works. 


Here is my temporary solution, 

in app module 's banner.java,  search for

> public void show(ExecuteContext ctx) {
>         ...
>         ctx.success();
>     }

then add a below statement, to before ctx.success().

> getParentView(getWebView()).requestFocus();

Finallly, your code should look like

> public void show(ExecuteContext ctx) {
>         ...
>         getParentView(getWebView()).requestFocus();
>         ctx.success();
>     }
> 

Note :  But because, I'm not good in java, so please try this as your own risk. 
Or just wait for the official update..

Have a good day all..

**Comment by ratson** [comment]
@zeezonez Would you share the exception you seen before crash? I am wondering why it is happening.

**Comment by zeezonez** [comment]
@ratson 

There is no crash, just the back button (hardware) registered event not working (I think all other hardware buttons too) 

document.addEventListener("backbutton", yourCallbackFunction, false);

Because the focus taken by admob banner view when it created.

**Comment by zeezonez** [comment]
@ratson 

More information.

After the bannerads view added and shown (it take focus), then hardware buttons event will not fire.
If user touch/tap/interact at app webview a few times, the app takes the focus back and the buttons works correctly.

**Comment by markenapps** [comment]
Looks like you have to focus an input field first to get the back-button working again.

**Comment by zeezonez** [comment]
@ratson 

I updated and tested on my two projects, and I can confirm that your code works like a charm.

Thank you so much... ^^

**Comment by markenapps** [comment]
I can confirm this too. Thanks for your great work!

**Comment by ratson** [comment]
@zeezonez @markenapps Thanks for confirming that.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Somehow, when using the app in `fullscreen` (set by `config.xml`) this error still occurs.

The code where is referred to, is not available in the latest 1.x stable release any longer (which I uses), so I can't fixed it myself.
