### ISSUE TITLE
Ads don't appear

### ISSUE THREAD

**Issue by diaxotora** [admob-plus/admob-plus#338]
Hi,
I used the plugin, it works very well with the test AdUnitIds, the ads appear correctly, but when I include the AdUnitIds from my admob account the block does not appear and the loadfail event is triggered, here is my code :
async function onDeviceReady() {
    let banner;
    let interstitial;
    await admob.start();
    banner = new admob.BannerAd({
      adUnitId: "xxxxxx"
    });
    interstitial = new admob.InterstitialAd({
      adUnitId: "xxxxxx"
    });
    await interstitial.load();
    await interstitial.show();
    await banner.show();
} 
function onLoad() {
    document.addEventListener("deviceready", onDeviceReady, false);
}
and i have no error in my console when i build for android
thank in advance for your help

**Comment by diaxotora** [comment]
Hello,
the code for the banner gives no error but the interstitial code gives the following error:
Uncaught (in promise) {
  "Code": 3,
  "Message": "No ad config.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null",
  "Response Info": {
    "Response ID": "null",
    "Mediation Adapter Class Name": "",
    "Adapter Responses": []
  }
}
please help me

**Comment by ratson** [comment]
Read https://admob-plus.github.io/docs/troubleshooting#why-are-ads-not-showing
