### ISSUE TITLE
Android Studio not able to find play-services-base

### ISSUE THREAD

**Issue by bartboersma** [admob-plus/admob-plus#339]
Hi,

I know this is not an issue with Admob, but most likely you know the answer so I am trying anyway. When I am following the Capacitor installation guide and build the project in Android Studio I am getting:

> Execution failed for task ':capacitor-cordova-android-plugins:generateDebugRFile'.
> Could not resolve all files for configuration ':capacitor-cordova-android-plugins:debugCompileClasspath'.
   > Could not find com.google.android.gms:play-services-base:20.1.0.

Android studio version is 4.2
Capacitor version is 3.0.0-rc.2
In SDK manager of Android Studio I've updated all SDK Tools. Tools installed: Android SDK Build-Tools 31-rc3, Android Emulator, Android SDK Platform-Tools, Google Play services, Intel x86 Emulator Accelator (HAXM Installer)

When changing the version into 20.+ I see it tries to read versions from:
 > Searched in the following locations:
 > - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-base/maven-metadata.xml
 > - https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml

In those URL's I see the latest version is 17.6.0. So, if I change it to 17.6.0 in capacitor.build.gradle and build.gradle it does work. 

Any idea what I need to do to make it work with version 20.1.0?

**Comment by skidrow88** [comment]
Hello !

How did you resolve the issue ?
