### ISSUE TITLE
Ad fraud 

### ISSUE THREAD

**Issue by vietnux** [admob-plus/admob-plus#341]
my app android often get error: "Ad fraud" and app remove from Play.
i fixed and upload new version. It run only any day and Play resend for my a email alert: Ad Fraud, after Play removed my app.
Current! I fixed and app is release. But i dont know it will be remove

>
>About the Ad Fraud policy
>--
>Ad fraud is strictly prohibited. Ad interactions generated for the purpose of tricking an ad network into believing traffic is from >authentic user interest is ad fraud, which is a form of invalid traffic. Ad fraud may be the byproduct of developers implementing >ads in disallowed ways, such as showing hidden ads, automatically clicking ads, altering or modifying information and otherwise >leveraging non-human actions (spiders, bots, etc.) or human activity designed to produce invalid ad traffic. Invalid traffic and ad >fraud is harmful to advertisers, developers, and users, and leads to long-term loss of trust in the mobile Ads ecosystem.

This is my app: [https://play.google.com/store/apps/details?id=com.amlich.labanphongthuy](https://play.google.com/store/apps/details?id=com.amlich.labanphongthuy)

I not spam!
If anyone has encountered and fixed it or found the cause, please let me know! 

Thank!

**Comment by ratson** [comment]
See https://admob-plus.github.io/docs/troubleshooting#why-my-app-is-removed-from-google-play

**Comment by reinaldoborin** [comment]
I have the same issue here, over 3 months.

**Comment by vietnux** [comment]
> I have the same issue here, over 3 months.

you update this plugin or update sdk of google is fixed
