### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: InterstitialAd.getPlugin(...) is not a constructor

### ISSUE THREAD

**Issue by gpofblank** [admob-plus/admob-plus#345]
Hello guys,

I've been using this plugin for 3 of my apps.
Just developed my 4th app and noticed that the plugin has been completely overwritten...
 
Followed the "new" documentation and got to this point:

"ERROR Error: Uncaught (in promise): TypeError: InterstitialAd.getPlugin(...) is not a constructor"

Looking at the code, this must be it -> index.js:
 constructor(opts: { adUnitId: string }) {
    super()

    this._objectInstance = new (InterstitialAd.getPlugin())(opts)
  }

---

That's what I get in the (browser) console right when the ad is supposed to come up.
When I try to compile my app for android, I get 40 errors related to this:

[cordova]         RewardedInterstitialAd.load(ctx.getActivity(), adUnitId, adRequest, new RewardedInterstitialAdLoadCallback() {
[cordova]         ^
[cordova]   symbol:   variable RewardedInterstitialAd
[cordova]   location: class RewardedInterstitial
[cordova] Note: Some input files use or override a deprecated API.
[cordova] Note: Recompile with -Xlint:deprecation for details.
[cordova] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[cordova] 40 errors

---

Tried importing AdMob from:
 import {AdMob} from '@admob-plus/ionic/ngx';

and from:

import {AdMob} from '@admob-plus/ionic';

but that didn't help...

The old version has been working pretty decently. I don't know why you needed to re-write it but anyways.
I'd appreciate it if you could help me fix this issue.

Environment:
$ ionic info
Ionic:

   Ionic CLI                     : 6.11.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 0.1102.13
   @angular-devkit/schematics    : 11.2.13
   @angular/cli                  : 11.2.13
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 7 other plugins)

ionic cordova plugin list
> cordova plugin ls
admob-plus-cordova 0.0.0 "admob-plus-cordova"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v12.13.0 (/usr/local/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina
   Xcode  : Xcode 11.3.1 Build version 11C505

---

**Comment by gpofblank** [comment]
Just for the protocol...
This is not helping too.

"ionic-angular user needs to update typescript to a recent version, or config "skipLibCheck": true in tsconfig.json to avoid type errors."

**Comment by gpofblank** [comment]
Wonder if that has anything to do with the issue ->   "extends": "@tsconfig/node10/tsconfig.json",
I do not have @tsconfig in my project files and is not a valid package to begin with.

**Comment by gpofblank** [comment]
Or may be this... -> npm ERR! Could not install from "../../internal/rollup-config" as it does not contain a package.json file.

**Comment by gpofblank** [comment]
Turned out the whole "internal" dir was not shipped with the plugin. Even though I downloaded it separately and put it where it needed to be, the issue still remains.

**Comment by ratson** [comment]
@gpofblank `internal/` holds build dependencies, which you don't need to run the app.
It would be helpful if you could prepare a test repo.

**Comment by itsLucario** [comment]
I'm also facing similar issue. The app is crashing and stuck with White Screen.

**Comment by ratson** [comment]
Close as no test repo.
