### ISSUE TITLE
'No ad config.' Presenting live ads in Android - Reopening

### ISSUE THREAD

**Issue by richwebapps** [admob-plus/admob-plus#349]
Re-opening since the issue still happens for several of us.  Banner and Interstitial ads work fine in iOS and also on the Android emulator. Ads also display on Android devices when using testDeviceIds configRequest. But live ads for Androids always produce this error.

Uncaught (in promise) {
  "Code": 3,
  "Message": "No ad config.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null",
  "Response Info": {
    "Response ID": "null",
    "Mediation Adapter Class Name": "",
    "Adapter Responses": []
  }
}

I also tried creating net-new ad units in Ad Mob and still no luck. The "No Fill" error doesn't make sense since it works fine on iOS and I don't have restrictions on ad targeting. I can also see ads when I switch to another plugin.

**Comment by richwebapps** [comment]
For others experiencing this, I tried building a production APK and deployed it manually and it finally shows ads. It seems the debug build has this issue. I still think there's something in this plugin that causes the error since other plugins don't seem to have this issue.

**Comment by ratson** [comment]
@richwebapps Did you run `npx admob-plus doctor`. It looks like it is a build cache problem.

**Comment by richwebapps** [comment]
Hi @ratson . Yes I did. Everything looks good. Seems to fail only in the debug build.

**Comment by Be4t5** [comment]
HI, I have the same problem. I can't test the ads implementation if I can't run it in debug mode. Any solution?

**Comment by ThomasC31x** [comment]
Hi, same problem

**Comment by ratson** [comment]
@richwebapps @Be4t5 @ThomasC31x I will check if there is a test repo.

**Comment by ratson** [comment]
See https://admob-plus.github.io/docs/troubleshooting/#why-are-ads-not-showing
Close as no further information.
