### ISSUE TITLE
Get rewared event in Ionic Capacitor

### ISSUE THREAD

**Issue by kisimediaDE** [admob-plus/admob-plus#350]
**Describe the bug**
I tried to get a callback if the reward was successfully and what item was rewared. 
For this I tried different ways like: 
- AdMobPlus.addEventListener(...) -> But here I get the error message that property 'addEventListener' does not exist on type 'AdMobPlusPlugin'
- Then I tried it with rewared.reward -> But here I get the error message that property 'reward' does not exist on type 'RewardedAd'
- I also tried document.addEventListener('admob.rewarded.dismiss' ...) -> But it's never reached

**Expected behavior**
An easy and quick way in Capacitor to handle rewards.

**Environment**

```
  AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.2.3
      CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
      Memory: 6.06 GB / 64.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.5 - /usr/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    Languages:
      Java: 15.0.2 - /usr/local/opt/openjdk/bin/javac
    npmPackages:
      typescript: ~4.0.2 => 4.0.7 
    npmGlobalPackages:
      cordova: 10.0.0
    Cordova:
      Version: 10.0.0
    Ionic:
      Version: 6.16.1
    AndroidManifest.xml:
      Version: -
```

**Comment by kisimediaDE** [comment]
Hey, I created a small test app to show everything I tried. 
During creating this small test app I also tried to run it on android. And there it's working. 
Only on iOS devices I didn't receive any feedback from the RewaredAd.

Link to the repo: [https://github.com/kisimediaDE/AdsTest](https://github.com/kisimediaDE/AdsTest)

Called init in: `src/app/app.component.ts` _Line 12_
Added button to open the ad in `src/app/home/home.page.html` _Line 17_

Added service for the whole ads topic here: `src/app/_services/ads.service.ts`

- **CODE 1** and **CODE 2** isn't working because of errors that you can find in the comments. _(Line 52-58 and Line 35-39)_
- **CODE 3**: Here I tried some document.addEventListeners but none of them are fired. _(Line 60-84)_
- **CODE 4**: This two eventListeners are working on android but not on iOS _(Line 86-95)_

I hope this help you finding the problem. If there are any question or stuff I should try please tell me :-)

**Comment by kisimediaDE** [comment]
Many thanks for your quick help! 👍 
Tested the new version 1.10.1 on Android and iOS with AdMobPlus.addListener

On iOS now everything is working like it should work 🥳 

But on Android the AdMobPlus.addListener is not fired. 
When I add document.addEventListener again then Android is working.

**Comment by gilzonme** [comment]
This helps a lot. But can anyone let me know how to dismiss the ad programmatically after it is completed. Is it possible?

**Comment by kisimediaDE** [comment]
Hey from what I found only about the SDK from Google is that this is not possible and no wanted feature from Google. So I don’t think, that this plug-in can support it.

Source:
- https://groups.google.com/g/google-admob-ads-sdk/c/o7gdbR02p2Y
- https://stackoverflow.com/questions/20139690/how-to-close-admob-inersitial-after-click-on-it
