### ISSUE TITLE
Cordova app not opening 2nd time after closing it.

### ISSUE THREAD

**Issue by deadlyjack** [admob-plus/admob-plus#353]
In debug console below errors are shown:

`
cordova.js:1237 deviceready has not fired after 5 seconds.
`
`
cordova.js:1230 Channel not fired: onFileSystemPathsReady
`

This happens after calling `admob.start()` method. Without `admob` the app works perfectly.

Here is snippet/code:

```js
  (async () => {
    await admob.start();
    admob.BannerAd.config({
      backgroundColor: '#212028',
    });
    window.ad = new admob.BannerAd({
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
      position: 'bottom',
    });

    ad.show();
  })();
```

I'm using webpack, babel for compile src code.

Even after closing app, these webview kept showing. I'm not sure whats wrong.

![Screenshot_20210527_140057](https://user-images.githubusercontent.com/38699939/119793323-1a736580-bef4-11eb-8443-a475b51c2327.png)

**Comment by ratson** [comment]
@deadlyjack You should `await` the `config()` and `show()`.
Is the webview means you are running the app in background?

**Comment by deadlyjack** [comment]
Thanks for the help. Turned out missing `await` before the `config()` was causing the issue. Silly me!
About those webviews, they appear in chrome remote inspect, even after the app is closed. App doesn't run in background.
However my problem is solved, you can close this issue.

**Comment by deadlyjack** [comment]
Thanks for the suggestion, but it couldn't fix the issue. 
About those webviews, they appear in chrome remote inspect, even after the app is closed. App doesn't run in background.

The project where I'm trying to use this plugin is open source. [The app](https://github.com/foxdebug/wallpaper-FXDBG.git)

**Comment by ratson** [comment]
@deadlyjack I am not able to build the project as `src/plugins/cordova-plugin-wallpaper` and `secrets.json` are missing.

**Comment by deadlyjack** [comment]
Hi, sorry for the inconvenience, I've fixed the repo. You can try gain.

**Comment by deadlyjack** [comment]
I updated the plugin and tried again and the issue persistent. (current version 1.13.1)

**Comment by RodriSanchez1** [comment]
Hi! I have the same problem in the current version. https://github.com/admob-plus/admob-plus/issues/304#issuecomment-818648744 . I call the navigator.app.exitApp() , and after that resume the app, i get  
`cordova.js:1237 deviceready has not fired after 5 seconds.
cordova.js:1230 Channel not fired: onFileSystemPathsRead`
and crash all my app. The only solution its close the entire app from the three buttos on the bottom of the device. After that, open the app again an all is working. 
![image](https://user-images.githubusercontent.com/80465873/170149176-1409efac-1ef4-47a7-bd5b-ee66a6ad8bfd.png)
That is how i implemented the plugin, the prepareAds function its  called from deviceReady listener

**Comment by RodriSanchez1** [comment]
@ratson i need you help please! I have two weeks stuck with this!
