### ISSUE TITLE
App Open Ad ( Error )

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#355]
I tried the open ad sample app code
https://github.com/admob-plus/admob-plus/blob/master/examples/cordova/www/js/index.js

`plugin version @1.12.4`
`cordova @10.0.0`
`cordova-android @^9.0.0`
`cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713`

### got this error

<img src="https://user-images.githubusercontent.com/78555833/119865751-31db3e80-bf46-11eb-97bd-0aaa70ca024c.jpg" width="500" />

**Comment by ratson** [comment]
@EMI-INDO You are trying out too early. I have just finished the documentation and released it.
Let me know if you could get it working.
