### ISSUE TITLE
Open ad - opens after modal or interstitial ad

### ISSUE THREAD

**Issue by EYALIN** [admob-plus/admob-plus#357]
**Describe the bug**
after each modal I open, I get the open ad, and also after the interstitial ad closed, I also get the open ad.

**To Reproduce**
1. create a new open ad when the app loads
2.  open modal/interstitial ad 

**Expected behavior**
open ad not open

**Environment**
Samsung S8

**Comment by ratson** [comment]
@EYALIN Re-designed the API to allow custom `load()` and `show()`, see https://admob-plus.github.io/docs/cordova/ads/app-open

**Comment by EYALIN** [comment]
@ratson thanks a lot! will test it today

**Comment by EYALIN** [comment]
@ratson you can close the ticket. all works. thanks!!
