### ISSUE TITLE
iOS App Open error Simultaneous accesses to  [address], but modification requires exclusive access

### ISSUE THREAD

**Issue by Sayene** [admob-plus/admob-plus#359]
**Describe the bug**
Code set up to show AppOpenAd when app resumes after it was sent to background (restoreFromBackground). Putting app to background and back several times causes app to crash with error: **Simultaneous accesses to [address], but modification requires exclusive access**, 
in https://github.com/admob-plus/admob-plus/blob/76679d003ccf02f95511a440c35e6c976e2f5cc7/packages/cordova/src/ios/AMBAdBase.swift#L31

**To Reproduce**
1. create AppOpenAd on 'resume' event:
```js
let appOpenAdd
document.addEventListener("resume", () => {
  if(restoreFromBackground) {
    appOpenAdd =   new admob.AppOpenAd({
      adUnitId: 'ca-app-pub-3940256099942544/5662855259'
    })
  }
}, false);
```
2.  slide app to background and restore
3.  first appOpenAd is shown on 2nd resume (why not on first?), dismiss it 'Continue to app..'
4. repeat slide to background, restore, dismiss 2-4 times to have app crash 

**Expected behavior**
no crash; appOpenAd is shown on first  call, and all consequent calls.

**Environment**
```
OS: macOS Big Sur 11.3.1
CocoaPods: 1.10.1
Xcode: 12.5/12E262
iOS 14.5 (emulator) 
admob-plus-cordova: 1.13.1 => 1.13.1
cordova: ^10.0.0 => 10.0.0 
cordova-ios: ^6.2.0 => 6.2.0 
```

**Comment by ratson** [comment]
@Sayene Please refer to updated https://admob-plus.github.io/docs/cordova/ads/app-open
If you want to display the ads on first call, you could do `ad.load().then(() => ad.show())`.
