### ISSUE TITLE
error building after admob-plus installation

### ISSUE THREAD

**Issue by chromotoxin** [admob-plus/admob-plus#36]
### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
      Memory: 2.01 GB / 7.93 GB
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

cordova: 8.1.2 (cordova-lib@8.1.1)
ionic: 4.3.1
cordova plugins: {
  "cordova-plugin-whitelist": "1.3.3",
  "cordova-plugin-statusbar": "2.4.2",
  "cordova-plugin-device": "2.0.2",
  "cordova-plugin-splashscreen": "5.0.2",
  "cordova-plugin-ionic-webview": "^2.0.0",
  "cordova-plugin-ionic-keyboard": "^2.0.5",
  "cordova-plugin-advanced-http": "^2.0.1",
  "cordova-plugin-camera": "^4.0.3",
  "cordova-plugin-file": "^6.0.1",
  "cordova-plugin-file-transfer": "^1.7.1",
  "cordova-plugin-filepath": "^1.4.2",
  "com-badrit-base64": "0.2.0",
  "cordova-plugin-firebase": "2.0.5",
  "cordova-android-support-gradle-release": "^1.4.5",
  "cordova-plugin-inappbrowser": "3.0.0",
  "cordova-sqlite-storage": "2.5.0",
  "cordova-plugin-network-information": "2.0.1",
  "mx.ferreyra.callnumber": "0.0.2",
  "call-number": "1.0.1",
  "cordova-admob-plus": "0.8.0"
}

### Steps to Reproduce

(Write your steps here:)

1. everything works fine
2. installed plugin
3. ionic cordova build android

### Expected Behavior

build successful...

### Actual Behavior

:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

39 actionable tasks: 5 executed, 34 up-to-date
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by n-clark** [comment]
Try using cordova-plugin-enable-multidex

**Comment by chromotoxin** [comment]
hello n-clark thanks for your reply.
I tried:

PS C:\xampp2\htdocs\affp\ionic_client_test\app> cordova plugin add --save  cordova-plugin-enable-multidex
Installing "cordova-plugin-enable-multidex" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-enable-multidex" for browser
Adding cordova-plugin-enable-multidex to package.json
Saved plugin info for "cordova-plugin-enable-multidex" to config.xml

And now it Builds, but as I run the app on the emulator it crashes immediately (and I cannot even device debug it).
I tried to "ionic cordova run browser" and it runs, so I guess, considering that the <plugin name="cordova-plugin-enable-multidex" spec="0.1.3" /> is there, the problem is still with the admob-plus plugin.

Any other suggestion?
thank you

**Comment by ratson** [comment]
@chromotoxin Would you run `npx admob-plus info --clipboard` to provide more information?

**Comment by chromotoxin** [comment]
Hello @ratson , I'm sorry I'm replying you so late, I gave up from installing your plugin for a little, I wanted to reach a milestone.

Anyway I fully cleaned the package-lock.json and added this:

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '27.0.0'
            }
        }
    }
}
```

at the end of the build.gradle file in the platforms/android/app/build.gradle to solve a conflict.

Today i reinstalled the plugin, the release built correctly and the banner now is showing clearly in the emulated app.
So my wrong, this was not an Issue.
Thanks for you help and patience ^^'

**Comment by ratson** [comment]
@chromotoxin Good to hear that 😄
