### ISSUE TITLE
AdMob default exported variable is null in Android

### ISSUE THREAD

**Issue by ShivamJoker** [admob-plus/admob-plus#360]
**Describe the bug**
In android while running the app the default exported variable becomes null.

**To Reproduce**

Follow the instructions given in the docs website.
I am using yarn

Here is the repo if you wanna look - https://github.com/ShivamJoker/SQL-Play/blob/22-fix/changeto-admob-plus/src/component/App.tsx#L137

**Expected behavior**
It should work

**Screenshots**
![image](https://user-images.githubusercontent.com/23727670/120196008-fa69dc00-c23c-11eb-90ed-9072c991ee5d.png)

**Environment**
```
AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 111.84 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.2.0 - ~/.nvm/versions/node/v15.2.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.2.0/bin/yarn
      npm: 7.5.2 - ~/.nvm/versions/node/v15.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.5 - /usr/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Neovim
```

**Additional context**
I have tried cleaning the whole project and installing multiple times but no luck.

**Comment by ShivamJoker** [comment]
Also the getting this - Package name 'admob.plus.rn' used in: :@admob-plus_react-native, :admob-plus_react-native.

**Comment by ShivamJoker** [comment]
@rayros any help ? I tried running the android example from the repo the app crashes while opening it.

**Comment by ShivamJoker** [comment]
Closing as it seems to be fixed in the new update

**Comment by ShivamJoker** [comment]
@ratson the warning is still there `Duplicate content roots detected: `

**Comment by ShivamJoker** [comment]
@ratson and also the release variant of app is throwing error 
![image](https://user-images.githubusercontent.com/23727670/120899337-dcd9af80-c64c-11eb-951a-dec31d673676.png)

**Comment by ratson** [comment]
@ShivamJoker `new InterstitialAd()` should be called after `AdMob.start()`.

**Comment by ShivamJoker** [comment]
> @ShivamJoker `new InterstitialAd()` should be called after `AdMob.start()`.

It's still not working I already tried that 
```js
  const setupAdmob = async () => {
    try {
      await AdMob.start();
      const interstitial = new InterstitialAd({
        adUnitId: getInterstitialId(),
      });
      await interstitial.load();
      await interstitial.show();
    } catch (err) {
      Alert.alert('Error in ad', JSON.stringify(err));
    }
  };
  ```
  
  
<img width="401" alt="image" src="https://user-images.githubusercontent.com/23727670/120915284-945bd980-c6c0-11eb-9a0e-fff4799884cc.png">

**Comment by ShivamJoker** [comment]
Any updates @ratson ?

**Comment by ShivamJoker** [comment]
@ratson after updating to the latest release I get "ad cls is not supported: o"

<img width="350" alt="image" src="https://user-images.githubusercontent.com/23727670/122873089-f8cc9900-d34e-11eb-9552-1aa4a8562d03.png">

**Comment by ShivamJoker** [comment]
@ratson thanks for the fix it seems to be working fine in android
But now iOS is giving me `Ad not found error`

<img width='350' src='https://user-images.githubusercontent.com/23727670/123534255-791d4080-d739-11eb-88f8-480ec490b4f4.png'/>

**Comment by ratson** [comment]
@ShivamJoker This should be fixed with `@admob-plus/react-native@1.10.2`.

**Comment by ShivamJoker** [comment]
@ratson no :( not yet it gives `[Error: Ad is not loaded: 1]`

**Comment by ShivamJoker** [comment]
```
  /**
   * load ad if it's not already loaded
   */
  const loadAd = async () => {
    if (await interstitial.isLoaded()) return;
    return await interstitial.load();
  };

  const showAd = async () => {
    if (!shouldShowAd()) {
      return;
    }
    console.log('time to show ad');
    // the ad load function isnt working
    await loadAd();
    //needing to ad this
    await interstitial.load();
    await interstitial.show();
    await loadAd();
  };
```

**Comment by ShivamJoker** [comment]
@ratson also the iOS version gets crashed on reloading the app giving when the setup function is ran
```
EXC_BAD_ACCESS: Exception 1, Code 2878976080, Subcode 8 >
Attempted to dereference garbage pointer 0x4f08ab99b050.
```
