### ISSUE TITLE
Ad type is not returned in admob.ad.dismiss

### ISSUE THREAD

**Issue by EYALIN** [admob-plus/admob-plus#368]
**Describe the bug**
when admob.ad.dismiss fired after app open dismissed, type is not returned 

**To Reproduce**
1. show app open ad
2. dismiss the ad

**Expected behavior**
ad type returned in admob.ad.dismiss (event.ad.opts.type needs to be equal to  'app-open')

**Environment**
android 9 - S8
"admob-plus-cordova": "1.15.0"

```

```

**Comment by ratson** [comment]
@EYALIN The `type` option has been removed, was used to create ad on the native side.
Please use `evt.ad instanceof admob.AppOpenAd` as documented in https://admob-plus.github.io/docs/cordova/ads/app-open

**Comment by EYALIN** [comment]
@ratson works. thanks
