### ISSUE TITLE
Native ad load gets "failed cannot find viewProvider: default"

### ISSUE THREAD

**Issue by EYALIN** [admob-plus/admob-plus#369]
**Describe the bug**
trying to load native ad (as in the example) and gets "failed cannot find viewProvider: default"

**To Reproduce**
1. load native ad after the ready event

**Expected behavior**
show native ad

**Environment**
"admob-plus-cordova": "^1.15.0"
S8 Samsung - Andoid 9

**Comment by ratson** [comment]
@EYALIN Do you have `admob-plus-cordova-native` plugin added?

**Comment by EYALIN** [comment]
@ratson thank you for the fast response. no, didn't add it. 
I will close the ticket and will try to implement it later today.

**Comment by EYALIN** [comment]
missing implementation of admob-plus-cordova-native
