### ISSUE TITLE
Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=8.1.2

### ISSUE THREAD

**Issue by lucaele** [admob-plus/admob-plus#38]
**Adding the plugin with CLI:**
cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-........... --variable APP_ID_IOS=ca-app-pub-.................

**This is the result:**
Installing "cordova-admob-plus" for android
Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=8.1.2
Skipping 'cordova-admob-plus' for android
Installing "cordova-admob-plus" for ios
Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=8.1.2
Skipping 'cordova-admob-plus' for ios

**Cordova -v**
8.1.2 (cordova-lib@8.1.1)

**Comment by B3L7** [comment]
Can confirm. I am having the same issue. Tried updating cordova and removing the reading android. No resolution.

**Comment by ipsjolly** [comment]
I am also having the same issue already updated Cordova and Cordova lib
$ npm update -g cordova
$ npm i cordova-lib

But still facing this issue

> cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-xxx
~xxx --save
Installing "cordova-admob-plus" for android
**Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed ve
rsion requirement: >=8.1.2**
Skipping 'cordova-admob-plus' for android
Adding cordova-admob-plus to package.json
Saved plugin info for "cordova-admob-plus" to config.xml
Android Studio project detected
