### ISSUE TITLE
Separate adUnitId for ios and android

### ISSUE THREAD

**Issue by igorbt** [admob-plus/admob-plus#385]
I'm trying to upgrade from 0.x to 1.x and I didn't find in documentation or in issues how to specify separate adUnitId for ios and android. In 0.x it was::
```
admob.interstitial.load({
    id: {
      // replace with your ad unit IDs
      android: 'ca-app-pub-xxx/yyy',
      ios: 'ca-app-pub-xxx/zzz',
    },
  })
  ```
  In 1.x it's just:
  ```
new admob.InterstitialAd({
    adUnitId: 'ca-app-pub-xxx/yyy',
  })
```
Should I detect myself the OS and pass the correct adUnitId value?

**Comment by krunalsk007** [comment]
As Nijil Nair suggested use the[ Cordova Device Plugin](https://cordova.apache.org/docs/en/3.0.0/cordova/device/device.html) . If you need help adding the plugin see Meteor Cordova . Once the plugin is properly installed you can use var devicePlatform = device.platform; which will return one of the following based on the device:

"Android"
"BlackBerry"
"iOS"
"WinCE"

**Comment by krunalsk007** [comment]
use the[ Cordova Device Plugin](https://cordova.apache.org/docs/en/3.0.0/cordova/device/device.html) . Once the plugin is properly installed you can use var devicePlatform = device.platform; which will return one of the following based on the device:

"Android"
"BlackBerry"
"iOS"
"WinCE"
ads logic
var devicePlatform = device.platform;
 let adUnitId = (devicePlatform =='Android') ?'android id ':'ios id;

**Comment by igorbt** [comment]
OK, thanks!
