### ISSUE TITLE
Ionic App 5,  Plugin AdMob Plus: Error 3 - No Ad Config

### ISSUE THREAD

**Issue by GhoshWorld** [admob-plus/admob-plus#386]
Hello everyone,
I am using admob-plus plugin in my Ionic app 5 for displaying ads. The test ads not work in the debug versions. How can i solved it? any help please
Thank you

Error Msg =>  
ERROR Error: Uncaught (in promise): {
  "Code": 3,
  "Message": "No ad config.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null",
  "Response Info": {
    "Response ID": "null",
    "Mediation Adapter Class Name": "",
    "Adapter Responses": []
  }
}

**Comment by ratson** [comment]
@GhoshWorld See https://admob-plus.github.io/docs/troubleshooting#why-are-ads-not-showing

**Comment by nosTa1337** [comment]
@ratson I do not see any information helpful on the linked page. Can you further clarifiy on how to test ads on debug versions? Or is that not possible right now?
