### ISSUE TITLE
Can't install plugin 

### ISSUE THREAD

**Issue by naveed-ahmad** [admob-plus/admob-plus#39]
### Is this a bug report?

Yes, its a bug

### Environment
AdMob Plus Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 318.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 14, 15, 16, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.2, 26.0.2, 27.0.1, 27.0.3
        System Images: android-16 | ARM EABI v7a, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      cordova-admob-plus: ^0.9.3 => 0.9.3
      cordova-android: ^7.1.2 => 7.1.2
      cordova-browser: ^5.0.4 => 5.0.4
      cordova-plugin-crypt-file-ng: git+https://github.com/qhng/cordova-plugin-crypt-file.git => 0.1.0
      cordova-plugin-google-analytics: ^1.8.6 => 1.8.6
    npmGlobalPackages:
      cordova: 8.1.2

AndroidManifest.xml: missing <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" ... />

### Steps to Reproduce

1. cordova plugin add cordova-admob-plus@0.9.3 --variable APP_ID_ANDROID=ca-app-pub-xxxxxx~xxxx

this command will throw `Failed to install 'cordova-admob-plus': TypeError: Path must be a string. Received undefined` exception.

### Expected Behavior
Plugin should install successfully. 
 
### Actual Behavior
Failed to install 'cordova-admob-plus': TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at ConfigKeeper_get [as get] (/Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigKeeper.js:45:26)
    at /Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:346:51
    at Array.forEach (<anonymous>)
    at is_conflicting (/Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:339:17)
    at PlatformMunger.add_plugin_changes (/Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:132:33)
    at /Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:123:29
    at _fulfilled (/Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Volumes/UBUNTU/development/games/pac_rat/platforms/android/cordova/node_modules/q/q.js:863:30)
Path must be a string. Received undefined

(Write what happened. Please add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by B3L7** [comment]
Can confirm. I am having the same issue. Also when I uninstall I am getting the message:

`config file undefined requested for changes not found at /../../../../platforms/android/undefined, ignoring`

Not sure if it is related or I should open a separate issue.

**Comment by naveed-ahmad** [comment]
@n-clark @B3L7 

I removed android platform, installed the plugin. Then removed `edit-config` tag from plugin.xml 

```
<edit-config target="AndroidManifest.xml" parent="/manifest/application/meta-data[@android:name='com.google.android.gms.ads.APPLICATION_ID']" mode="overwrite">
            <meta-data
                android:name="com.google.android.gms.ads.APPLICATION_ID"
                android:value="$APP_ID_ANDROID" />
        </edit-config>
```

Then added android platform again. Added `<meta-data>` tag manually in android manifest. This is temporary solution but I was able to build the apk.

**Comment by n-clark** [comment]
I was able to reproduce this issue by installing the plugin, removing the plugin, then installing it again. The error `Path must be a string. Received undefined` occurs during the reinstall.

**Comment by B3L7** [comment]
It looks like [commit d1dcafa8bb987c3b66c5a55e62d189e17542e32e](https://github.com/admob-plus/admob-plus/commit/d1dcafa8bb987c3b66c5a55e62d189e17542e32e) resolved this issue for me.

**Comment by ratson** [comment]
@naveed-ahmad Is you issues resolved with the latest version?

**Comment by naveed-ahmad** [comment]
@ratson yes upgraded to `0.12.0` and issue is resolved. Thanks for quick fix.
