### ISSUE TITLE
Admob.BannerAd.config({backgroundColor: 'red'}) is not a function

### ISSUE THREAD

**Issue by MaxSultan** [admob-plus/admob-plus#391]
I am trying to change the background color of Banner ads in my Cordova app. I am using the admob-plus-cordova plugin. I have no problem getting ads to show on iOS or Android but I cannot change the background color of the ads. When I use this code admob.BannerAd.config({ backgroundColor: 'red' }) it tells me that the admob.BannerAd.config does not exist or admob.BannerAd.config is not a function. When I run npx admob-plus doctor i get an x on the Google-Mobile-ads-SDK because my version is 8.3.0 and not 8.5.0 (I dont see how that would cause this error). According to the docs it looks like this should be a simple process but something has caused it to be more complicated. Any help/ideas would be appreciated

**Comment by ratson** [comment]
@MaxSultan Would you create a test repo for me to check?

**Comment by MaxSultan** [comment]
Yes, working on it now

**Comment by MaxSultan** [comment]
It worked in a reduced test case for me, so it must just be how we initialize admob or create the banner instance. Sorry

**Comment by vigamage** [comment]
> It worked in a reduced test case for me, so it must just be how we initialize admob or create the banner instance. Sorry

How did you initialize it in your working sample ? I am struggling to get it to work. If you don't mind. can you show me the code there? thanks
