### ISSUE TITLE
Not able to use this plugin in iOS, if it is kids category

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#393]
While I am using this plugin for the iOS app in the kids category, the app doesn't approve, and they send the following message. Kindly help me to solve this issue.

**Guideline 1.3 - Safety - Kids Category**
We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. Specifically:

- Your app implements the App Tracking Transparency framework, which is used when apps collect data about users and share it with third-parties for tracking purposes. Since Kids Category apps are not allowed to collect, transmit or share identifiable information with third-parties, you should not implement App Tracking Transparency in your app.

- Your app includes third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA. We found that your app references the ASIdentifierManager API, which provides access to a user's IDFA, in the following location(s) in your binary:

• /System/Library/Frameworks/AdSupport.framework/AdSupport
• Tamil Story

It would be appropriate to remove all instances of “ASIdentifierManager” from your app, even if they are not utilized in your app's functionality.

**Next Steps**
To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.

**Comment by ratson** [comment]
@merbin2012 Unfortunately, you need to remove that part of the native code manually right now. Not sure if it worth to create another plugin for just this.

**Comment by merbin2012** [comment]
May I know where I need to remove the native code?

**Comment by ratson** [comment]
https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/ios/AMBPlugin.swift#L4

**Comment by merbin2012** [comment]
@ratson Thank you. Just uploaded to AppStore with removed the following code. Waiting for iOS approval, let you know, if they once reviewed.


```
#if canImport(AppTrackingTransparency)
import AppTrackingTransparency
#endif

........................
........................
........................

@objc func requestTrackingAuthorization(_ command: CDVInvokedUrlCommand) {
    let ctx = AMBContext(command)
    if #available(iOS 14, *) {
        ATTrackingManager.requestTrackingAuthorization(completionHandler: { status in
            ctx.success(status.rawValue)
        })
    } else {
        ctx.success(false)
    }
}
```

**Comment by merbin2012** [comment]
Hi! again this update was rejected by the iOS team. Kindly give more details, if you can.

**Comment by eltonnobrega** [comment]
Hi, I was looking to use admob for a kid-friendly app. Did this issue happen on Google Play too? Did you use child-directed tags? In Admob did you put G (children) in the public?

**Comment by merbin2012** [comment]
@eltonnobrega don't worry about playstore, it's only occurs in iOS only.

**Comment by merbin2012** [comment]
Finally got approved from iOS team, by did remove from the kids category and all relevant kids key words.

**Comment by eltonnobrega** [comment]
Hi, could you ask some more questions?
In admob:
Have you set up targeting for everyone, including children and families, maximum ad content rating for an app G?
Have you enabled user metrics? ("In order to provide accurate measurements, the Google Mobile Ads SDK will begin sending events at app start. Data will be collected automatically but will not be further processed for reporting or ad serving unless you decide to enable user metrics functionality in the AdMob front end.")

In the app:
Did you set tagForChildDirectedTreatment(true) and set max_ad_content_rating to G ?

On Google Play:
Is the app classified in the families program?

Can you say the name of the app?

**Comment by merbin2012** [comment]
@eltonnobrega It's not matter on iOS, if we are using **ASIdentifierManager** method, they will reject, even not collect any user tracking data.

**Comment by ratson** [comment]
The related APIs will be move to the consent plugin, please track progress in https://github.com/admob-plus/admob-plus/discussions/394
