### ISSUE TITLE
Cordova native ad with custom view : no such file or directory www/index.js

### ISSUE THREAD

**Issue by tweed2458** [admob-plus/admob-plus#395]
**Describe the bug**
Hi everyone,

First of all, sorry for my english.

I'm able to use this plugin with native ad but now I'm trying to customize view for Native Ad.

So I follow this instruction :

```
git clone https://github.com/admob-plus/admob-plus.git
cordova plugin rm admob-plus-cordova-native
cordova plugin add ./admob-plus/packages/cordova-native --link --save
cd admob-plus/packages/cordova-native
```

But after the command "cordova plugin add" I have always this error : 

ENOENT : no such file or directory, open C:\Users\XXX\Desktop\Project\test\admob-plus\packages\cordova-native\www\index.js

And indeed, this file doesn't exists.

Any idea ?

Thanks

**To Reproduce**
1. Create a new cordova project
2. Add android platform
3. Add plugin admob-plus-cordova
4. Then use this command : git clone https://github.com/admob-plus/admob-plus.git and cordova plugin add ./admob-plus/packages/cordova-native --link --save (in administrator)

**Environment**

Cordova version 10.0.0
Windows 10

```
(paste the output of the command here)
```

**Additional context**

**Comment by jasonandress** [comment]
Not sure if you figured this out yet or not but I went through the same thing today. 

There is a missing directory in the cordova-native folder which contains the missing file index.js. Just copy the www folder along with the index.js file that is in the plugin when you install it from the original into your fork and install it from your local again and it worked for me.

Not sure if this is the correct way but it works for me.

**Comment by slyd4r** [comment]
> from

where can I find that missing direcory ? I faced the same issue today .
