### ISSUE TITLE
Test ads work on the debug and do not work on the release

### ISSUE THREAD

**Issue by albasha942021** [admob-plus/admob-plus#397]
Hello
I am developing an app for Android phones using the Cordova platform and when using your plugin.
The ads appeared in the debug version and did not appear in the release version of the application file after build.
What is this problem and how do I solve it?

**Comment by albasha942021** [comment]
hi can any one help me to solve this problem

**Comment by ratson** [comment]
@albasha942021 See https://admob-plus.github.io/docs/troubleshooting#why-are-ads-not-showing

**Comment by albasha942021** [comment]
Hello
First I would like to thank you for your respond.
I use this command (npx admob-plus doctor) in my project and get that result.

![code](https://user-images.githubusercontent.com/86891277/125123692-4559f780-e0f7-11eb-9404-7fcf5af34a74.PNG)

the app is only for android not ios 
I use google test add and it work in debug apk but did not appear in the release apk.

**Comment by albasha942021** [comment]
> @albasha942021 See https://admob-plus.github.io/docs/troubleshooting#why-are-ads-not-showing
Hello
First I would like to thank you for your respond.
I use this command (npx admob-plus doctor) in my project and get that result.

the app is only for android not ios
I use google test add and it work in debug apk but did not appear in the release apk.
