### ISSUE TITLE
iOS Build failed: Swift Compiler Error No such module 'GoogleMobileAds' AMBAdBase.swift

### ISSUE THREAD

**Issue by Filavision** [admob-plus/admob-plus#400]
**Describe the bug**
When i try to compile my app in Xcode i run into a Swift Compiler Error: No such module 'GoogleMobileAds' AMBAdBase.swift

**To Reproduce**
1. Follow the steps on the website to install the plugin.
1. Biuld with the console: cordova build ios --release --buildConfig >> **BUILD SUCCSEEDED**
2. Open Xcode, click on Product > Archive >> **BUILD FAILED**

**Expected behavior**
The App should build

**Environment**
```
  AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.4
      CPU: (6) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
      Memory: 981.78 MB / 8.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.5 - /usr/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      cordova-ios: ^6.2.0 => 6.2.0 
      cordova-plugin-fingerprint-aio: ^4.0.2 => 4.0.2 
      cordova-plugin-geolocation-ios-fixed: ^1.0.0 => 1.0.0 
      cordova-plugin-inapppurchase-fixed: ^1.1.2 => 1.1.2 
      cordova-plugin-nativestorage: ^2.3.2 => 2.3.2 
      cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
      cordova-plugin-whitelist: ^1.3.5 => 1.3.5 
    npmGlobalPackages:
      cordova: 10.0.0
    Cordova:
      Version: 10.0.0
      Plugins:
        cordova-plugin-whitelist: ^1.3.5
        cordova-plugin-statusbar: ^2.4.3
        cordova-plugin-geolocation-ios-fixed: ^1.0.0
        cordova-plugin-nativestorage: ^2.3.2
        cordova-plugin-inapppurchase-fixed: ^1.1.2
        cordova-plugin-fingerprint-aio: ^4.0.2
    Ionic:
      Version: -
    AndroidManifest.xml:
      Version: -
```

**Additional context**
When i remove the plugin, everything works fine.
I also downloaded and added the "GoogleMobileAds.xcframework" to the Build Phases > Link Binary With Libraries and get another biuild error: "Framework not found FBLPromises"

**Comment by OziOcb** [comment]
Hi.

Did you find a solution to that? I'm having the same issue atm

Cheers

**Comment by Filavision** [comment]
No, sorry

**Comment by KevinGervais** [comment]
I found a solution:
do in command line:
```
sudo gem install cocoapods
cd ./platforms/ios
pod install --repo-update
```

**Comment by MaximPerry** [comment]
I'm having the same issue. Unfortunately your solution @KevinGervais doesn't work for me. 

When using the terminal to build my app (cordova run ios) everything works just fine. It only fails in Xcode when I try to use the Archive feature - I want to upload that to TestFlight.

**Comment by MaximPerry** [comment]
Ok I just found a solution:

- Upgraded Xcode to the latest version (Xcode 13)
- `cordova platform rm ios` then `cordova platform add ios`

I no longer have the issue in Xcode. However, running or building the app using cordova and the command line (`cordova run ios` `cordova build ios` fails everytime, but it does work in Xcode which is fine by me.

**Comment by lilmnm-kamikaze-** [comment]
I am also having this issue nothing works for me to get this working

**Comment by zeromark223** [comment]
try open file .xcworkspace to build, does not open file .xcodeproj.
Cocoapod use xcworkspace.

**Comment by danieldanielecki** [comment]
> I found a solution: do in command line:
> 
> ```
> sudo gem install cocoapods
> cd ./platforms/ios
> pod install --repo-update
> ```

didn't work. I had to revert back to `1.28.0`, for more see https://github.com/admob-plus/admob-plus/issues/613#issuecomment-2483042194
