### ISSUE TITLE
Cant get to show an ad with capacitor and vue

### ISSUE THREAD

**Issue by berti92** [admob-plus/admob-plus#403]
I installed your plugin via your 
`npm install @admob-plus/capacitor`
`npx cap sync`

Then I added 
`        <meta-data            android:name="com.google.android.gms.ads.APPLICATION_ID"            android:value="MY_APP_ID" />`
`        <meta-data            android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT"            android:value="true" />` to the Manifest.

I try to display an add via an onclick listener:
```
    handleBuyPoint: function() {
        (async () => {  
            await AdMobPlus.start();
            const interstitial = new InterstitialAd({    
                adUnitId: 'ca-app-pub-3940256099942544/1033173712',  
            })  
            await interstitial.load()  
            await interstitial.show()
        })()
    },
```

I debug my app via remote chrome webtools and I get the following:
![image](https://user-images.githubusercontent.com/11201469/124826653-5d097280-df75-11eb-931b-1bdbab6ac3cd.png)

I'm not able to get a interstitialad or rewarded ad to show up on my emulator screen.

Maybe anyone could help me. Am I doing sth wrong?

**Comment by ratson** [comment]
@berti92 Please prepare a test repo for me to check.

**Comment by berti92** [comment]
I figured it myself out. There was no problem with this plugin - sorry"
