### ISSUE TITLE
package.json variable APP_ID_ANDROID is not correctly written when running ionic cap sync

### ISSUE THREAD

**Issue by weberoliver** [admob-plus/admob-plus#404]
**Describe the bug**
When creating a basic configuration with ionic using capacitor with a blank app and implementing the home page as shown in the examples the app id variable is not correctly read from package.json. It can also not be updated.

**To Reproduce**
1. Set up a new ionic blank app with capacitor
2. install packages
3.  Run ionic capacitor add android
4. modify package.json
5. run ionic cap sync
6.  modify package.json again for the APP_ID
7. Checkout .\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml

**Expected behavior**
It should update everytime I run ionic capacitor sync or ionic capacitor run android -l 

**Screenshots**
![image](https://user-images.githubusercontent.com/47383295/124833621-c2ae2c80-df7e-11eb-848d-2d14e6862aaa.png)
![image](https://user-images.githubusercontent.com/47383295/124835112-1ae62e00-df81-11eb-864e-dc931914c509.png)

**Environment**

```
  AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.18363
      CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
      Memory: 2.81 GB / 15.95 GB
    Binaries:
      Node: 14.17.3 - D:\Programme\nodejs\node.EXE
      npm: 7.19.1 - D:\Programme\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 29, 30
        Build Tools: 28.0.3, 29.0.3, 30.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    Languages:
      Java: 1.8.0_212-release
    npmPackages:
      admob-plus-cordova: ^1.19.2 => 1.19.2
      typescript: ~4.2.4 => 4.2.4
    Cordova:
      Version: 8.1.2 (cordova-lib@8.1.1)
      Plugins:
        admob-plus-cordova: ^1.19.2
    Ionic:
      Version: 6.16.3
    AndroidManifest.xml:
      Version: -
```

**Additional context**
I was trying out to use admob plus with ionic capacitor, using my own app id for testing. This led to forcecloses showing me in adb logcat that the app id was invalid or wrong and this showed me in the AndroidManifest the app ID was always set back to ca-app~xxx-yyy from the examples. I first ran the installation via npm and then modified the package.json if this would make any difference. How do I know this happens? By running ionic capacitor run android -l looking at the manifest changing, then changing it during runtime of the command before the building through gradle and then seeing it work if i substitute it correctly.

**Comment by EYALIN** [comment]
@weberoliver from what I know, you cannot modify package.json and change your ID.
if you want to do so, you need to remove the plugin and add it again.
after adding the package, it goes to 4 files that are related to android/ios and therefore the modifying will not work.

try to reinstall and update

**Comment by gonzalomedelp** [comment]
I have the same problem. It doesn't work the way @EYALIN is saying either. I tried uninstalling the plugin (both npm installs) and it doesn't work. The AndroidManifest.xml file is not modified. I'm using Ionic with Capacitor.

**Comment by EYALIN** [comment]
@gonzalomedelp  can you remove the android platform and add it again?
maybe with capacitor, it's not synchronized

**Comment by ratson** [comment]
@weberoliver You will need to [update the config files manually](https://admob-plus.github.io/docs/capacitor) as [variables is not supported by Capacitor](https://capacitorjs.com/docs/plugins/cordova#variables-and-hooks).

**Comment by gonzalomedelp** [comment]
@EYALIN I did remove the platform and add it again. It didn't work.

**Comment by gonzalomedelp** [comment]
@ratson I thought that was the correct way, but the documentation is confusing. You have a "Capacitor" section, a "Cordova" section, and an "Ionic" section. Both Capacitor and Cordova can be used with other frameworks or languages besides Ionic, so it's obvious that one will follow only the "Ionic" instructions, specially when inside those instructions there's tabs for Cordova and Capacitor.
