### ISSUE TITLE
After closing the "app open ad" showing black screen 

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#405]
While switching off the screen and unlock the screen to show the App open ad appears, but most of the time while closing the app open ad, the app is showing a black screen. Also, needs to switch the app again to visible the app again. Kindly check the below screenshot.

![1](https://user-images.githubusercontent.com/3687184/125080689-bba02f00-e0e2-11eb-82fd-72bd70dc3dd3.jpg)
![2](https://user-images.githubusercontent.com/3687184/125080698-bd69f280-e0e2-11eb-84e7-c405bf8da3c5.jpg)

**Comment by EYALIN** [comment]
@merbin2012 can you give more details such as your version?
can you share your code of how you show the ad when resuming the app?
as long as you open it after the platform ready you should have no issue, I tried it in many devices

**Comment by merbin2012** [comment]
Just now I am checking this issue, but not yet this problem occurs. I think might this issue is solved in "admob-plus-cordova@1.20.0" version.  Now I am closing this issue. I will reopen if occur again. Thank you very much.

**Comment by merbin2012** [comment]
Still found this issue, off your screen a little longer and check it. I am using Redmi Note 5 Pro, I think this issue is not only on my device.

**Comment by EYALIN** [comment]
@merbin2012 can you please share your code when resuming to your app?

**Comment by merbin2012** [comment]
Just separating the App open code from the whole ad code.

```
document.addEventListener("resume",resumeAppOpenAd,false);


var _canAppOpenShow=true;

function resumeAppOpenAd()
{
	if(_canAppOpenShow)
		appOpenAdShow();
}

function appOpenAdShow()
{
	_appOpenAd.show();
}
function appOpenAdLoad()
{
	_appOpenAd.load();
}






document.addEventListener('admob.ad.load', function (evt) 
{
  console.log("App open loaded");
})  


document.addEventListener('admob.ad.loadfail', function (evt) 
{
  console.log("App open loadfail");
  appOpenAdLoad();
})  	

document.addEventListener('admob.ad.dismiss', function (evt) 
{
  console.log("App open dismiss");
  appOpenAdLoad();
})  



document.addEventListener('admob.ad.show', function (evt) 
{
	console.log("App open show");
})  



document.addEventListener('admob.interstitial.show', function(data){
	
	
	_isInterstitialLoaded=false;
	
	_canAppOpenShow=false;
	
	// handle event
	console.log("Interstitial loaded");

});		

document.addEventListener('admob.interstitial.dismiss', function(){

	_canShowInterstitial=false;
	
	setTimeout(function(){
		_canAppOpenShow=true;
	},15000);
	
	loadInterstitial();
	console.log("Interstitial closed");
});
```

**Comment by ratson** [comment]
@merbin2012 `admob.ad.*` events is emit for every ads, you should check the `evt.ad` for the correct instance.
Also, don't mix `admob.ad.*` and `admob.interstitial.*` events, both are emitted now for backward compatibility, the later ones will be removed from [the next major version](https://github.com/admob-plus/admob-plus/discussions/394).

**Comment by ratson** [comment]
@merbin2012 Did you fix this problem?

**Comment by merbin2012** [comment]
@ratson no, not yet solved.

**Comment by merbin2012** [comment]
@ratson I fixed by show the appopen ads by some setTimeout

Example
```
function resumeAppAd()
{
 setTimeout(appOpenAdShow,250)
}
```
