### ISSUE TITLE
Test ads work on the debug and do not work on the release #397

### ISSUE THREAD

**Issue by albasha942021** [admob-plus/admob-plus#406]
Hello
First I would like to thank you for your respond.
I use this command (npx admob-plus doctor) in my project and get that result.

![code](https://user-images.githubusercontent.com/86891277/125123692-4559f780-e0f7-11eb-9404-7fcf5af34a74.PNG)

the app is only for android not ios 
I use google test add and it work in debug apk but did not appear in the release apk.

_Originally posted by @albasha942021 in https://github.com/admob-plus/admob-plus/issues/397#issuecomment-877390619_

**Comment by albasha942021** [comment]
what should i do?

**Comment by ratson** [comment]
@albasha942021 It seems you are using an old version the plugin (1.14.0 < 1.19.2), please create a test repo for me to check. I cannot tell what's wrong from just the screenshot.

**Comment by albasha942021** [comment]
hello
how can i update the plugin?
i try to remove it and add it again and still the same version.

**Comment by albasha942021** [comment]
thank you so much the problem has been solved.
