### ISSUE TITLE
Cordova plugin add admob-plus-cordova failed - Command failed with exit code 31

### ISSUE THREAD

**Issue by YBurkhardt** [admob-plus/admob-plus#408]
Bug Description

I try to build a new version of my game, but now if I start my script I get an error while adding admob-plus-cordova and cordova-plugin-consent

`Failed to install 'admob-plus-cordova': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (Mls/GameClientHtml2/cordova-ios-test/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
pod: Command failed with exit code 31`

How to reproduce

1.) Create new cordova project: cordova create <dir> <bundleid> <name>
2.) Add iOS target cordova platform add ios
3.) add admit plus plugin: cordova plugin add admob-plus-cordova --save --variable APP_ID_IOS=<admobid>
4.) cordova plugin add cordova-plugin-consent

**Comment by EYALIN** [comment]
@YBurkhardt you just need to update "pod"
they had an update that breaks this plugin.

run the following inside your IOS folder "pod install"

**Comment by ratson** [comment]
@YBurkhardt What is your output of `npx admob-plus doctor`?

**Comment by EYALIN** [comment]
@ratson i had it too. he just need to update the pod. the old version of the pod not fit this plugin

**Comment by merbin2012** [comment]
As per the @EYALIN comment it worked well.
1) Install admob-plus plugin
2) Move to the ios directory
3) cd platforms
4) cd ios
5) pod repo update
6) pod install
Thats all, again move your cordova project then build it. Succcess....
