### ISSUE TITLE
Events only fire first time Ads are shown & dismissed 

### ISSUE THREAD

**Issue by jalilmotaz** [admob-plus/admob-plus#412]
**Describe the bug**
setting document event listener for admob.interstitial.dismiss fires the first time the interstitial ad is shown and dimissed. I then load and show the interstitial ad again but this time the dismiss event and all other events no longer are fired. I see in Java logs the error shown when sending the event "Application attempted to call on a destroyed WebView" Not sure why this happens.

**To Reproduce**
Add event listener for admob.interstitial.dismiss 
Fire interstitial ad two times
the second time the dismiss event is not fired

**Expected behavior**
the event listener should fire each time.

**Environment**
Android  
Cordova

I am not sure if I am doing something wrong the way I create/show the Ad. Below is my code. I have tried to make the interstitial varaible instatiated one time and I also tried to re-instantiate it every time but still no luck.

       this.ShowInterstitial = function () {

        interstitial = new admob.InterstitialAd({
            adUnitId: 'ca-app-pub-3940256099942544/8691691433',// TEST UNIT
        });
        interstitial.on('load', (evt) => {
            // evt.ad
        });
        interstitial.on('impression', (evt) => {
            // evt.ad
            console.log(evt);
        });
        document.addEventListener('admob.interstitial.dismiss', function () {
              console.log("DISMISSED ");
        });

    return interstitial.load().then(function () {
        return interstitial.show().then(function (res) {
            return res;
        });
    }); }

**Comment by jalilmotaz** [comment]
Issue solved. My issue was more comples. I have another Android activity that includes a manually added cordova webview. This then reinitializes the plugin again on device ready of second activity and all references get updated to this new webview. I had to make my second activity use regular WebView and not another CordovaSystemWebview to keep the reference to the correct CordovaWebView

**Comment by Carlosps** [comment]
@jalilmotaz Did the event 'admob.ad.click' fired for you? 

I was able to listen to the event 'admob.banner.open'. But not for the ad click event.

I am trying to simulate that event so that I would remove all ads to prevent users from clicking on ads over and over in the same session.
