### ISSUE TITLE
Impossible to make a new build:  "admob.plus.core.Ad$1 is defined multiple times"

### ISSUE THREAD

**Issue by Zerokk** [admob-plus/admob-plus#413]
Hello,

I added AdMob Plus to my project, and well, at start, it was working. I have in my phone a working version of my ionic app, builded with the --prod flag, that is showing the placeholder ad.

But after having some serious issues trying to sign the APK for the Play Store, I just started being unable to do absolutely anything with my project. I keep having this error regarding AdMob which I'm not able to solve:

`Type admob.plus.core.Ad$1 is defined multiple times: C:\Zerok\Dev\Proyectos\Dromous\node_modules\@admob-plus\capacitor\android\build\.transforms\caf89848ec3f4a75afca2ab1d3cbcd43\transformed\classes\classes.dex, C:\Zerok\Dev\Proyectos\Dromous\android\capacitor-cordova-android-plugins\build\.transforms\031de8c5ab4ccc04dd0cc8127e017c43\transformed\classes\classes.dex`

This is the output of the AdMob Doctor:

`✖ googleads.g.doubleclick.net
  › RequestError: getaddrinfo ENOENT googleads.g.doubleclick.net
✔ package.json
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_ANDROID
↓ Cordova Android dependencies [SKIPPED]
❯ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="SwiftVersion"]: missing / invalid
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error: platform[name="ios"]/preference[name="deployment-target"]: missing / invalid
↓ platforms/ios/*.xcodeproj [SKIPPED]
✔ plugins/admob-plus-cordova/package.json
  ✔ admob-plus-cordova: 1.20.1`

I tried following [this stackoverflow question](https://stackoverflow.com/questions/60507686/type-buildconfig-is-defined-multiple-times), but I don't see anything that has any impact on my project. The AdMob plugin is added just once, aswell the NPM library for the client code.

The other weird thing, is that you'd expect Gradle to care about the files in the /android folder, and not about the ones in node_modules. Why is it having a class collission with a file that's located outside the android folder? This doesn't make any sense.

I can't either build or do anything with my project as for now. I tried updating Android Studio, Gradle, cleaning and rebuilding the project, removing the Android folder and creating it again... and nothing.

**Comment by ratson** [comment]
@Zerokk Please create test repo for me to check.

**Comment by Zerokk** [comment]
@ratson I just created this test repo, with all the files that Capacitor uses for building the app, + the whole Android folder, just having removed some critical files like google_services and the API keys I need. I also removed the code, as it's perfect and it's not a code issue. Thanks!

**Comment by Zerokk** [comment]
(bump) @ratson hello there, did you do a little check on the files? Do you have an idea on what's failing? I still haven't found the problem and I'm hardstuck not being able to compile.

**Comment by ratson** [comment]
@Zerokk You should use `@admob-plus/capacitor` only without `admob-plus-cordova`.
Check https://github.com/admob-plus/admob-plus/blob/master/examples/ionic-angular-capacitor/src/app/tab1/tab1.page.ts for example.
