### ISSUE TITLE
clicking on the ios banner does not work

### ISSUE THREAD

**Issue by Sirioxstar** [admob-plus/admob-plus#417]
Describe the bug
IOS Banner ads cannot be clicked.
When you try to click ads, nothing happens.

To Reproduce
1. code added:
      await this.admob.start();

            this.banner = new this.admob.BannerAd({
                adUnitId: this.idAppBanner,
                position: 'top'
            });
            await this.banner.show();
2.Run on iPhone x
3.Click banner, nothing opened.

Expected behavior
Ad url must be opened.

Environment

ionic: 6.16.3
cordova: 10.0.0
cordova-ios: 6.2.0
admob-plus/ionic: 1.4.1
admob-plus-cordova: 1.20.1

**Comment by ratson** [comment]
@Sirioxstar Please let me know if it is fixed with `admob-plus-cordova@1.21.0`.
