### ISSUE TITLE
Cannot tap on anything if banner ad is displayed

### ISSUE THREAD

**Issue by mirfanazam** [admob-plus/admob-plus#424]
In iOS, I cannot tap on anything if a banner ad is showing. Only thing I can tap on is the banner ad.
But if I comment the code that shows banner ad then I can tap on buttons and menus without any problem.

  AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.5.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 6.71 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.5 - /usr/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_251 - /usr/bin/javac
    npmPackages:
      admob-plus-cordova: 1.22.0 => 1.22.0 
      cordova-android: ^9.1.0 => 9.1.0 
      cordova-clipboard: ^1.3.0 => 1.3.0 
      cordova-ios: ^6.2.0 => 6.2.0 
      cordova-plugin-advanced-http: ^2.4.1 => 2.5.1 
      cordova-plugin-background-mode: ^0.7.3 => 0.7.3 
      cordova-plugin-camera: ^4.1.0 => 4.1.0 
      cordova-plugin-device: ^2.0.2 => 2.0.3 
      cordova-plugin-geolocation: ^4.0.2 => 4.1.0 
      cordova-plugin-googlemaps: ^2.7.1 => 2.7.1 
      cordova-plugin-inappbrowser: ^5.0.0 => 5.0.0 
      cordova-plugin-ionic-keyboard: ^2.2.0 => 2.2.0 
      cordova-plugin-ionic-webview: ^5.0.0 => 5.0.0 
      cordova-plugin-local-notification: ^0.9.0-beta.2 => 0.9.0-beta.2 
      cordova-plugin-nativegeocoder: ^3.4.1 => 3.4.1 
      cordova-plugin-network-information: ^2.0.2 => 2.0.2 
      cordova-plugin-splashscreen: ^6.0.0 => 6.0.0 
      cordova-plugin-statusbar: ^2.4.2 => 2.4.3 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
      cordova-plugin-x-socialsharing: ^5.6.5 => 5.6.8 
      cordova-plugin-x-toast: ^2.7.2 => 2.7.2 
      cordova-sqlite-storage: ^5.0.0 => 5.1.0 
      typescript: ~3.4.3 => 3.4.5 
    npmGlobalPackages:
      cordova: 10.0.0
    Cordova:
      Version: 10.0.0
      Plugins:
        cordova-plugin-statusbar: ^2.4.2
        cordova-plugin-device: ^2.0.2
        cordova-plugin-ionic-keyboard: ^2.2.0
        cordova-plugin-camera: ^4.1.0
        cordova-sqlite-storage: ^5.0.0
        cordova-plugin-x-toast: ^2.7.2
        cordova-plugin-advanced-http: ^2.4.1
        cordova-clipboard: ^1.3.0
        cordova-plugin-x-socialsharing: ^5.6.5
        cordova-plugin-local-notification: ^0.9.0-beta.2
        cordova-plugin-network-information: ^2.0.2
        cordova-plugin-googlemaps: ^2.7.1
        cordova-plugin-geolocation: ^4.0.2
        cordova-plugin-nativegeocoder: ^3.4.1
        cordova-plugin-background-mode: ^0.7.3
        cordova-plugin-whitelist: ^1.3.4
        cordova-plugin-inappbrowser: ^5.0.0
        cordova-plugin-ionic-webview: ^5.0.0
        cordova-plugin-splashscreen: ^6.0.0
        admob-plus-cordova: 1.22.0
    Ionic:
      Version: 6.13.1
    AndroidManifest.xml:
      Version: -

**Comment by ratson** [comment]
@mirfanazam Would you create a test repo for me to check?

**Comment by mirfanazam** [comment]
@ratson Let me try to create a test project try to reproduce it.

**Comment by mirfanazam** [comment]
@ratson I have tested it by creating a project from scratch but it works fine without any problem.

But in my original project it same problem. On Android, it is working fine but on iOS I am facing this issue.

**Comment by ratson** [comment]
@mirfanazam I guess it is conflicting with other plugin's view manipulation, that's why I need to a test repo to figure out what could be fixed.

**Comment by mirfanazam** [comment]
@ratson I am trying to figure out which plugin is conflicting with it. Once found then I can create a test repo.

**Comment by ratson** [comment]
@mirfanazam Would you check if this is fixed by the latest release?
