### ISSUE TITLE
(IOS) warns

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#429]
can't run the app. it warns like this

When I don't install the plugin I can run the app normally.

**how to disable it**

<img src="https://user-images.githubusercontent.com/78555833/132753312-1ef34ade-5256-4755-9f07-3aee00eed799.png" width="300" height="500">

**Comment by ratson** [comment]
@EMI-INDO Do you have the crash log? It could be caused by the AdMob SDK if you forge to remove it.

**Comment by EMI-INDO** [comment]
sorry I just recently replied, now it's working fine.

Thank you friend.
