### ISSUE TITLE
cordova-plugin-add-swift-support dependency

### ISSUE THREAD

**Issue by deliverymanager** [admob-plus/admob-plus#43]
Is this module a dependency to the plugin cordova-admob-plus?

This is a huge disadvantage as the swift libraries make the .ipa huge!

Is there a workaround this?

**Comment by ratson** [comment]
Yes, it is used to provide Swift support. If you don't want it, you could try `cordova-plugin-admob-free`, but I don't recommend it.

How much size is increased do you see?

**Comment by ratson** [comment]
@deliverymanager The increased size is mainly due to https://developers.google.com/admob/ios/download, not much from Swift support.

**Comment by deliverymanager** [comment]
cordova-plugin-admob-free uses the same libraries right?
It just not written with Swift.
The build is not increasing using the other plugin.
The same issue had Ionic with its cordova plugin.
They used the dependency and the ipa was huge.
They finally removed all the swift code from their plugin and dropped the dependency.

**Comment by ratson** [comment]
If that is the case, need to look deeper for the reasons.

@deliverymanager Would you try the official Swift sample to see if the same happens? https://github.com/googleads/googleads-mobile-ios-examples/tree/master/Swift/admob
I would like to confirm if it is Swift problem or the plugin I used for adding Swift support introduce it.

**Comment by JaredBrown138** [comment]
I personally didn't see a size increase that big. My .Ipa went from ~12mb to ~20mb. I can provide more details on my build if needed, not sure what information would be helpful.

**Comment by deliverymanager** [comment]
I don't know why I saw a bigger increase, but in my opinion in your case the increase from 12MB to 20MB is also huge.
My .ipa is around 6MB and I try to keep it as small as possible.
