### ISSUE TITLE
( ERROR ) cordova plugin add admob-plus-cordova@1.25.0

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#435]
cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID="test"  `success`
cordova plugin add admob-plus-cordova`@1.25.0` --variable APP_ID_ANDROID="test"  `error`
cordova plugin add admob-plus-cordova`@1.25.0` `error`

log error 

`cordova plugin add admob-plus-cordova@1.25.0 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713
Failed to fetch plugin admob-plus-cordova@1.25.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for admob-plus-cordova@1.25.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\62822\AppData\Roaming\npm-cache\_logs\2021-09-24T16_33_54_325Z-debug.log`

**Comment by ratson** [comment]
@EMI-INDO What is your `npm info admob-plus-cordova@1.25.0` output?

**Comment by EMI-INDO** [comment]
> cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID="test" `success`
> cordova plugin add admob-plus-cordova`@1.25.0` --variable APP_ID_ANDROID="test" `error`
> cordova plugin add admob-plus-cordova`@1.25.0` `error`
> 
> log error
> 
> `cordova plugin add admob-plus-cordova@1.25.0 --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713
> Failed to fetch plugin admob-plus-cordova@1.25.0 via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> CordovaError: Error: npm: Command failed with exit code 1 Error output:
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for admob-plus-cordova@1.25.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\62822\AppData\Roaming\npm-cache_logs\2021-09-24T16_33_54_325Z-debug.log`

**Comment by EMI-INDO** [comment]
> @EMI-INDO What is your `npm info admob-plus-cordova@1.25.0` output?

nothing happens `npm info admob-plus-cordova@1.25.0`

I open debug.log `npm ERR! C:\Users\62822\AppData\Roaming\npm-cache_logs\2021-09-24T16_33_54_325Z-debug.log`




0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'admob-plus-cordova@1.25.0',
1 verbose cli   '--save-dev'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose npm-session b392702db20b2f45
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://repo.huaweicloud.com/repository/npm/admob-plus-cordova 42ms (from cache)
8 silly registry:manifest no matching version for admob-plus-cordova@1.25.0 in the cache. Forcing revalidation.
9 http fetch GET 200 https://repo.huaweicloud.com/repository/npm/admob-plus-cordova 1863ms
10 silly fetchPackageMetaData error for admob-plus-cordova@1.25.0 No matching version found for admob-plus-cordova@1.25.0.
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 2192ms
13 verbose type version
14 verbose stack admob-plus-cordova: No matching version found for admob-plus-cordova@1.25.0.
14 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
14 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:43:18
14 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
14 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
14 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
14 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
14 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
14 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
14 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
14 verbose stack     at processImmediate (internal/timers.js:464:21)
15 verbose cwd C:\Users\62822\Desktop\Build Release\admob
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "admob-plus-cordova@1.25.0" "--save-dev"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ETARGET
21 error notarget No matching version found for admob-plus-cordova@1.25.0.
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]
`

**Comment by EMI-INDO** [comment]
Thank you now it can be added

**Comment by ratson** [comment]
@EMI-INDO I see you are using a mirror npm registry, which could have delay on releases, you may try using "https://registry.npmjs.org" if this is happened next time.
