### ISSUE TITLE
Request User Consent

### ISSUE THREAD

**Issue by Winamp9** [admob-plus/admob-plus#443]
Hello. consent.getConsentStatus () returns "Unknown" for both eu and non-eu countries.
Do I need to publish applications for ConsentStatus to return correct values? Do I need to create a message in the AdMob account in the Privacy & Messages section?

**Comment by EMI-INDO** [comment]
@Winamp9 https://support.google.com/fundingchoices/answer/9180084

**Comment by Winamp9** [comment]
@EMI-INDO 
I created messages in the "Privacy and Messages" section in AdMob, published the application in google play, but formStatus returns 2 (Unavailable) for all users. Does it take time to start showing new consent messages?
