### ISSUE TITLE
Refresh Native Ad - Cordova

### ISSUE THREAD

**Issue by jasonandress** [admob-plus/admob-plus#458]
Calling native.load() to load a new ad does not load a new ad.

**Expected behavior**
Calling native.load() will load a new ad.

I've posted this in the discussion section with no reply in a while. Looking for help. Either I'm doing this wrong or it isn't implemented.

**Comment by philippogol** [comment]
have you first tried with other ad units to test if it works? i find the Interstitial the most easy to try to check if all is alright.
to go on the safe side, you can use a window.settimeout, something like this

window.setTimeout(function(){
interstitial = new admob.InterstitialAd({
adUnitId: _adUnitId,
})
//will be called just only when the module has finished loading the ad
interstitial.on('load', (evt) => {
interstitial.show();
});
//first call of the ad (loading)
interstitial.load();
},20000);

gl!
