### ISSUE TITLE
I'm getting rejected because of AppTrackingTransparency

### ISSUE THREAD

**Issue by DesignerApparelSales** [admob-plus/admob-plus#459]
I did not use apptracking and stated that in the notes for review, but I still get rejected. 

"Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.1."...

"If your app does not track users, update your app privacy information in App Store Connect to undeclare tracking. "

This is my replied: "This app plugin have AppTrackingTransparency/Tracking option that can be turnoff and not use. I did not use AppTrackingTransparency or tracking and do not have any personalize ads. I can not update the app privacy information since the plugin have a feature to enable AppTrackingTransparency," But I still get rejected.

**Comment by DesignerApparelSales** [comment]
Yeah, it not getting thru, one of my other app got passed but when I resubmit a new binary, I have to go thru the process of explaining it all over again. 

Thank so much for the  plugin but can you guy make it so the AppTrackingTransparency framework are not use or  not show if we choose not to us it.

**Comment by EMI-INDO** [comment]
@DesignerApparelSales  

I also have the same problem

**Comment by DesignerApparelSales** [comment]
I ended up just add AppTrackingTransparency, Its too much of a hassle to keep on explaining to those reviewers.

**Comment by danieldanielecki** [comment]
@DesignerApparelSales how have you done that?
