### ISSUE TITLE
Support mediation? Unity ads, adcolony ...

### ISSUE THREAD

**Issue by berkinalex** [admob-plus/admob-plus#46]
Support mediation? Unity ads, adcolony ...

**Comment by bardgr** [comment]
Mediation is a major kick back to use the admob plus in favor of the admob free. I just gave a symbolic financial support to help the author. More with the feature

**Comment by joshlatimer** [comment]
Any update on this? more than willing to support if this can start getting worked on soon

**Comment by zarelint** [comment]
please say  if you have in mind adding this feature?

**Comment by elkhalifte** [comment]
any news about mediation???

**Comment by victorvhpg** [comment]
any news?

**Comment by ratson** [comment]
Move to https://github.com/admob-plus/admob-plus/discussions/269
