### ISSUE TITLE
Stuck on MobileAds.initialize

### ISSUE THREAD

**Issue by becvert** [admob-plus/admob-plus#460]
Hello,

`await admob.start()` started to not resolve on Android devices wich prevented me from displaying ads in my apps.

the `start` method calls [MobileAds.initialize()](https://github.com/admob-plus/admob-plus/blob/76557eaf95905e1012a2084383c4bb34bcf05ecd/packages/cordova/src/android/cordova/AdMob.java#L63)

For some unknown reason, the OnInitializationCompleteListener started to not being triggered so `callbackContext.success` is never returned to cordova.

For the time being, as a workaround maybe, I call MobileAds.initialize() with no listener and return callbackContext.success straight away. This seems to work.

According to some discussions on other places, `MobileAds.initialize()` is not mandatory. Maybe `admob.start` should not depend on the listener.

Do any of you have seen this problem too ? If yes, do you know why it happens ?

For info, my app is well setup, no Admob violation, etc, it's been running like this for a while, without notice AdMob started to fail.

Kind regards

**Comment by EMI-INDO** [comment]
I also have the same problem

**Comment by netmist** [comment]
I have the same problem too.

**Comment by arcadesindo** [comment]
We are having the same issue
https://github.com/Scirra/Construct-3-bugs/issues/5211

Our game was updated on last Oct 12, but suddenly on Nov 10, the game got blackscreen because the admob function stuck

**Comment by royan1** [comment]
Also having the same issue here :(

@ratson - willing to fund $200 if this can be looked at as priority?

**Comment by transoceanic** [comment]
I also have the same problem here
Perhaps this is due to https://groups.google.com/g/google-admob-ads-sdk/c/zMshI4tmAwc?pli=1

**Comment by fredriksthlm** [comment]
https://groups.google.com/g/google-admob-ads-sdk/c/f7s7waakTSI

**Comment by robertwsug** [comment]
This appears to be fixed now without any code change required, likely a result of Google resolving the issue on their end.

**Comment by becvert** [comment]
Thank you all
