### ISSUE TITLE
No production ads, only test ads work

### ISSUE THREAD

**Issue by Merkane** [admob-plus/admob-plus#47]
I've integrated the admob-plus plugin for Cordova and I'm only getting test ads. When I disable the setDevMode to false it will never show my banner or interstitial ads. For example, the event 'admob.banner.load_fail' will always return

When I check the flow in admob.js it seems that it does parse a valid ad unit. I've tested this ad unit with another admob plugin: https://www.npmjs.com/package/cordova-admob and there it works fine. I wanted to move over to this one since that one does not support rewarded videos at the moment.

Cordova version: 8.1.2
Cordova Admob plus version: 0.0.0 (installed it through the CLI: cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=my_app_id_here
Platorm: Android
Test device: Samsung galaxy S9
Android version: 8.0

My call to create the banner ads:
`Publisher.createBannerAd = function() {
  if(admob) {
    admob.banner.show({
      id: {
        // replace with your ad unit IDs
        android: Publisher.admobId.banner
      }
    });
  }
};`

My call to prepare the interstitials and show when loaded:
`Publisher.prepareInterstitialAd = function() {
  if(admob) {
  admob.interstitial.load({
      id: {
        // replace with your ad unit IDs
        android: Publisher.admobId.interstitial
      }
    }).then(() => admob.interstitial.show())
  }
};`

The variable Publisher.admobId.banner is the 'ca-app-pub-xxx/xxx' of my admob. I also tried to hardcode my ca-app-pub id as a string in the id object but no succes either.

Any suggestions what I'm doing wrong?

**Comment by lucaele** [comment]
Last week 0.13.0 release was working fine,
but today not with same code?

Same problem for me with 0.14.2 release.
- cordova 8.1.2
- android platform 7.1.3

Any idea?

**Comment by lucaele** [comment]
On debug my app i fund this:
I/Ads: Ad failed to load : 3

Any idea how fix?

**Comment by lucaele** [comment]
https://stackoverflow.com/questions/33566485/failed-to-load-ad-3

**Comment by Merkane** [comment]
Hi @lucaele I'm not seeing the error code 3 but I do get the same basically:

I/Ads: No fill from ad server.

Weird thing was that I did see impressions 2 days ago and when I switched to admob-plus they didn't work anymore. I double checked everything on the admob side in our account but everything seems correct :(

**Comment by Merkane** [comment]
@lucaele I have no idea... I just tested again with https://www.npmjs.com/package/cordova-admob but this gives me the same errors now. For me the production ads worked on Tuesday but then they stopped working slightly after.

Also tried https://ratson.github.io/cordova-plugin-admob-free/ but no luck either.

@ratson do you have the same issue that production ads stopped showing for you?

**Comment by lucaele** [comment]
In my device (no.1)... banner NOT works!
Testing my app in other device (no.2) ... banner works!

How long Admob not fill ads in my (no.1) device?

**Comment by lucaele** [comment]
@Merkane are you using Android Studio for debuggin?

**Comment by Merkane** [comment]
Yes I am. I get: I/Ads: No fill from ad server. and w/ads failed to load ad 3. I tried to change my package name, tested on 4 different Android devices now

1. Samsung Galaxy S9
2. Oneplus 6
3. Huawei P20 pro
4. Samsung galaxy S7

and on all devices I just get the no fills...

**Comment by iFeddy** [comment]
i thought i had problem with installation. Having same problem, cant make ads work on production. Ad units were active before i switched to plus from free.

**Comment by svzi** [comment]
I've recently discovered some issues as well, but I was lucky to solve them:
https://github.com/admob-plus/admob-plus/issues/51#issuecomment-444868490

Maybe that helps here as well?

**Comment by iFeddy** [comment]
> I've recently discovered some issues as well, but I was lucky to solve them:
> [#51 (comment)](https://github.com/admob-plus/admob-plus/issues/51#issuecomment-444868490)
> 
> Maybe that helps here as well?

awesome, thank you!

**Comment by svzi** [comment]
@iFeddy Did it solve your issue as well?

**Comment by lucaele** [comment]
@iFeddy, it solve for me.

**Comment by DooDiddle** [comment]
@lucaele @iFeddy I tried testing this with ionic with my device attached  using "ionic cordova run android --device --prod" to get a prod build. I still don't see live ads, only test ads. Can you help?

**Comment by svzi** [comment]
@DooDiddle You should probably read my full comment:

> I solved it by running a production build of my app, that have been signed and seems to be trusted.

You're testing with an unsigned(!) production build, try what I suggested and use a signed build.

**Comment by svzi** [comment]
Try:
`ionic cordova run android --device --prod --release`

**Comment by ecomlix** [comment]
Same error :/ istrusted : false
i think its an issu from admob not in the plugin

**Comment by Merkane** [comment]
I tried
cordova run android --device --prod --release and already tried cordova run android --release before but both didn't work. I still get 0 fill every single time. How did you test if the json returned trusted on your release app?

**Comment by svzi** [comment]
@Merkane My app didn't return "trusted", because `isTrusted: false` was the error message in the error handler. When I sign my build, the error handler doesn't get called and the ad is being displayed.

**Comment by Merkane** [comment]
Annoying thing about the release app is that you can't debug it anymore. At the moment I have the same behaviour of just nothing shows. I checked with our ad manager but everything seems to be active, registered etc etc. We've reached out to Google if they can have a look what's wrong.

**Comment by svzi** [comment]
@Merkane When you manually install your signed APK on a real device, you can still see debug output from `console.log(...)` in your ADB log afair.

**Comment by Merkane** [comment]
@svzi thanks for the info! So basically I don't get any different result compared to a debug apk:

2018-12-11 14:20:19.633 19855-19855/? I/chromium: [INFO:CONSOLE(171)] "isTrused? false", source: file:///android_asset/www/src/publisher.js (171)
2018-12-11 14:20:19.634 19855-19855/? I/chromium: [INFO:CONSOLE(172)] "errorcode: 3", source: file:///android_asset/www/src/publisher.js (172)
2018-12-11 14:20:19.634 19855-19855/? I/chromium: [INFO:CONSOLE(180)] "Banner Ad failed to load", source: file:///android_asset/www/src/publisher.js (180)

I'm still getting the isTrusted is set to false and the error code 3.

**Comment by Merkane** [comment]
Yeah will do that in the coming days. I'm using plain Cordova btw, no Ionic.

**Comment by DooDiddle** [comment]
@svzi @Merkane I built my prod version that is signed, and still don't see live ads. I can't see any errors either, what do you use to see messages like these?:
"Banner Ad failed to load"
"isTrused? false",

**Comment by svzi** [comment]
@DooDiddle I'm not sure, but I thought I would use my usual tools. But maybe I didn't even inspect the log files, because on my signed builds the ads appear as expected. So I had no reason to check the logs.

**Comment by DooDiddle** [comment]
@svzi @Merkane @lucaele

I pulled logs from the phone I am testing this on fitered for "Ads" and I got this: Any ideas why I am not seeing prod ads only test ads?

Ads     : Updating ad debug logging enablement.
Ads     : Update ad debug logging enablement as false
Ads     : Use AdRequest.Builder.addTestDevice("XXX") to get test ads on this device.
Ads     : Invoke Firebase method getInstance error.
Ads     : The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date
Ads     : Not retrying to fetch app settings
Ads     : SDK version: afma-sdk-a-v14799017.12451000.1
Ads     : Ad failed to load : 3
Ads     : Use AdRequest.Builder.addTestDevice("XXX") to get test ads on this device.
Ads     : App does not have the required permissions to get location
Ads     : SDK version: afma-sdk-a-v14799017.12451000.1
Ads     : Ad failed to load : 3

**Comment by svzi** [comment]
@DooDiddle I wouldn't use the constructor for that. Maybe the component gets created before the UI is even visible? Try to use it in the `ionViewDidEnter()` method instead.

**Comment by svzi** [comment]
@DooDiddle You can clone this repository and try the Ionic3 example app. If that works out, you could compare the code with your own and try to find the difference. That's all I can suggest, because I didn't try with Ionic4 and this way, you could figure it out on your own and let us known thereafter. Will sure be helpful to others as well.

**Comment by DooDiddle** [comment]
I was able to see ads in production. I have not made any changes to the code. I have changed the app name, have uploaded a test version to app store to try, although I cannot confirm if any of these made a difference or caused ads to start showing up.

**Comment by suathh** [comment]
I am having this issue on iOS. Did anyone has a problem like this ?
