### ISSUE TITLE
why by default NSUserTrackingUsageDescription key is added in info.plist ? in IONIC

### ISSUE THREAD

**Issue by krunalsk007** [admob-plus/admob-plus#486]
### Discussed in https://github.com/admob-plus/admob-plus/discussions/484

<div type='discussions-op-text'>

<sup>Originally posted by **krunalsk007** January  4, 2022</sup>
i received this warning when i am uploading my app on app store 
"Your app contains NSUserTrackingUsageDescription, indicating that you will request permission to track users. To update this information on your app's product page, you must indicate which data types are tracking users. If this is incorrect, update your app binary and upload a new build to App Store Connect."
 
 **Even i am not using ATT so why by default this key inserted at a bulid time.** 
 
**How to remove that key ?? or can i used that key without using of ATT in my app.**
@ratson  
  </div>

**Comment by yuto7th** [comment]
I'm also facing a similar issue. I'm wondering if there is a way to specify installation parameters for admob-plus to avoid adding NSUserTrackingUsageDescription to info.plist during installation. If such a mechanism exists, it could potentially resolve the problem. Alternatively, if there isn't such an option, is it correct to understand that implementing AppTrackingTransparency (ATT) is mandatory to use this plugin?
