### ISSUE TITLE
iOS- Error: pod: Command failed with exit code 31

### ISSUE THREAD

**Issue by lucaele** [admob-plus/admob-plus#49]
Hi all,
my project has build right on Android but in iOS there is a problem:
Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code 31

This error appear after the follow commands:
- cordova platform rm ios
- cordova platform add ios

Cordova version: 8.1.2 (cordova-lib@8.1.1)
Installed platforms:
  android 7.1.3
  ios 4.5.5

Project plugin list:
cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-enable-multidex 0.1.3 "Enable Multidex"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"

Any idea how fix?

**Comment by lucaele** [comment]
SOLVED, just run
pod repo update

**Comment by JoeMeeks** [comment]
@lucaele did you have to install some cocoapods cli dependency to do this?
