### ISSUE TITLE
cannot find viewProvider: default

### ISSUE THREAD

**Issue by mayankkataria** [admob-plus/admob-plus#494]
I'm facing this error: ```ERROR Error: Uncaught (in promise): cannot find viewProvider: default``` while implementing native ads with below code:
```
const ad = new admob.NativeAd({
    adUnitId: 'ca-app-pub-3940256099942544/2247696110'
})
await ad.show({
    x:0,
    y:50,
    width: window.screen.width,
    height: 300
});
```

**Comment by ratson** [comment]
@mayankkataria It looks like you did not install `admob-plus-cordova-native`
Please provide your `npx admob-plus doctor` output.

**Comment by msalmikais** [comment]
@mayankkataria , i have the same problem !!! any solution ???  (ionic - cordova)

**Comment by mayankkataria** [comment]
> @mayankkataria It looks like you did not install `admob-plus-cordova-native` Please provide your `npx admob-plus doctor` output.

Yes that was an issue. @msalmikais I forgot to install ```admob-plus-cordova-native``` plugin. After installing it, this problem was solved.

**Comment by jonatarussi** [comment]
Same here, both plugins added.. but the error still persist

**Comment by vandilsondamata** [comment]
Same here, both plugins added.
