### ISSUE TITLE
Testing mode

### ISSUE THREAD

**Issue by hckr** [admob-plus/admob-plus#5]
Is there an option to use test ad units, as stated in [AdMob docs](https://developers.google.com/admob/android/rewarded-video?hl=pl#always_test_with_test_ads)?

> Always test with test ads
> 
> When building and testing your apps, make sure you use test ads rather than live, production ads. Failure to do so can lead to suspension of your account.
> 
> The easiest way to load test ads is to use our dedicated test ad unit ID for Android rewarded video:
> 
> ca-app-pub-3940256099942544/5224354917

**Comment by ratson** [comment]
Added https://admob-plus.github.io/docs/test-ads.html#dev-mode

**Comment by hckr** [comment]
Thanks!

**Comment by reinaldoborin** [comment]
> Added https://admob-plus.github.io/docs/test-ads.html#dev-mode

Link 404.
