### ISSUE TITLE
Kindly Help: Unable to get Admob-Plus to work!

### ISSUE THREAD

**Issue by Amaeta** [admob-plus/admob-plus#507]
### Discussed in https://github.com/admob-plus/admob-plus/discussions/506

<div type='discussions-op-text'>

<sup>Originally posted by **Amaeta** March 14, 2022</sup>
My work is on Cordova (BUILDING FOR iOS) and I have successfully added Admob-plus. Tested with npx admob-plus doctor:
✔ googleads.g.doubleclick.net
❯ CocoaPods
  ✖ Google-Mobile-Ads-SDK not found
    › Run `pod repo update`
✔ package.json
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_IOS
↓ Cordova Android dependencies [SKIPPED]
❯ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="Swift…
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error: platform[name="ios"]/preference[name="…
  ✔ APP_ID_IOS
✔ platforms/ios/iczit.xcodeproj
  ✔ SWIFT_VERSION: 5.3
✔ plugins/admob-plus-cordova/package.json
  ✔ admob-plus-cordova: 1.27.0

Ran pod repo update RESULT: Updating spec repo `trunk`

I have built successfully but cannot receive any ads neither a show that there is an ad space.

**Also, can anyone help me with the code for Cordova? I want to be sure it is not the arrow function problem. I built my app on pure javascript.**</div>

**Comment by Amaeta** [comment]
Just to mention that my platform is Apache Cordova. Any sample code will be appreciated

**Comment by Adrinc** [comment]
did you solve?

**Comment by Amaeta** [comment]
No I didn't.

**Comment by jmelvin** [comment]
Perhaps you are running a debug build.  Try building for --release and retesting.  I had the same issue at first.  The instructions should be updated to include this warning and save centuries of man-hours.

**Comment by MaximPerry** [comment]
Hey there, 
I am a proud noob, but I may be able to help! For some reason, for me, the code example from the documentation doesn't work.

But this did the trick:

`
//This function is generated automatically by Cordova in index.js
function onDeviceReady() {

    try {
        admob.start();
        banner = new admob.BannerAd({ adUnitId: 'ca-app-pub-3940256099942544/6300978111' }); //this is the test app ID for Android
        banner.load();
        banner.show();
      } catch (e) {
        console.log(e); // Outputs "Fail to create ad"
      }
}`

**Comment by Amaeta** [comment]
Thanks a lot Maxim.

Mind sending me all? For app open, interstatia and native?

**Comment by MaximPerry** [comment]
Mhhh, I got the banner to work since that's what I want to use in my app, but I'm not sure how the other types of ads would work, sorry...

I'll come back here to comment if I get to them.

**Comment by EYALIN** [comment]
@Amaeta is the new version made it work?

**Comment by Amaeta** [comment]
Yes, it works now. Thanks a lot to those who have helped me.

Was wondering how to optimize earning from admob, frequency of banner ad
display etc.

**Comment by EYALIN** [comment]
@ratson  you can close this one.
