### ISSUE TITLE
I have exactly the same symptoms as the previous bug

### ISSUE THREAD

**Issue by moguba** [admob-plus/admob-plus#509]
only rewardvideo error!
I have exactly the same symptoms as the previous bug.
In other words, in ios, it is a bug that the application is forcibly terminated when it ends after the billing time of google ad.
Probably because the part that was corrected at that time has not been corrected this time.

If you can fix that part, Cordova admob pro ver1.27.0 will have no problem.
Please correct it.
ios is 15.4

[safe33c-apri-2022-03-19-081403.txt](https://github.com/admob-plus/admob-plus/files/8308122/safe33c-apri-2022-03-19-081403.txt)
.

**Comment by moguba** [comment]
The admob-plus plugin worked successfully.
In addition, we were able to confirm the operation of banner ads and AdWords ads.
Thank you very much.

**Comment by EYALIN** [comment]
@ratson you can close this ticket
