### ISSUE TITLE
Error Message from admob.banner.load_fail

### ISSUE THREAD

**Issue by KaseSiu** [admob-plus/admob-plus#51]
I installed the admob-plus, and i change the app id and ds unit id.
But i got an error from admob.banner.load_fail event, it return a json.
`{ "isTrusted":false }`

Is it my admob account problem or something else,
Please tell me how to solve this problem, thank you.

**Comment by svzi** [comment]
@KaseSiu I just discovered the same issue (with version `0.15.0` of this plugin). I couldn't see any ads, neither my banner nor my interstitial were showing. I solved it by running a production build of my app, that have been signed and seems to be trusted. 

I hope that helps!

**Comment by ecomlix** [comment]
running a production build of app with this command line do not solve probleme for me :/
ionic cordova build android --prod --release

**Comment by KaseSiu** [comment]
It is working now when i release the app, thank you.

**Comment by MoradAbdelgaber** [comment]
@KaseSiu , I run ionic cordova build android --prod --release and signed the apk and also got the same error

**Comment by beingakashyadav** [comment]
@KaseSiu will you please help me to solve this error??

**Comment by edips** [comment]
@svzi Thanks for your suggestion! it works for Admob project for Qt  :)

**Comment by suathh** [comment]
I am getting this error in iOS. Is there a solution for iOS ?
