### ISSUE TITLE
Cordova Android Banner is displayed twice , 3 , 4 ...

### ISSUE THREAD

**Issue by JLWINC** [admob-plus/admob-plus#510]
Hello, i use **android 10.1.1** **SDK30** **CORDOVA CLI 11** 

when i refresh page _index.html_ every time is create a new banner and keep the last one like the picture or open a new page like **index2.html** and back to **index.html**  :

![TEST](https://user-images.githubusercontent.com/49573915/160085587-cdbcb70a-7a8c-45ab-bb24-19ba5f1b57d5.PNG)

and when i use :
```
  banner.on('impression', async (evt) => {
    await banner.hide()
  })

```
the banner is not showing ,

my code : 

```
let banner

var app= {
  initialize: function() {

    document.addEventListener('deviceready', async () => {
        await admob.start()
  	    banner = new admob.BannerAd({
            adUnitId: BannerID,
            size: 'SMART_BANNER'
        })

	//when added this function is hide banner and nothing is showing	
	banner.on('impression', async (evt) => {
            await banner.hide()
        })
        
        await banner.show()

  }, false);

    this.bindEvents();
  },

  bindEvents: function() {
      document.addEventListener('deviceready', this.onDeviceReady, false);
  },

  onDeviceReady: function() {
      app.receivedEvent('deviceready');

  },

};

```
i have **mutiple pages** index1.html index2.html ... and every page it contains a **unique ids** 
please how ican to keep only one banner when load a new Page?

Thank you.
@ratson

**Comment by hisoka-sama** [comment]
reload the page using javascript, but before that you should hide the banner.

**Comment by JLWINC** [comment]
@hisoka-sama  Yes i already reload page every time i open new page , 
how i can to hide banner when open new page ?

i need to use **await banner.hide()** but before that i need to create ad like this   
`banner = new admob.BannerAd({`

i don't know something is wrong !!

**Comment by JLWINC** [comment]
i use this function but is not working `admob.BannerAd.hide();`
i need to call hide banner in the top of script before create the Ad if is already showing in the view , if you have any example I will be grateful to you

**Comment by hisoka-sama** [comment]
```
let banner

var app= {
  initialize: function() {

    document.addEventListener('deviceready', async () => {
        await admob.start()
  	    banner = new admob.BannerAd({
            adUnitId: BannerID,
            size: 'SMART_BANNER'
        })

	//remove this	
	//banner.on('impression', async (evt) => {
        //    await banner.hide()
       // })
        
        await banner.show()

  }, false);

    this.bindEvents();
  },

  bindEvents: function() {
      document.addEventListener('deviceready', this.onDeviceReady, false);
  },

  onDeviceReady: function() {
      app.receivedEvent('deviceready');

  },


var refreshPage = async() => {
     //hide the banner before refreshing the page
      await banner.hide();
      //refresh the page this way or any other way you prefer
      location.reload();
}
//call this when you refresh the page
//await refreshPage();
```

**Comment by JLWINC** [comment]
Thank you , I really appreciate this (y)
