### ISSUE TITLE
Ionic cordova app built as android app bundle doesn't work [Shows white screen] when admob-plus-cordova plugin is installed

### ISSUE THREAD

**Issue by MoAsmar** [admob-plus/admob-plus#512]
**Describe the bug**

Ionic cordova app built for production as android app bundle doesn't work while admob-plus-cordova plugin is installed. The app shows white screen after launch.

**To Reproduce**

1. Create new ionic app with cordova using `ionic start myapp --cordova`
2. Add the plugin using the cli from docs: 
```
ionic cordova plugin add admob-plus-cordova
npm install @admob-plus/ionic
```
3. Generate ionic app bundle using & sign it
`ionic cordova build android --prod --release -- -- --packageType=bundle`
5. Upload the app to google play store and download the apk then run it on device 
Result: app shows white screen

_**Note:** When I remove the plugin "admob-plus-cordova" and uninstall @admob-plus/ionic package, the apk from aab will work normally!_

**Expected behavior**

The app should launch normally not stuck on white screen, when I run` ionic cordova run android` without `--prod --release`flag the app works but in prod and after aab release it doesn't

**Screenshots**
![screen2](https://user-images.githubusercontent.com/8542126/160605265-84439426-76d1-48a1-abc1-c30c8b0fb5ec.jpg)

**Environment**

ionic-info: (coz `npx admob-plus info` doesn't work inside ionic project)
```
Ionic:

   Ionic CLI                     : 6.18.2 (C:\Users\moasmar\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run                             : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\moasmar\AppData\Local\Android\Sdk)
   NodeJS            : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.5.4
   OS                : Windows 10
```

**Additional context**

I need to understand if the implementation I am following is correct or no, is there a specific way to integrate admob-plus in ionic cordova apps and what is it? I am using the ionic docs in my case
![image](https://user-images.githubusercontent.com/8542126/160603991-79d2cd2f-5cca-402d-a581-b92f91a4b479.png)

**Comment by Adrinc** [comment]
did you solved?, I´m stuck with this

**Comment by Iheb-miled** [comment]
Same problem, did you solve it?

**Comment by Adrinc** [comment]
> Same problem, did you solve it?

Did you manage to pass the splash screen? Just adding this plugin and importing it into my app.module.ts  causes the app to freeze after the splash screen. it dosent metter if I build it as .apk or .aab

**Comment by MoAsmar** [comment]
I have used another AdMob plugin to make it work, found no solution with this one

**Comment by boengli** [comment]
@MoAsmar  May I ask which one?
