### ISSUE TITLE
Banner is not width 100%, has space on left and right

### ISSUE THREAD

**Issue by lucaele** [admob-plus/admob-plus#52]
hi all,
bottom banner work bad in test mode and in release production on device.
The banner has space on left and right.

This error on device iPhoneX and in all simulator.

![img_81efb42abbe1-1](https://user-images.githubusercontent.com/10365369/49635478-315e2e80-fa00-11e8-8e91-8c142161bf7f.jpeg)

![img_8e66cbec12b2-1](https://user-images.githubusercontent.com/10365369/49635361-bb59c780-f9ff-11e8-8a49-ba3e519a0a65.jpeg)

I think this is a bug, any idea how solve or fix?

i'm using:
admob-plus @0.17.3
Cordova 8.1.2 (cordova-lib@8.1.1)

**Comment by lucaele** [comment]
Same on admob-plus@0.20.1
same problem in Android and iOS

**Comment by JaredBrown138** [comment]
Is this for all ads? Some ads are like this for me, others span the whole width. It might be due to the adverts banner size. It may be difficult to adjust the size on a per ad basis, not to mention annoying for the user as you would have to increase height to increase width without stretching.

**Comment by lucaele** [comment]
With plugin version 0.24.1 all ads banner is show on 100% width
