### ISSUE TITLE
Wrong Google-Mobile-Ads-SDK major version

### ISSUE THREAD

**Issue by pschorey** [admob-plus/admob-plus#526]
I've followed the Cordova install guide many times, but the Google Mobile Ads SDK keeps being installed at version 9.7.0, and then it won't allow me to build ios because of Swift compile errors in ***/Plugins/admob-plus-cordova/AMBAdBase.swift and elsewhere.

I've tried removing the ios platform, adding the ios platform back, running "pod repo update" and "cd platforms/ios && pod install --repo-update" but I haven't had any luck.

Any assistance would be appreciated.

Below are the npx admob-plus doctor logs:

✔ googleads.g.doubleclick.net
❯ CocoaPods
  ✖ Google-Mobile-Ads-SDK: 9.7.0 != 8.13.0
    › Run `pod repo update`
✔ package.json
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_ANDROID
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_IOS
↓ Cordova Android dependencies [SKIPPED]
✔ config.xml
  ✔ platform[name="ios"]/preference[name="SwiftVersion"]: 5.3
  ✔ platform[name="ios"]/preference[name="deployment-target"]: 11.0
  ✔ ANDROID_SUPPORT_V4_VERSION
✖ Command failed with ENOENT: xcodeproj show --format=tree_hash platforms/ios…
  spawn xcodeproj ENOENT
✔ plugins/admob-plus-cordova/package.json
  ✔ admob-plus-cordova: 1.27.0

**Comment by souly1** [comment]
Related but not same issue:

Need to upgrade Google-Mobile-Ads-SDK version to 9.0> as the current version is using old GoogleAppMeasurement not supported by other plugins moving forward (cordova-plugin-firebasex for example)

Currently removed iOS platform hoping that until I release new iOS version this issue will be somewhat resolved (or I'll rollback cordova-plugin-firebasex version to 14.0.0, not good for Android, but should be fine for iOS)

**Comment by ratson** [comment]
The SDK has been updated in the latest version.
