### ISSUE TITLE
Html5 Game - Needs Help to make this Plugin Works

### ISSUE THREAD

**Issue by VictorHugoDotVn** [admob-plus/admob-plus#53]
Dear All,
Anyone already build this plugin in html5 successful, please help me.
I follow the documentation but seems this plugin only for Ionic or others but no Html5 game.

Please help me. thanks a lot ya.

**Comment by JaredBrown138** [comment]
Yes, this plugin is for Cordova or Cordova based frameworks. You say html5 game so I assume you mean a game in a browser. Why not just use normal ads?

**Comment by VictorHugoDotVn** [comment]
Hi JaredBrown138,
Thanks for reply.
The main reason why i need Admob for the Html5 game is that i want the html5 game to be converted to Android application. This will help user to play offline.
Beside of this, if i not mistaken, google not allow to use adsense for game unless the huge traffic and with written approval.

If you or any one have any advice on how to have admob for html5 game, please help.
Thanks.
