### ISSUE TITLE
upstream dependency conflict issue with latest version 1.24.0

### ISSUE THREAD

**Issue by gilzonme** [admob-plus/admob-plus#532]
**Describe the bug**
After installing `@admob-plus/capacitor` when trying to build capacitor application android it causes the following error

`ionic cap build android  
> npm.cmd i -E @capacitor/android@4.0.1
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @admob-plus/capacitor@1.24.0
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^4.0.0" from @capacitor/browser@4.0.1
npm ERR!   node_modules/@capacitor/browser
npm ERR!     @capacitor/browser@"^4.0.1" from the root project
npm ERR!   peer @capacitor/core@"^4.0.0" from @capacitor/app@4.0.1
npm ERR!   node_modules/@capacitor/app
npm ERR!     @capacitor/app@"4.0.1" from the root project
npm ERR!   9 more (@capacitor/splash-screen, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.6.0" from @admob-plus/capacitor@1.24.0
npm ERR! node_modules/@admob-plus/capacitor
npm ERR!   @admob-plus/capacitor@"^1.24.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @capacitor/core@3.7.0
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^3.6.0" from @admob-plus/capacitor@1.24.0
npm ERR!   node_modules/@admob-plus/capacitor
npm ERR!     @admob-plus/capacitor@"^1.24.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**To Reproduce**
1. Install using `npm i @admob-plus/capacitor`
2. Run `ionic cap build android`

**Comment by ahadjithoma** [comment]
same issue here. Did you solve it?

**Comment by ratson** [comment]
The version range has been relaxed in the latest version.
