### ISSUE TITLE
The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-30).

### ISSUE THREAD

**Issue by mishenThakshana** [admob-plus/admob-plus#534]
I'm getting the following error when I tried to build my project (Capacitor 3 (gradle 7)),

The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.work:work-runtime:2.7.0.
AAR metadata file: C:\Users\Mishen Thakshana\.gradle\caches\transforms-3\86375eee459dc92179683999d6e4da48\transformed\work-runtime-2.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.

**Comment by sergip76** [comment]
I'm getting the same error.

**Comment by wuda-io** [comment]
After running the command
`cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx --variable APP_ID_IOS=ca-app-pub-xxx~xxx`

and then `cordova build` the same issue appears.
How to fix?

**Comment by rapasae** [comment]
Same problem for me with last version 1.28.0.

No problem using 1.27.0 with command `cordova plugin add admob-plus-cordova@1.27.0 --save --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx --variable APP_ID_IOS=ca-app-pub-xxx~xxx`

Perhaps its related with new play services version 20.6.0 used by the last build?

**Comment by wuda-io** [comment]
I guess i solved it by removing android platform and used
`cordova platform add android@11.0.0`

**Comment by 2cool2envy** [comment]
For me 

> Same problem for me with last version 1.28.0 (Cordova package).
> 
> No problem using 1.27.0 with command `cordova plugin add admob-plus-cordova@1.27.0 --save --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx --variable APP_ID_IOS=ca-app-pub-xxx~xxx`
> 
> Perhaps its related with new play services version 20.6.0 used by the last build?

For me 1.27.0 is giving same error @rapasae

**Comment by Silvestar-Iliev** [comment]
For cordova :  I solved this problem by installing cordova platform add android@11.0.0 , but now I have a new problem - it doesn't show the test banner

**Comment by germangc125** [comment]
In my case I have solved it by adding the following line in the config.xml

   <preference name="android-targetSdkVersion" value="31" />
