### ISSUE TITLE
How I can set overlap:true banner?

### ISSUE THREAD

**Issue by gammafp** [admob-plus/admob-plus#54]
How can I get my banner to be placed on top (overlap) of the weview.

**Comment by gammafp** [comment]
@support[bot] when my application generates money I will donate :smile:

**Comment by ratson** [comment]
@gammafp You could already use this plugin for free to earn money. Merry Christmas 😄

**Comment by gammafp** [comment]
@ratson Can I already use overlap:true, you are fast. 
I try use overlap for my game but the banner move up the content of my game.

I solve it change the property of main container (CSS: position: absolute)

https://play.google.com/store/apps/details?id=io.gamma.guineajump

Mery Xmas.

**Comment by gammafp** [comment]
Ok thanks

**Comment by artuska** [comment]
+1

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by matrixreal** [comment]
> @ratson Can I already use overlap:true, you are fast.
> I try use overlap for my game but the banner move up the content of my game.
> 
> I solve it change the property of main container (CSS: position: absolute)
> 
> https://play.google.com/store/apps/details?id=io.gamma.guineajump
> 
> Mery Xmas.

main container of css?
can you be more specific please?
thanks
