### ISSUE TITLE
remove or hide banner not working

### ISSUE THREAD

**Issue by brunoalex** [admob-plus/admob-plus#543]
**Describe the bug**

**To Reproduce**
  let banner

document.addEventListener('deviceready', async () => {
  await admob.start()

  banner = new admob.BannerAd({
    adUnitId: 'ca-app-pub-xxxxx',
  offset: 0,  // overlap with content
  })

  await banner.show()
}, false)

**dont work** : banner.hide();
VM1367:1 Uncaught ReferenceError: banner is not defined

**dont work**:  admob.banner.hide({
 id: {
        android: 'ca-app-pub-XXX/XXX'
      },
 })

VM2295:1 Uncaught TypeError: Cannot read properties of undefined (reading 'hide')
    at <anonymous>:1:14

**so.. i cant hide or destroy the banner :/**

**Comment by EYALIN** [comment]
@brunoalex if you will insert it into the device ready as well, it will work.
the reason for that is that you are trying to hide before the variable is initialized.

**Comment by AbdulRazak-Naeate** [comment]
I am trying to show and hide banner on state change , following your intructions by putting hide function on ondeviceReady but it only shows but hiding the banner , Any thing I might be missing ? .Thank You 
`import React, { useState, useEffect } from 'react';

 const BannerAdmob = ({adUnitId,offset,userconsentStatus,showIntertitialAd,conversionCounts,adsShowalert}) => {
  const [isBannerVisible, setBannerVisible] = useState(false);
  let banner;

  // Initialize the banner once when the component mounts
  useEffect(() => {

    document.addEventListener(
      'deviceready',
      async () => {
        // Initialize the banner ad
        banner =  new admob.BannerAd({
          adUnitId:adUnitId ? `${adUnitId}`:'ca-app-pub-83499458412850/70889387',
          offset: offset ? offset: 120,
          npa:userconsentStatus ? userconsentStatus: 1
        });

        // Listen for the 'impression' event to automatically hide the banner
        banner.on('impression', async () => {
         /*  await banner.hide();
          setBannerVisible(false); // Update state to reflect that the banner is hidden */
        });

        // Automatically show or hide the banner when the state changes
        if (isBannerVisible) {
          await banner.show(); // Show the banner
        } else {
         
          await banner.hide(); // Hide the banner
      
        }
      },
      false
    );

    // Cleanup event listener
    return () => {
            
    };
  }, [isBannerVisible]); // Re-run effect when `isBannerVisible` state changes

  // Function to toggle banner visibility
  const toggleBanner = async () => {
    setBannerVisible((prev) => !prev); // Toggle the visibility state
  };

  return (
    <div>
      <button onClick={toggleBanner}>
        {isBannerVisible ? 'Hide Banner' : 'Show Banner'}
      </button>
    </div>
  );
}
export default BannerAdmob`
