### ISSUE TITLE
Ads dont load if user uncheck all settings in GDPR (ump)

### ISSUE THREAD

**Issue by tomitank** [admob-plus/admob-plus#544]
I got below message in Android Studio after i uncheck all option in GDPR modal.

I/Ads: Ad failed to load : 3
I/Ads: Ad failed to load : 3
D/SystemWebChromeClient: file:///android_asset/www/plugins/admob-plus-cordova/www/admob.js: Line 78 : Uncaught (in promise) {
      "Code": 3,
      "Message": "No ad config.",
      "Domain": "com.google.android.gms.ads",
      "Cause": "null",
      "Response Info": {
        "Response ID": "null",
        "Mediation Adapter Class Name": "",
        "Adapter Responses": []
      }
    }
I/chromium: [INFO:CONSOLE(78)] "Uncaught (in promise) {
      "Code": 3,
      "Message": "No ad config.",
      "Domain": "com.google.android.gms.ads",
      "Cause": "null",
      "Response Info": {
        "Response ID": "null",
        "Mediation Adapter Class Name": "",
        "Adapter Responses": []
      }
    }", source: file:///android_asset/www/plugins/admob-plus-cordova/www/admob.js (78)

**Comment by TheNotorius0** [comment]
Oh, so THAT is causing the **No ad config.** error? I've got a few reports and logs from users that couldn't load ads (with **"Message": "No ad config."**), but couldn't figure out what was the cause.

**Comment by TheNotorius0** [comment]
Ok, just tested with a test ad, it's true. If a user click **Do not consent**  the ad won't load, and the user will get a **No ad config** error (which defeats the point of having a consent popup, if they have to opt-in to watch an ad)

**Comment by repotoolsapps** [comment]
I have the same problem, Ads are not shown when removing everything.

**Comment by DevloCore** [comment]
Hello, same here. Ads are not loading if the user do not consent all.
I noticed that when the user clicks "customize" without checking/unchecking any option in UMP message, and then he clicks validate, no ads will be loaded.

**Comment by hooliapps** [comment]
> Ok, just tested with a test ad, it's true. If a user click **Do not consent**  the ad won't load, and the user will get a **No ad config** error (which defeats the point of having a consent popup, if they have to opt-in to watch an ad)
> 
> 
> 
> Edit: maybe only users with the consentStatus **Required** or **Obtained** should be able to click the "Do not consent" button. If it's not required, you shouldn't display the Popup, and you shouldn't show an option to change Ads consent (so don't show the ad consent popup and don't let the users change their ad consent status, unless their status is Required / Obtained. The problem seems **disappeared** now)

Hello, do you have any javascript example to do that please ?

**Comment by TheNotorius0** [comment]
> > Ok, just tested with a test ad, it's true. If a user click **Do not consent**  the ad won't load, and the user will get a **No ad config** error (which defeats the point of having a consent popup, if they have to opt-in to watch an ad)
> > Edit: maybe only users with the consentStatus **Required** or **Obtained** should be able to click the "Do not consent" button. If it's not required, you shouldn't display the Popup, and you shouldn't show an option to change Ads consent (so don't show the ad consent popup and don't let the users change their ad consent status, unless their status is Required / Obtained. The problem seems **disappeared** now)
> 
> Hello, do you have any javascript example to do that please ?

When clicking an Ad:

```
checkAndShowConsent().then(() => {

    const rewarded = new admob.RewardedAd({
        adUnitId: id
    });
}
```
```
async function checkAndShowConsent() {

    const consentStatus = await consent.getConsentStatus();

    if (consentStatus === consent.ConsentStatus.Required) {

        await consent.requestInfoUpdate();

    } else {

        return false;
    }

    const formStatus = await consent.getFormStatus();

    if (formStatus === consent.FormStatus.Available) {

        const form = await consent.loadForm();
        return await form.show();

    } else {

        return false;
    }
}
```

**Comment by matrixreal** [comment]
> > > Ok, just tested with a test ad, it's true. If a user click **Do not consent**  the ad won't load, and the user will get a **No ad config** error (which defeats the point of having a consent popup, if they have to opt-in to watch an ad)
> > > Edit: maybe only users with the consentStatus **Required** or **Obtained** should be able to click the "Do not consent" button. If it's not required, you shouldn't display the Popup, and you shouldn't show an option to change Ads consent (so don't show the ad consent popup and don't let the users change their ad consent status, unless their status is Required / Obtained. The problem seems **disappeared** now)
> > 
> > 
> > Hello, do you have any javascript example to do that please ?
> 
> When clicking an Ad:
> 
> ```
> checkAndShowConsent().then(() => {
> 
>     const rewarded = new admob.RewardedAd({
>         adUnitId: id
>     });
> }
> ```
> 
> ```
> async function checkAndShowConsent() {
> 
>     const consentStatus = await consent.getConsentStatus();
> 
>     if (consentStatus === consent.ConsentStatus.Required) {
> 
>         await consent.requestInfoUpdate();
> 
>     } else {
> 
>         return false;
>     }
> 
>     const formStatus = await consent.getFormStatus();
> 
>     if (formStatus === consent.FormStatus.Available) {
> 
>         const form = await consent.loadForm();
>         return await form.show();
> 
>     } else {
> 
>         return false;
>     }
> }
> ```

Hello,
I did try the following but it not work
create cordova project
add this plugin and consent plugin
add ios platform
make sure that the app id is correct on info.plist and banner but it not work
can you help?
thanks

**Comment by fredriksthlm** [comment]
This is how it works for everyone, and how it is supposed to work. There has been discussions about this for years.

https://groups.google.com/g/google-admob-ads-sdk/c/UcveWmtBm4Q/m/QOezaayMAwAJ

**Comment by ratson** [comment]
Close as nothing I can do.

**Comment by tomitank** [comment]
i use this now:
`admob.interstitial.on('loadfail', function(e) {
	resetConsentStatusAndShowAgain();
});
function resetConsentStatusAndShowAgain() {
if (navigator.connection.type != Connection.NONE)
	consent.getConsentStatus().then(function(consentStatus) {
		if (consentStatus === consent.ConsentStatus.Obtained) {
			admob.ready = false;
			consent.reset();
			safeAdmobInit();
		}
	});
}
`
