### ISSUE TITLE
Is that possible to set Ads between content 

### ISSUE THREAD

**Issue by sonugpc** [admob-plus/admob-plus#55]
Hi, is that possible to put an ad between content like if there is a post I want to put an add before post of slider area means custom location with different sizes?

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by ratson** [comment]
Duplicate to https://github.com/admob-plus/admob-plus/issues/54
