### ISSUE TITLE
Build failed after adding admob-plus-cordova plugin

### ISSUE THREAD

**Issue by CONSTRUCTPRO** [admob-plus/admob-plus#553]
## Please help
didn't fix even after adding
`
<platform name="android">
    <preference name="AndroidXEnabled" value="true" />
</platform>
`
to config.xml

using latest gradle & cordova & android studio versions

`error details :`
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Picked up _JAVA_OPTIONS: -Xmx1G
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
`> Task :app:checkDebugAarMetadata FAILED`

`FAILURE: Build failed with an exception.`

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: C:\.gradle-7.1.1\bin\caches\transforms-3\8bdba0aef32e26b04c7a380b76c30e51\transformed\work-runtime-2.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
9 actionable tasks: 9 executed
Command failed with exit code 1: C:\Users\Workspace\Desktop\ad\platforms\android\gradlew cdvBuildDebug -b C:\Users\Workspace\Desktop\ad\platforms\android\build.gradle

**Comment by Silvestar-Iliev** [comment]
I have the same problem, if anyone can help I would appreciate it.

**Comment by Silvestar-Iliev** [comment]
I solved this problem by installing cordova platform add android@11.0.0 , but now I have a new problem - it doesn't show the test banner

**Comment by EYALIN** [comment]
@Silvestar-Iliev This plugin is not maintained anymore, please move to the maintained one.
you can follow this post: https://github.com/admob-plus/admob-plus/issues/574

using the new one will fix your issue

**Comment by ratson** [comment]
The error suggest your `compileSdkVersion` is 30, which is old than 31.

```
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
```
try 
```xml
<preference name="android-targetSdkVersion" value="33" />
```
