### ISSUE TITLE
iPhone Notch - background color

### ISSUE THREAD

**Issue by lucaele** [admob-plus/admob-plus#56]
Hi all,
i'm using plugin version 0.24.1,
on iPhone X with notch and banner on bottom,
the background of safe-area on bottom is white.

How can i change the color of safe-area?
Is there any param on plugin for customize it?

Thanks,
Luca

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by ratson** [comment]
Close as related to the old version.
