### ISSUE TITLE
Invalid activity and confirmed click after using admob-plus

### ISSUE THREAD

**Issue by AlinAssus** [admob-plus/admob-plus#565]
Hello to everyone,

Last year, in December I've updated my apps to use admob-plus cordova plugin(previously I was serving admob ads using cordova-plugin-admob-free). After a few days  with the plugin my CTR dropped to nearly 0% for the Android version and on iOS I received a notification that there are issues with the banner and that Confirmed Clicks are in place for it.

I've contacted Admob support and the only thing they could tell me is that there appears to be invalid activity but nothing certain. Also worth mentioning is that in the Policy Center I only see the confirmed click issue but nothing related to the invalid activity.

I need to mention that there were no changes in positioning the ads or the number of times it was displayed and I've never had any issues in the past with admob policy. These are apps that are on the store from 2016 with no other issues in the past. The issues appeared right after the update with the latest version of the admob-plus plugin.

Did anyone else had any similar issue after using the admob-plus plugin?

**Comment by netlob** [comment]
same here, been having that issue for the past 2 years

**Comment by ratson** [comment]
@AlinAssus @netlob You are welcome the audit the code, I would rather happy to accept fixes than something I cannot verify.
Also, check your code and other plugins too.

Close as nothing I could do.
