### ISSUE TITLE
How to hide or remove a banner?

### ISSUE THREAD

**Issue by gmbad** [admob-plus/admob-plus#572]
I Try:

admob.banner.hide({
      android: 'ca-app-pub-3940256099942544/6300978111'
 });

But it does not work. Error: hide is not a function.

I would like to remove banner and add it again, when I change or refresh page...

Can someone help me?

Thanks!!

**Comment by EYALIN** [comment]
@gmbad This plugin is not maintained anymore, please move to the maintained one.
you can follow this post: https://github.com/admob-plus/admob-plus/issues/574

using the new one will fix your issue

**Comment by EYALIN** [comment]
@gmbad add async and it will work

**Comment by ratson** [comment]
@gmbad see https://admob-plus.github.io/docs/cordova/ads/banner/
`admob.banner.hide` is the old API.
