### ISSUE TITLE
This plugin has a maintained repo now - please use and follow

### ISSUE THREAD

**Issue by EYALIN** [admob-plus/admob-plus#574]
unfortunately, this plugin creator @ratson, did fantastic work, and we highly appreciate him not maintaining this plugin anymore (not responding for a while).
we moved to a maintained plugin (which forked from this one) to here:
https://github.com/EYALIN/community-admob-plus

you can install it as an npm package:
cordova plugin add community-admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub-XXX --variable APP_ID_IOS=XXX

**If someone needs support with other packages such capacitor, please let us know in the new GitHub repo** "https://github.com/EYALIN/community-admob-plus"

**Comment by Amaeta** [comment]
Finally added @EYALIN community-admob-plus-cordova, tried to build on Chrome and console output: Channel not fired: onAdMobPlusReady

**Comment by A32rj3gebebr** [comment]
Are both SDKs (iOS and Android) up to date?

**Comment by EYALIN** [comment]
@A32rj3gebebr Yes, and tested for a while.

**Comment by Calsy** [comment]
Thank you Eyalin for stepping in and keeping this plugin alive.  Very much appreciated.

**Comment by Winamp9** [comment]
Thank you very much. Are all instructions from [admob-plus.github.io](https://admob-plus.github.io/) up to date?

**Comment by Amaeta** [comment]
Please help.
@EYALIN thanks for the work you did with the community
I have sorted out the admob native.  It displays but sometimes it crashes my app (guess when it is not loaded). My code is 
 if(ad.showfail || ad.loadfail){
	   //ad.show();
	  }else{
		new Promise(function(resolve){
        setTimeout(function() {
		ad.hide();
        resolve();
		
		}, 12000);
		});
		ad.showWith(document.getElementById('nativeads'));
		ad.load();
		}

How can I catch the error? Please help!

**Comment by ratson** [comment]
@EYALIN Thank you for creating the fork for those needed the updates.
As the latest commits and alpha release provides the same features as your forks, I'm closing this.
For those prefer the fork, feel free to use the fork and support @EYALIN  work.

**Comment by EYALIN** [comment]
@ratson  thank god you are back :-) 
will set a sponsorship to you right now ( a monthly one this time)

**Comment by Nuesret** [comment]
Hey EYALIN!! Please help me out!!! Can't get the plugin work... what am I doing wrong?! Please don't tell me, that I have to add the "let banner" snippet into the MainActivity file... I added it into the headers of the assets/html files...

...ended here:
Argh! It's not working... what am I doing wrong?

This is the situation:

1. made my webproject in html-css-javascript
2. build the corona project and added all components: the admob-plus plugin and androidx adapters
3. imported the android folder in Android Studio, synced and added the necessary meta.data in manifest.xml
4. implemented the abdmob code in MainActivity.java and checked gradle.build for actual google ads lib
5. added the let banner snippets to the html headers in assets
```
let banner

document.addEventListener('deviceready', async () => {
banner = new admob.BannerAd({
adUnitId: 'ca-app-pub-xxx/yyy',
})

banner.on('impression', async (evt) => {
await banner.hide()
})

await banner.show()
}, false)
```
Result: the banner is jumping in and out and stays after an amount of time (at least, if you revisit the page again). 
If I change the code in
```
let banner

document.addEventListener('deviceready', async () => {
banner = new admob.BannerAd({
adUnitId: 'ca-app-pub-xxx/yyy',
})

banner.on('impression', async (evt) => {
await banner.hide()
})

await banner.show()
}, true)
```
...the banner is showing up and stays. BUT... this works fine as long as the user opens the pages in a linear way. If he revisits the page - the same banner duplicates itself and jump over the old one: now we see two identical banners at the bottom. This goes on and on... till the whole page is covered with the same banner.

Hey guys, how do you manage it to work? Did I forget to add code somewhere? Please help. I need really help.

Found this but it isn't working
[https://github.com/admob-plus/admob-plus/issues/450](url)

**Comment by Shugarlipz** [comment]
Please, my app keeps crashing after adding the plugin, I'm new to this and I have done all the necessary thing's I feel will make it work yet is still crashing.

**Comment by Nuesret** [comment]
> Please, my app keeps crashing after adding the plugin, I'm new to this and I have done all the necessary thing's I feel will make it work yet is still crashing.

If I understand you correctly, you compile your HTML-CSS-JS pages using Cordova and then insert the Admob plus plugin here as well? What exactly is the problem? Do you end up with an .apk or .app file from Cordova that crashes? Or did you import your Cordova project into Android Studio and edit and compile it there?

**Comment by Shugarlipz** [comment]
I compiled HTML, CSS and JavaScript file using Cordova, after building an
apk.file it was working perfectly but immediately I added the
admob-plus-cordova plugin, it started crashing. Once I remove the plugin
again, it will start working fine, I built an apk file to test it.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Did you enable AndroidX and Kotlin in config.xml ?


________________________________

**Comment by Nuesret** [comment]
Yes, androidx is neccessary. You have to use the latest versions of cordova, node.js etc.

**Comment by Shugarlipz** [comment]
I only enabled AndroidX in config.xml but I didn't enable kotlin

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
Without Kotlin it will not work.

It won't crash the app, I think, but ads are not shown.

Just search in this Git for "config.xml kotlin" to see how to enable it.

It's pretty easy and basics.


________________________________

**Comment by Shugarlipz** [comment]
I added the kotlin plugin and is still crashing, please is there anyhow I
can solve this?
