### ISSUE TITLE
👀 Guess who's back? Ratson back (version troubles)

### ISSUE THREAD

**Issue by 1n3JgKl9pQ6cUMrW** [admob-plus/admob-plus#578]
**After months of waiting, it seems Ratson is alive and back after the keyboard** 👍

---

In the meantime the community also updated this plugin with a major bump to the used Android SDK's (from `20` to `22`).

But what I noticed (after Ratson just committing some [minor codechanges](https://github.com/admob-plus/admob-plus/commit/136ef5dcf1a0623a80811bbb4c4fa565c01c7601)) is that the original version of this plugin already had version 22 for Android all the time.

- The thing is that `version 1.28` of this plugin had `Google Play Services 20` (updated in August 2022).
- But a month later, the SDK was [updated](https://github.com/admob-plus/admob-plus/blob/d263f9c73bad1f8d4dc5a802ddd98caf431e9f16/packages/cordova/plugin.xml) to `version 22` while the plugin version still was `1.28`.

---

So maybe many of us didn't see this major update, because the plugin itself seemed the same.

On the other hand, when I install the plugin (the original one), I still see / get the old SDK version (`20.x`)

`cordova plugin add admob-plus-cordova --variable APP_ID_ANDROID="ca-app-pub-xxx~xxx"`

But the `plugin.xml` clearly states `version 22.x`.

[Plugin.xml](https://github.com/admob-plus/admob-plus/blob/d263f9c73bad1f8d4dc5a802ddd98caf431e9f16/packages/cordova/plugin.xml
)

_So maybe this repo and NPM are not in sync?_

**Comment by EMI-INDO** [comment]
@1n3JgKl9pQ6cUMrW 

Yes he's back, I'm happy to hear this news.
