### ISSUE TITLE
Native Ad Make App Performance Very Slow

### ISSUE THREAD

**Issue by sakuraiyhl** [admob-plus/admob-plus#579]
Hi,

I have develop ionic app that need native ad to support it. I have follow all the instruction from https://admob-plus.github.io/ and success display native ad on mobile. but i have realize that have 2 critical issue after implement it.

Issue
1. The native ad will display on the place that set it but after scroll the page it still remain on same position. The method that i use to display is Attach to HTML.
2. The app performance will become slow after few times leave the native ad page, then go back to that page again. 

Expected behavior
Native Ad implement will not slow down app performance and ad can show on correct position after scroll the page.

Environment
Android 8.0 / Android 12.0

**Comment by ratson** [comment]
It is the limitation on using the native ad as it is an overlay on top of the webview.
If anyone find a way to optimize that, feel free to send a PR.
