### ISSUE TITLE
Could not install the plugin

### ISSUE THREAD

**Issue by DoruLaz** [admob-plus/admob-plus#58]
### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Memory: 1.73 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 2.15.12 - ~/Desktop/OQ/omniquiz/node_modules/.bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    Languages:
      Java: 1.7.0 - /usr/bin/javac
    npmPackages:
      cordova: ~6.4.0 => 6.4.0 
      cordova-admob-plus: ^0.24.1 => 0.24.1 
      cordova-android: ~6.3.0 => 6.3.0 
      cordova-ios: ~4.3.1 => 4.3.1 
    npmGlobalPackages:
      cordova: 8.0.0
      ionic: 3.20.0

### Steps to Reproduce

1. cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-xxxxxx/xxxxxx --variable APP_ID_IOS=ca-app-pub-xxxxxx/xxxxxx

### Expected Behavior

Should install the plugin. 

### Actual Behavior

Installing "cordova-admob-plus" for ios
Installing "cordova-plugin-add-swift-support" for ios
Failed to install 'cordova-admob-plus': undefined
(node:3294) UnhandledPromiseRejectionWarning: /bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

(node:3294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JaredBrown138** [comment]
You need to have ruby and cocoapods installed on your machine when installing on a mac or building for ios. Not sure exactly why you are getting this issue but it looks like it is an issue with your ruby installation. This may help: https://stackoverflow.com/questions/8864668/getting-a-bad-interpreter-error-when-using-brew

**Comment by DoruLaz** [comment]
@JaredBrown138 Thank you very much for pointing me in the right direction. After days of headbanging while trying to re-install cocoapods, I wiped the mac clean and re-installed everything, and now it's working.

This issue can be closed. BTW, @ratson  thanks for the awesome plugin. I will surely donate once I manage to get some funds from commercials.

**Comment by jespertheend** [comment]
I'm having the same issue. `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby` does indeed not exist. 2.6 does though (`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby)

**Comment by jespertheend** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8955

**Comment by jespertheend** [comment]
```
brew install cocoapods --build-from-source
brew link --overwrite cocoapods
```
fixed it for me
