### ISSUE TITLE
After update to 2.0.0-alpha.3 version

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#584]
I tried to use my old Admob code to display banner ads, it worked for the previous versions but not worked for this latest version even though it did not show any errors. The code is given below.

```
document.addEventListener("deviceready", initAds, false);

var _bannerAd;
function initAds()
{

   _bannerAd = new admob.BannerAd({
     adUnitId: 'ca-app-pub-3940256099942544/6300978111'
  });
  _bannerAd.load();
}
```

**Comment by ratson** [comment]
@merbin2012 Would you provide the output of `npx admob-plus info` and `npx admob-plus doctor`?

**Comment by merbin2012** [comment]
@ratson Please wait I will give you the result

**Comment by merbin2012** [comment]
Already I installed the Cordova plugin but again it ask me to install it,
![image](https://github.com/admob-plus/admob-plus/assets/3687184/aea3cf1c-d7b4-4e9d-902b-3e558a515701)

**Comment by merbin2012** [comment]
Please see the following result
**npx admob-plus info**
AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.19045
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 18.01 GB / 31.96 GB
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE    
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD      
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD       
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 23.0.1, 23.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.2
        System Images: android-16 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    Languages:
      Java: 15.0.2
    npmPackages:
      admob-plus-cordova: 2.0.0-alpha.3 => 2.0.0-alpha.3
      cordova-android: ^12.0.0 => 12.0.0
      cordova-plugin-codeplay-share-app-link: 0.0.2 => 0.0.2
      cordova-plugin-dialogs: ^2.0.2 => 2.0.2
      cordova-plugin-file: ^7.0.0 => 7.0.0
      cordova-plugin-spinner: ^1.1.0 => 1.1.0
      cordova-plugin-x-toast: ^2.7.3 => 2.7.3
    Cordova:
      Version: 12.0.0 (cordova-lib@12.0.1)
      Plugins:
        cordova-plugin-codeplay-share-app-link: 0.0.2
        cordova-plugin-x-toast: ^2.7.3
        cordova-plugin-file: ^7.0.0
        cordova-plugin-spinner: ^1.1.0
        cordova-plugin-dialogs: ^2.0.2
        admob-plus-cordova: 2.0.0-alpha.3
    Ionic:
      Version: -
    AndroidManifest.xml:
      Version: -
	  


**npx admob-plus doctor**
![image](https://github.com/admob-plus/admob-plus/assets/3687184/0dbf2297-b001-4ecb-bcfc-e95068c76ab5)

**Comment by ratson** [comment]
@merbin2012  Do you see any error in `adb logcat"?

**Comment by merbin2012** [comment]
@ratson Sorry, I don't know how to detect the error in Logcat it just scrolls infinitely. I have not seen any error in inspect element. If I directly call the ad, it shows pending.



![image](https://github.com/admob-plus/admob-plus/assets/3687184/93d84d24-f85e-4e10-9d31-eef3e3abcca2)

**Comment by merbin2012** [comment]
@ratson Okay Thanks, I will immediately check and let you know the details.

**Comment by merbin2012** [comment]
@ratson Please check screenshot, in the next message ill attach the whole logs

![image](https://github.com/admob-plus/admob-plus/assets/3687184/563f0121-595f-4fd4-a062-f1479bb4f207)

**Comment by ratson** [comment]
@merbin2012 It seems the plugin is not installed correctly.
Did you check https://admob-plus.github.io/docs/cordova/upgrade ?

**Comment by merbin2012** [comment]
@ratson Thank you now it is working. Please clear my another doubt.

I am not understood "Remove ad-type specific events They are replaced with admob.ad.* events."

Currently I am using the following
//Admob Events
//Google Banner Ads Events
admob.banner.load
admob.banner.loadfail
admob.banner.impression
admob.interstitial.load
admob.interstitial.loadfail
admob.interstitial.show
admob.interstitial.dismiss
admob.ad.load
admob.ad.loadfail
admob.ad.dismiss
admob.ad.show
admob.rewarded.load
admob.rewarded.loadfail
admob.rewarded.reward
admob.rewarded.show
admob.rewarded.dismiss

How should I use this? I checked "admob-plus-cordova\www\generated.js" in this file both are the same, but the events are not triggered.

**Comment by ratson** [comment]
```
admob.banner.load
admob.banner.loadfail
admob.banner.impression
admob.interstitial.load
admob.interstitial.loadfail
admob.interstitial.show
admob.interstitial.dismiss
admob.rewarded.load
admob.rewarded.loadfail
admob.rewarded.reward
admob.rewarded.show
admob.rewarded.dismiss
```
These events are removed.

**Comment by merbin2012** [comment]
Which one should I use instead of these events?

**Comment by merbin2012** [comment]
@ratson Thank you got it, I will check it later.
