### ISSUE TITLE
google-services plugin version conflict

### ISSUE THREAD

**Issue by Danitrebu** [admob-plus/admob-plus#59]
### Is this a bug report?

No, just an error?

### Environment

  AdMob Plus Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
      Memory: 2.96 GB / 7.88 GB
    Binaries:
      Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

cordova: 8.0.0
ionic: 4.0.3
cordova plugins: {
  "cordova-plugin-whitelist": "1.3.3",
  "cordova-plugin-device": "2.0.2",
  "cordova-plugin-splashscreen": "5.0.2",
  "cordova-plugin-ionic-webview": "^2.0.0",
  "cordova-plugin-ionic-keyboard": "^2.0.5",
  "phonegap-plugin-push": "^2.1.3",
  "cordova-admob-plus": "^0.24.1"
}

AndroidManifest.xml: looks ok

### Steps to Reproduce

1. ionic cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=my_id_is_here APP_ID_IOS=my_id_is_here
2. npm install --save ionic-admob
3. add provider on app.module
4. call showBannerAd on app.component's platform.ready function:
```
showBannerAd(){
    this.admob.banner.show({
      id: {
        android: 'my_id_is_here',
        ios: 'test'
      }
    })
  }
```

### Expected Behavior

Build and test the app

### Actual Behavior

Error info is kinda clear, but I don't know how to make it work. I had this error time ago with firebase push plugin, and had to change versions manually on project.properties to 11.6.2. Now that I installed admob-plus, another line appeared with 17.1.2

My project.properties now:
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-base:11.6.2
cordova.system.library.2=com.google.android.gms:play-services-ads:11.6.2
cordova.system.library.3=com.android.support:support-v13:26.+
cordova.system.library.4=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.5=com.google.firebase:firebase-messaging:11.6.2
cordova.gradle.include.1=phonegap-plugin-push/starter-push.gradle
cordova.system.library.6=com.google.android.gms:play-services-ads:17.1.2 # duplicated line with another version

Error info:
What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

### Reproducible Demo

Just follow the steps above, I did nothing special. Will edit with github repository if needed, have to go as soon as I submit this issue.

**Comment by Danitrebu** [comment]
I finally gave up. Started a whole new project with AdMob Plus and OneSignal instead of Firebase and Push (just wanted to give OneSignal a try). Still waiting for a reply to try and fix the old project. The banner is showing but it's only a grey square. I'll just wait to see if it get shown in some hours

**Comment by IamMarek** [comment]
I've solved it by adding a following code into platforms/android/app/build.gradle file. 

`configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
    }
}
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
