### ISSUE TITLE
Error: exec proxy not found for :: AdMob :: interstitial_load

### ISSUE THREAD

**Issue by isularifin** [admob-plus/admob-plus#6]
i have installed this plugin in cordova 8.0.0. But i have got error on browser console like this....
`Error: exec proxy not found for :: AdMob :: interstitial_load  cordova.js:1004:9
Error: exec proxy not found for :: AdMob :: ready  cordova.js:1004:9
uncaught exception: Missing Command Error  admob.js:159:13`

What can i do? Thanks alot before

**Comment by ratson** [comment]
As you mention `browser console`, are you running on browser? Did you try the examples in this repo and see the same error?

I will look into it if you create an example repo and instructions to re-create the error.

**Comment by isularifin** [comment]
thanks  alot for the respon ratson.

Yes. I am running it on browser. 
I have tried running the example that you point but i got error like this on....
`Received Event: deviceready  index.js:34:5
Error: exec proxy not found for :: AdMob :: banner_show  cordova.js:1004:9
Error: exec proxy not found for :: AdMob :: interstitial_load  cordova.js:1004:9
Error: exec proxy not found for :: AdMob :: reward_video_load  cordova.js:1004:9
Error: exec proxy not found for :: AdMob :: ready  cordova.js:1004:9
uncaught exception: Missing Command Error admob.js:159:13`

And i have tried to build it with android platform and failed.....
`:app:compileDebugJavaWithJavac/home/user/cordova_project/admobplus2/platforms/android/app/src/main/java/admob/plugin/AdMob.java:60: error: incompatible types: Object cannot be converted to JSONObject
            JSONObject opts = args.opt(0);
                                      ^
/home/user/cordova_project/admobplus2/platforms/android/app/src/main/java/admob/plugin/AdMob.java:67: error: incompatible types: boolean cannot be converted to float
            MobileAds.setAppVolume(true);
                                   ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
27 actionable tasks: 5 executed, 22 up-to-date
(node:1685) UnhandledPromiseRejectionWarning: Error: /home/user/cordova_project/admobplus2/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/user/cordova_project/admobplus2/platforms/android/app/src/main/java/admob/plugin/AdMob.java:60: error: incompatible types: Object cannot be converted to JSONObject
            JSONObject opts = args.opt(0);
                                      ^
/home/user/cordova_project/admobplus2/platforms/android/app/src/main/java/admob/plugin/AdMob.java:67: error: incompatible types: boolean cannot be converted to float
            MobileAds.setAppVolume(true);
                                   ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
    at ChildProcess.whenDone (/home/user/cordova_project/admobplus2/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:1685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by ratson** [comment]
@isularifin Added dummy implementation for browser platform, so it does not cause error, but doing nothing. The Android problem is fixed since v0.2.0.

**Comment by isularifin** [comment]
thanks
