### ISSUE TITLE
admob.start() not working on Vue Cordova

### ISSUE THREAD

**Issue by yusuf1980** [admob-plus/admob-plus#607]
onMounted( () =>  {
    let banner;
    document.addEventListener('deviceready', async () => {
        
        await admob.start() // or start loading ads
        console.log(admob)
        
        banner = new admob.BannerAd({
            adUnitId: 'ca-app-pub-......',
            position: 'bottom',
            offset: 0,
        })

        banner.on('impression', async (evt) => {
            await banner.hide()
        })

        await banner.show()
        console.log('show')
    }, false)
})

**Comment by kapchew** [comment]
I face the same problem too. Any pointers?

**Comment by kapchew** [comment]
You need to enable Kotlin support https://admob-plus.github.io/docs/cordova/upgrade

**Comment by yusuf1980** [comment]
> You need to enable Kotlin support https://admob-plus.github.io/docs/cordova/upgrade

It's work, thank you.
