### ISSUE TITLE
Can't install plugin in cocoon.io

### ISSUE THREAD

**Issue by evilcoder04** [admob-plus/admob-plus#61]
When I install this plugin on cocoon.io and compile the project I always get this error:

Platform: Android only

COMPILER ERROR: /workspace/platforms/android/gradlew: Command failed with exit code 1 Error output: FAILURE: Build failed with an exception.

* Where: Build file '/workspace/platforms/android/build.gradle' line: 252

* What went wrong: A problem occurred evaluating root project 'android'. > Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CORDOVA LOG: [36m20190105T234157 [DEBUG] AndroidBuilder -[39m [prepare] cordova restore platforms [36m20190105T234157 [DEBUG] AndroidBuilder -[39m [prepare] adding engine android@6.2.3 Subproject Path: CordovaLib Subproject Path: CordovaLib (node:31903) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global' [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [prepare] cordova restore plugins [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.defaultres.android@1.0.1 [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.installlocation.android@1.0.0 [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-admob-plus@* [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-whitelist@1 [36m20190105T234207 [DEBUG] AndroidBuilder -[39m [build] Warning: File /.android/repositories.cfg could not be loaded. [36m20190105T234209 [DEBUG] AndroidBuilder -[39m [build] call cordova ANDROID_HOME=/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux JAVA_HOME=/usr/lib/jvm/default-java Subproject Path: CordovaLib The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead. at build_bn80sr2p3qn85nl67pfyv7g3j.run(/workspace/platforms/android/build.gradle:137) FAILURE: Build failed with an exception. * Where: Build file '/workspace/platforms/android/build.gradle' line: 252 * What went wrong: A problem occurred evaluating root project 'android'. > Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. BUILD FAILED Total time: 0.959 secs [91m20190105T234213 [ERROR] AndroidBuilder -[39m { Error: /workspace/platforms/android/gradlew: Command failed with exit code 1 Error output: FAILURE: Build failed with an exception. * Where: Build file '/workspace/platforms/android/build.gradle' line: 252 * What went wrong: A problem occurred evaluating root project 'android'. > Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. at ChildProcess.whenDone (/workspace/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5) stderr: '\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file \'/workspace/platforms/android/build.gradle\' line: 252\n\n* What went wrong:\nA problem occurred evaluating root project \'android\'.\n> Could not get unknown property \'PLAY_SERVICES_VERSION\' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n', stdout: 'The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.\n\tat build_bn80sr2p3qn85nl67pfyv7g3j.run(/workspace/platforms/android/build.gradle:137)\n\nBUILD FAILED\n\nTotal time: 0.959 secs\n', code: 1 }

I think it has something to do with PLAY_SERVICES_VERSION which.

**Comment by ratson** [comment]
@evilcoder04 Should you ask the support of cocoon.io for explanation / help?
Maybe then they could PR a fix, I don't know how to fix for their platform.

**Comment by ratson** [comment]
Close as the service is closed, https://blog.cocoon.io/shutting-down-cocoon/
