### ISSUE TITLE
Consent not return any value for some of my apps

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#621]
I have more apps, but it works for most apps, but in some applications, the **await** method does not return any value, so the next statement is not executing and does not initialize the ads. Please see the screenshot below.

Note: I have done all the details in the admob account.

![image](https://github.com/admob-plus/admob-plus/assets/3687184/a6dd6951-eb5a-4917-9a93-27c750170137)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
`consent.trackingAuthorizationStatus()` is for iOS only, Android doesn't use / return any value.

May that's it?

**Comment by merbin2012** [comment]
@1n3JgKl9pQ6cUMrW Sorry this is my mistake, I am not adding the following line in config.xml

`<preference name="GradlePluginKotlinEnabled" value="true" />`
