### ISSUE TITLE
CocoaPods is conflicting when installed cordova-plugin-consent

### ISSUE THREAD

**Issue by DesignerApparelSales** [admob-plus/admob-plus#624]
CocoaPods is conflicting when installed cordova-plugin-consent and admob-plus together. Its seem like they are using different version of CocoaPods.  I get this error,  UserError: [!] CocoaPods could not find compatible versions for pod "GoogleUserMessagingPlatform":
  In snapshot (Podfile.lock):
    GoogleUserMessagingPlatform (= 2.1.0, >= 1.1)

**Comment by EYALIN** [comment]
@DesignerApparelSales did you try my forked plugin ?
https://github.com/EYALIN/community-admob-plus/tree/master/packages/cordova

think it will solve your issue

**Comment by DesignerApparelSales** [comment]
I have fixed the issue. I rearranged my plugin build order. So i placed the, plugin name=“cordova-plugin-consent” source=“npm”, before ,plugin name=“admob-plus-cordova” source=“npm” , in the config.xml and there was no error.
