### ISSUE TITLE
Error on consent "Uncaught (in promise) Method must be call on main thread"

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#637]
I have use the following code
```
 if (cordova.platformId === 'ios') {
    const status = await consent.trackingAuthorizationStatus()
    /*
      trackingAuthorizationStatus:
      0 = notDetermined
      1 = restricted
      2 = denied
      3 = authorized
    */
    const statusNew = await consent.requestTrackingAuthorization()
  }

  const consentStatus = await consent.getConsentStatus()
  if (consentStatus === consent.ConsentStatus.Required) {
    await consent.requestInfoUpdate()
  }

  await consent.loadAndShowIfRequired()

  if (await consent.canRequestAds()) {
    // request ads

		_bannerAd = new admob.BannerAd({
			adUnitId: _adUnitId.bannerid
		});
.....
```

But it shows the following error "Uncaught (in promise) Method must be called on main thread." in this "await consent.loadAndShowIfRequired()" line.

![image](https://github.com/admob-plus/admob-plus/assets/3687184/fc9f1f78-93fe-47e1-9c01-82afe68b1ec4)

**Comment by EYALIN** [comment]
i have it too. 
@ratson can you help us here?

**Comment by merbin2012** [comment]
Thank you

**Comment by undergroundcreative** [comment]
At what point do you guys call await consent.canRequestAds() ?

I always get an error using:

```
try {
   canRequestAds = await consent.canRequestAds();
}
catch(e){
   console.log('canRequestAds error: ' + JSON.stringify(e));
}
```

Which logs:

canRequestAds error: {}

I call it after:

```
form = await consent.loadForm();
form.show();
```

I'm using:

admob-plus-cordova 2.0.0-alpha.14 
and 
cordova-plugin-consent 2.4.0  UMP_VERSION 2.0.0


Everything else seems to work. It loads and shows the form correctly. Is there an event handler that lets you know when the user has chosen their options?

Thanks in advance. Sean

**Comment by merbin2012** [comment]
@undergroundcreative  You are using  lower version of consent plugin,  update it to solve the issue
https://github.com/admob-plus/admob-plus/releases/tag/cordova-plugin-consent%403.0.0-alpha.6

**Comment by undergroundcreative** [comment]
Hi guys, could you let me know which versions you're using of:

- cordova android
- admob-plus-cordova
- cordova-plugin-consent
- UMP_VERSION

As I say, the code above worked up to await consent.canRequestAds() using:

admob-plus-cordova 2.0.0-alpha.14
and
cordova-plugin-consent 2.4.0 UMP_VERSION 2.0.0
and 
cordova android ^11.0.0

When I switched to admob-plus-cordova 3.0.0-alpha.6
and
UMP_VERSION 2.1.0

I get no further logs after I call await consent.getConsentStatus();

Could you also share any relevant code that would help me and others, as the deadline was yesterday?!

Many thanks,

Sean

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> Now when I click the Consent button on the form, close the app and reopen, I get the form popping up again asking for consent. This can't be right. My code is above. How do I detect if the user has already given or rejected consent?

@undergroundcreative

This is a well known bug / feature and can be solved by using a 2nd plugin (Android only).

See - https://github.com/admob-plus/admob-plus/issues/631#issuecomment-1834293370

And in more detail - https://github.com/admob-plus/admob-plus/issues/601#issuecomment-1702578477

**Comment by undergroundcreative** [comment]
Thanks @1n3JgKl9pQ6cUMrW , I've been following the issue on #601 - all your input is much appreciated.

I did see that 2nd plugin but as I'm using Ionic Appflow to build my app, I don't know how I'd get it to install. I see you had to download and unzip it in order to install it, but I don't know how that could work with Appflow. Any ideas?

Many thanks again :)

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
You can install every plug-in you want, locally.

Just download the .zip from Git or another source and point to the unzipped folder when installing.

Cordova has a manual for this in the official docs, and the same if for Ionic, I think;

https://stackoverflow.com/questions/45976858/unable-to-add-a-cordova-plugin-from-local-folder

**Comment by undergroundcreative** [comment]
Appflow is a remote build tool though, so I don't think the instructions in that link would apply?

[https://ionic.io/appflow](https://ionic.io/appflow)
