### ISSUE TITLE
[Funding Question] Availability of premium support?

### ISSUE THREAD

**Issue by svzi** [admob-plus/admob-plus#65]
Hi @ratson,

I'm strongly considering becoming a funder of your very nice plugin. So I'm wondering is there any way to get some kind of private support on this plugin? That alone would make me start a subscription instantly.

Best,
Sven

**Comment by ratson** [comment]
Thank you for raising this. I realised that I failed to promote the [Corporate Plan](https://github.com/admob-plus/admob-plus/issues/66) in a place where people would see it, cerated and pinned the issue to see if it helps.

**Comment by darkguy2008** [comment]
+1 to this, I hardly have $150/mo to spare just to get fast replies on a plugin. I would join a Patreon or something, considering I'm having a problem right now where the plugin doesn't build for iOS...
