### ISSUE TITLE
Corporate Plan

### ISSUE THREAD

**Issue by ratson** [admob-plus/admob-plus#66]
I maintain this project in my spare time, so issues raised here will only be handled when I have time.
For those who need better support, there are [Corporate Plans](https://ratson.name/fund-admob-plus/#corporate-plan) for subscription.

Any financial support would help me to keep improving the quality of this project!

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by ratson** [comment]
Move to https://github.com/admob-plus/admob-plus/discussions/271
