### ISSUE TITLE
Error "Alternatively, if you do not collect cookies for tracking purposes, revise the cookie..."

### ISSUE THREAD

**Issue by hooliapps** [admob-plus/admob-plus#660]
Hello

I display iOS ATT Form then CMP.

My app was refused because, if user say "No" at IOS ATT Form, then on CMP Google message "XXX asks for your consent to use your personal data to:".

How to have a Label who works even if user say "No" or "Yes" to ATT form please ?

Of course, if user say "No" to Track, and "Yes" to Google CMP, i checked, then Google use non-personalised ads.

Best regards

Message from Apple:
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
You collect data to track after the user selects "Ask App Not to Track" on the App Tracking Transparency permission request.

Specifically, we noticed the app accesses web content you own and collects cookies for tracking after the user asked you not to track them.

Next Steps

To resolve this issue, please revise the app so that you do not collect data for tracking purposes if the user does not give permission for tracking.

Alternatively, if you do not collect cookies for tracking purposes, revise the cookie prompts that appear in the app to clarify you do not track users.

Resources

- Tracking is linking data collected from the app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking).
- See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).

Support

- Reply to this message in your preferred language if you need assistance. If you need additional support, use the [Contact Us module](https://developer.apple.com/contact/topic/#!/topic/select).
- Consult with fellow developers and Apple engineers on the [Apple Developer Forums](https://developer.apple.com/forums/).
- Help improve the review process or identify a need for clarity in our policies by [suggesting guideline changes](https://developer.apple.com/contact/app-store/?topic=guideline).

**Comment by TheNotorius0** [comment]
That's because first you need to show Google UMP, then the ATT (if the user has chosen to consent, otherwise it won't show).

Anyway, you should create both the GDPR and ATT message on AdMob, they handle it automatically. For example, this is my code, I don't have to do anything else and it works:

```
if (await consent.canRequestAds()) {

    showAd();
          
} else {

    await consent.requestInfoUpdate();
    await consent.loadAndShowIfRequired();

    if (await consent.canRequestAds()) {

        showAd();
     }
}
```

**Comment by hooliapps** [comment]
Thanks, with this code is ok.
