### ISSUE TITLE
Promote Your App

### ISSUE THREAD

**Issue by ratson** [admob-plus/admob-plus#68]
You are welcome to submit PR as [a plugin user](https://admob-plus.github.io/users).

**Comment by acerbastimur** [comment]
Hello, I'm using your plugin on my project called 'Talk a While' which is on Google Play Store now, can you please add it into promotion page ?

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by ratson** [comment]
@acerbastimur Added https://github.com/admob-plus/admob-plus/commit/c307da24fb86e2d026e1b4be0f316117fc8a0156

**Comment by ratson** [comment]
Move to https://github.com/admob-plus/admob-plus/discussions/272
