### ISSUE TITLE
The plugin is not loading any testing or real ads

### ISSUE THREAD

**Issue by keev-studio** [admob-plus/admob-plus#682]
**Describe the bug**
The plugin is not loading any test or real ads. admob.start() function might be hanging or failing without throwing a visible error. Logcat screenshot attached.

**To Reproduce**
1.Installing the basic default latest cordova app and using android13
2. add admob-plus-cordova plugin
3. Call Banner or Interstitial Ad
4. check chrome://inspect

**Expected behavior**
I expect to see an ad loaded in chrome://inspect webview

**Screenshots**
I run LogCat in Android studio but I am unable to interpret the issues
![error](https://github.com/user-attachments/assets/185a9a95-67dd-4aa3-a922-a8bbb75b270a)

**Environment**
Windows

```
AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.19045
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 3.37 GB / 11.91 GB
    Binaries:
      Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    Languages:
      Java: 17.0.12
    npmPackages:
      admob-plus-cordova: 2.0.0-alpha.18 => 2.0.0-alpha.18
      cordova-android: ^13.0.0 => 13.0.0
      cordova-plugin-enable-multidex: ^0.2.0 => 0.2.0
      cordova-plugin-fullscreen: ^1.3.0 => 1.3.0
    Cordova:
      Version: 12.0.0 (cordova-lib@12.0.1)
      Plugins:
        cordova-plugin-fullscreen: ^1.3.0
        cordova-plugin-enable-multidex: ^0.2.0
        admob-plus-cordova: 2.0.0-alpha.18
    Ionic:
      Version: 7.2.0
    AndroidManifest.xml:
      Version: -
```

**Additional context**
When I switch back to plugin version 1.8 ads are shown, but in version 2 not

Thank you for your hard work, I really appreciate that.

**Comment by alpertuna** [comment]
I experienced the same issue, `await admod.start()` was hanging.
And solved by adding this config to config.xml
```
  <platform name="android">
    <preference name="AdMobPlusWebViewAd" value="true" />
    <preference name="AndroidXEnabled" value="true" />
    <preference name="GradlePluginKotlinEnabled" value="true" />
    <allow-intent href="market:*" />
  </platform>
```

I saw that in the admob cordova example. https://github.com/admob-plus/admob-plus/blob/master/examples/cordova/config.xml
It turned out only `<preference name="GradlePluginKotlinEnabled" value="true" />` was enough.

Also, this is discussed here https://github.com/admob-plus/admob-plus/issues/645#issuecomment-1999223571
And, here is from the documentation https://admob-plus.github.io/docs/cordova/upgrade

I think this config should be mentioned in getting started part of the document

**Comment by keev-studio** [comment]
Hi, you are completely right
<preference name="GradlePluginKotlinEnabled" value="true" />
will make the ads to load correctly.

I suppose its my fault to dont notice this in the Docs. I am sorry.

Thank you for your help

**Comment by keev-studio** [comment]
Fixed by adding 
` <preference name="GradlePluginKotlinEnabled" value="true" />`
to Cordova config.xml file
