### ISSUE TITLE
Just spelling fixe on your website :) https://admob-plus.github.io 

### ISSUE THREAD

**Issue by melvinfelixpons** [admob-plus/admob-plus#70]
https://admob-plus.github.io/docs/installation.html

=> For Android developer, com.google.android.gms:play-services-ads:$PLAY_SERVICES_VERSION >>>>>>> is is <<<<<<< available for configuration, the default is --PLAY_SERVICES_VERSION=16.0.0.

https://admob-plus.github.io/docs/ad-request-options.html

=> Check out the official >>>>>>> Andorid <<<<<<< and iOS doc for more info.

thanks for your plugin, i gave you 5$ buddy ;)

**Comment by ratson** [comment]
@melvinfelixpons Thank you for your report and support, much appreciated.
Fixed in https://github.com/admob-plus/admob-plus/commit/c3bdb0a204128ce6147eb2f0edf30f5c5f73d03d
