### ISSUE TITLE
GDPR Complaince

### ISSUE THREAD

**Issue by ssj7** [admob-plus/admob-plus#71]
Hi it is me again, is admob plus GDPR complainant? I didn't see any options or info regarding it.

**Comment by ssj7** [comment]
The extra non-personalized ads, where can we set this option in the plugin?

```
Bundle extras = new Bundle();
extras.putString("npa", "1");

AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();
```
From https://developers.google.com/admob/android/eu-consent#forward_consent_to_the_google_mobile_ads_sdk

**Comment by gartorware** [comment]
This is necesary I guess.
