### ISSUE TITLE
On orientation change banner ads overlap in iOS devices

### ISSUE THREAD

**Issue by wliadmin** [admob-plus/admob-plus#78]
W have created a new ionic 3 app, and use this plugin to show admob banner ads in footer.

We have checked the app and we found on device orientation change banner ads overlap in iOS devices. It's working fine in android devices.

Please find attached screenshot for the same.

![iphone6s_portrait_view](https://user-images.githubusercontent.com/9083810/53069176-05335380-3501-11e9-9f06-628b6a3a6e0a.png)

![iphone6s_landscape_view](https://user-images.githubusercontent.com/9083810/53069175-05335380-3501-11e9-82c0-03ae442d9b6c.png)

Could you please check for this issue and let us know for it's solutions?

**Comment by pilz97** [comment]
Hi @wliadmin 

Sorry for the question, but how did you configure the plugin that it work with iOS?
My android app works fine with the plugin but my iOS app Crashes after start.. (when i remove the plugin the iOS app works)

**Comment by dimitribocquet** [comment]
I have this issue too, do you have any solution/workaround?

**Comment by sta55en** [comment]
I'm seeing the same issue.
