### ISSUE TITLE
[iOS] Build error in Xcode 10.2. SWIFT_VERSION '3.0' is unsupported

### ISSUE THREAD

**Issue by andrey3diq** [admob-plus/admob-plus#87]
### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 615.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      npm: 6.8.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 27
        Build Tools: 24.0.1, 28.0.3
        System Images: a... | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0 - /usr/bin/javac
    npmPackages:
      cc.fovea.cordova.purchase: ^7.4.3 => 7.4.3 
      cordova-admob-plus: 0.25.1 => 0.25.1 
      cordova-android: 7.1.4 => 7.1.4 
      cordova-android-play-services-gradle-release: ^2.1.0 => 2.1.0 
      cordova-browser: 5.0.4 => 5.0.4 
      cordova-ios: 5.0.0 => 5.0.0 
      cordova-plugin-add-swift-support: ^1.7.2 => 1.7.2 
      cordova-plugin-apprate: ^1.4.0 => 1.4.0 
      cordova-plugin-background-mode: https://github.com/katzer/cordova-plugin-background-mode.git => 0.7.2 
      cordova-plugin-device: ^1.1.7 => 1.1.7 
      cordova-plugin-firebase: ^2.0.5 => 2.0.5 
      cordova-plugin-ionic-webview: ^1.2.1 => 1.2.1 
      cordova-plugin-local-notification: https://github.com/katzer/cordova-plugin-local-notifications.git => 0.9.0-beta.3 
      cordova-plugin-nativeaudio: https://github.com/andrey3diq/cordova-plugin-nativeaudio.git => 3.1.0 
      cordova-plugin-splashscreen: ^4.1.0 => 4.1.0 
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2 
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3 
      cordova-plugin-x-socialsharing: ^5.4.4 => 5.4.4 
      cordova-sqlite-storage: ^3.2.0 => 3.2.0 
      ionic-plugin-keyboard: ^2.2.1 => 2.2.1 
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 4.10.3

### Steps to Reproduce

My project based on ionic v3.

1. cordova build ios

### Expected Behavior

Build project successfully without errors.

### Actual Behavior

This error during build:
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.

### Reproducible Demo

I created a new cordova hello world project and added this plugin.
https://github.com/andrey3diq/cordova-admob-issue
Checkout repo and run these:
1. cordova platform add ios@latest
2. cordova build ios

**Comment by boreales** [comment]
You can change the Swift Version in the Build Settings of Xcode. Then it will build without error.

<img width="609" alt="Capture d’écran 2019-04-11 à 08 41 37" src="https://user-images.githubusercontent.com/21291577/55936143-c0d94f80-5c35-11e9-8212-4c68e03034a9.png">

**Comment by andrey3diq** [comment]
@boreales thanks for the workaround! I changed to Swift 5 and it can be built now.

**Comment by ratson** [comment]
@andrey3diq You can set the Swift version `config.xml`, e.g. https://github.com/admob-plus/admob-plus/blob/master/examples/basic/config.xml#L18
Installation documentation is update for this.
