### ISSUE TITLE
Invalid app ID 

### ISSUE THREAD

**Issue by DooDiddle** [admob-plus/admob-plus#91]
- Started with blank ionic 4 app
- added @admob-plus/ionic
- added cordova-admob-plus with appID
Tried running on the device. App crashes with Error Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to * 04-19 01:10:27.577 2009 2009 E AndroidRuntime: * find your app ID.

**Comment by DooDiddle** [comment]
got it working

**Comment by DTX-Elliot** [comment]
What was the problem and how did you get it working? I'm having the same problem

**Comment by maykon-oliveira** [comment]
Same problem

**Comment by pawel-marciniak** [comment]
> got it working

Can you give some explanation how you did it?
