### ISSUE TITLE
Compatible IONIC 4 ?

### ISSUE THREAD

**Issue by zigou13** [admob-plus/admob-plus#92]
Hello Admob plus, is it compatible with IONIC 4?

**Comment by fmendoza** [comment]
Yes

**Comment by zigou13** [comment]
Why have this error message? 
![IMG_4507](https://user-images.githubusercontent.com/32574412/56715855-1be06b80-6739-11e9-89d8-b0bbb5fe82f0.PNG)

**Comment by zigou13** [comment]
+1

**Comment by zigou13** [comment]
@ratson  please

**Comment by nathantaal** [comment]
Same problem as here:
https://github.com/admob-plus/admob-plus/issues/76#issuecomment-499010725

This issue should be closed.

**Comment by guikeller** [comment]
The plugin is compatible with any version of Ionic 2+ if you don't mind losing the auto-complete/types.

```ts
private admobPlugin = (<any>window).AdMob;
private admobOpts = {
  id: {
    android: 'ca-app-pub-4929051959006705/9890750624'
  }
};

constructor(...) { }

protected showAd(): void {
  this.admobPlugin.setDevMode(true);
  this.admobPlugin.interstitial.load(this.admobOpts).then(loaded => {
      this.admobPlugin.interstitial.show().then(showed => {
         // showed the ad
      });
  });
}
```
