### ISSUE TITLE
inAppBrowser hides the banner ad

### ISSUE THREAD

**Issue by DooDiddle** [admob-plus/admob-plus#93]
I am using the inAppBrowser (https://github.com/apache/cordova-plugin-inappbrowser) inside my app and when it is launched I can no longer see the banner ad under the screen. Is there a way to make this work?

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk
