### ISSUE TITLE
Fresh Install: Firebase + abmob plus conflict when building for ios

### ISSUE THREAD

**Issue by evinkuraga** [admob-plus/admob-plus#94]
### Is this a bug report?

Yes

### Environment

```
npx: installed 86 in 7.618s

  AdMob Plus Environment Info:
    System:
      OS: macOS Mojave 10.14.4
      CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
      Memory: 1.05 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_201 - /usr/bin/javac
    npmPackages:
      cordova-admob-plus: ^0.28.2 => 0.28.2 
      cordova-ios: ^5.0.1 => 5.0.1 
      cordova-plugin-firebase: 2.0.5 => 2.0.5 
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3 
    npmGlobalPackages:
      cordova: 8.1.2

```

### Steps to Reproduce

(Write your steps here:)

1. cordova create testproj
2. cordova platform add ios@5.0.1
3. cordova plugin add cordova-plugin-firebase --save
4. cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-myvalues --variable APP_ID_IOS=ca-app-pub-myvalues
5. cordova run ios

### Expected Behavior

Build successfully.

### Actual Behavior

```
...
Build system information
warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'GoogleAppMeasurement')

Build system information
warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'nanopb')

** ARCHIVE FAILED **

xcodebuild: Command failed with exit code 65
```

### Reproducible Demo

This is a fresh install test as described in steps above.

### Other fix attempts

1. Tried to add cordova-plugin-enable-multidex 
No success. 

2. cordova plugin rm cordova-plugin-firebase
this works and archives successfully.. however it defies the purpose. :)

**Comment by 91-Soo** [comment]
I applied it this way.

ionic cordova plugin add cordova-admob-plus --variable APP_ID_ANDROID=ca-app-pub-1111 --variable APP_ID_IOS=ca-app-pub-1111 --variable PLAY_SERVICES_VERSION=15.0.1

**Comment by evinkuraga** [comment]
The above didn't work for me. Still getting exit code 65.

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk
