### ISSUE TITLE
Ionic 3 no test and no reward value

### ISSUE THREAD

**Issue by penseeartificielle** [admob-plus/admob-plus#95]
Hi there,

 First, thank you very much for your hard work ! I have two issues concerning admob-plus (4.20.0) for Ionic 3 (i only do rewardedvideos) :
- how do i enable test mode ? i tried to add isTesting to the AdUnitIDOption but it doesnt work (that's logical because it's not declared in the object). I've read also about setDev on the admob object, but this property does not exist (in another thread you said it was enabled with 0.6.0)

- how do i get the reward object once the video has completed ? Because right now, if i close the ad before the end, the response is still success and there is no object in it : 
that.admob.rewardVideo.show()
          .then((res) => { //res is empty, if i close the ad or watch it fully

- one bonus question not found in the docs : how do i use the property "on" ? what can i declare in it to have my watchers on the lifecycle of admob ?

thank you in advance, your help is greatly appreciated, i shall support this plugin if i can make some money with my app too ^^

**Comment by tijlreynhout** [comment]
I have the same question. because there seems no way to enable the test mode?
