### ISSUE TITLE
ionic 4 compile failures: error: use of undeclared type 'GADBannerViewDelegate' etc

### ISSUE THREAD

**Issue by madhusudhankonda** [admob-plus/admob-plus#96]
When building the app on ionic4 +admob plus, I get errors in AMSBanner.swift class:

Versions:
"@ionic-native/admob-plus": "^5.5.1"
"cordova-admob-plus": "^0.28.2"
"@ionic/angular": "^4.1.0"
"xcode": "^2.0.0"

Any help is much appreciated!

Thanks
/M

Please find the errors below:

Plugins/cordova-admob-plus/AMSBanner.swift:1:29: error: use of undeclared type 'GADBannerViewDelegate'
class AMSBanner: AMSAdBase, GADBannerViewDelegate {
                            ^~~~~~~~~~~~~~~~~~~~~
...
error: use of undeclared type 'GADAdSize'
    var adSize: GADAdSize!
                ^~~~~~~~~
...
 error: use of undeclared type 'GADRequest'
    func show(request: GADRequest) {

..
use of undeclared type 'GADBannerView'
    func adViewDidReceiveAd(_ bannerView: GADBannerView) {
                                          ^~~~~~~~~~~~~
....

**Comment by madhusudhankonda** [comment]
Any help please?

**Comment by remisture** [comment]
+1

**Comment by francoisduchemin** [comment]
I have the same issue...

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by evinkuraga** [comment]
Not sure if it's related, but i'm getting: 

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /localpath/myapp/src-cordova/platforms/ios/myapp/Plugins/cordova-admob-plus/AMSBanner.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal i386 /localpath/myapp/src-cordova/platforms/ios/myapp/Plugins/cordova-admob-plus/AMSBanner.swift
	CompileSwift normal i386 /localpath/myapp/src-cordova/platforms/ios/myapp/Plugins/cordova-admob-plus/AMSPlugin.swift
(4 failures)
xcodebuild: Command failed with exit code 65
```

**Comment by jasonandress** [comment]
@ratson @ratson0 any help is appreciated

**Comment by RobvandenBerg** [comment]
@evinkuraga I had exactly the same error. After digging around I found the problem: sendSubviewToBack is obsoleted.

In Xcode, I changed the following line in AMSBanner.swift (of the admob-plus plugin):
`view.sendSubviewToBack(background)`
to:
`view.sendSubview(toBack: background)`

After that the problem was solved.

**Comment by masterbd** [comment]
This is not working at all!

**Comment by nocodedweb** [comment]
Getting the same error message(s).  Has anyone been able to figure this one out?

I get 43 errors of similar variations when this plugin is installed:

Use of undeclared type 'GADRequest'
Use of undeclared type 'GADInterstitial'

etc.

Podfile is:

```
platform :ios '13.0'
target 'mytarget' do
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Google-Mobile-Ads-SDK', '~> 7.57'
end
```

Tried running

```
pod install
pod update
pod repo update
```

Have had no luck so far.

Xcode version 11.5, running on iOS 13.5.1.

**Comment by lucaele** [comment]
Same as @nocodedweb!

The following build commands failed:
	CompileSwift normal arm64 ...cordova-admob-plus/AMSAdBase.swift
	CompileSwift normal arm64 .../cordova-admob-plus/AMSBanner.swift
	CompileSwift normal arm64 .../cordova-admob-plus/AMSConstants.swift
	CompileSwift normal arm64 .../cordova-admob-plus/AMSInterstitial.swift
	CompileSwift normal arm64 .../cordova-admob-plus/AMSPlugin.swift
	CompileSwift normal arm64 ../cordova-admob-plus/AMSRewardVideo.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(7 failures)

Xcode version 11.6, running on iOS 11.00
Cordova 9.0.0 (cordova-lib@9.0.1)

Any idea?

**Comment by manel00** [comment]
Same to me @lucaele 
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/manel/Documents/ionic_projects/xstories/xstories/platforms/ios/XStories/Plugins/cordova-admob-plus/AMSRewardVideo.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```
