### ISSUE TITLE
ionic-admob not compatible with Ionic 4?

### ISSUE THREAD

**Issue by remisture** [admob-plus/admob-plus#98]
### Is this a bug report?

Yes

### Environment

AdMob Plus Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
      Memory: 331.52 MB / 24.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      cc.fovea.cordova.purchase: ^7.4.3 => 7.4.3
      cordova-admob-plus: 0.28.2 => 0.28.2
      cordova-android: 7.1.4 => 7.1.4
      cordova-clipboard: ^1.2.1 => 1.2.1
      cordova-ios: 4.5.5 => 4.5.5
      cordova-plugin-app-version: ^0.1.9 => 0.1.9
      cordova-plugin-device: ^2.0.2 => 2.0.2
      cordova-plugin-facebook4: ^4.2.1 => 4.2.1
      cordova-plugin-firebase: 2.0.5 => 2.0.5
      cordova-plugin-google-analytics: ^1.8.6 => 1.8.6
      cordova-plugin-inappbrowser: ^3.0.0 => 3.0.0
      cordova-plugin-ionic-keyboard: ^2.1.3 => 2.1.3
      cordova-plugin-ionic-webview: ^2.4.1 => 2.4.1
      cordova-plugin-shake: ^0.6.0 => 0.6.0
      cordova-plugin-splashscreen: ^5.0.2 => 5.0.2
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3
      cordova-sqlite-ext: ^2.3.1 => 2.3.1
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 4.12.0

AndroidManifest.xml: looks ok

### Steps to Reproduce

```
$ ionic cordova build ios
> ng run app:ionic-cordova-build:production --platform=ios

Date: 2019-05-12T10:44:53.199Z
Hash: 228111ec2385e66dcb2d
Time: 12550ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.01ecbc0fcff9207e8cde.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.a723c36635c3a098c2aa.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.8bda7e7b67c2c6eb5607.css (styles) 26.4 kB [initial] [rendered]
chunk {cordova} cordova.17fb1a7c009cbc8d5d42.js (cordova) 22.8 kB [entry] [rendered]

ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/ionic-admob/dist/index.d.ts(2,10): error TS2305: Module '"../../rxjs/Observable"' has no exported member 'Observable'.
```
### Expected Behavior

I expect to be able to use this plugin together with Ionic 4.

### Actual Behavior

I don't know what the problem is, but maybe rxjs 6 is not supported?

**Comment by chanxdesigns** [comment]
That can be solved using the @admob-plus/ionic instead of ionic-admob.
However I'm having problem of using the any admob plugin from service .. works in constructor but not work if run from a service...

**Comment by yuricamara** [comment]
Same problem here!

**Comment by chanxdesigns** [comment]
I found a quirk. If u use alerts inside the callback then you won't see the ad instead a black screen will be shown.. don't know the reason but found it after a hard debugging.. now the problem is solved...

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by oangelo** [comment]
I am having problems too, but my app does not even starts at the AVD when I add the cordova plugin. Anybody else having this problem? Any idea how to solve this?

**Comment by Diicepoo** [comment]
Same problem here!
